// Regression for real deployed screenshot c-continuous-first-deck.jpg (e9d35da).
// Prior geometry/unit passes did NOT cover off-ship support context.
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{createHash}from'node:crypto';
import{createVoyageCampaign,VOYAGE_VESSEL_GEOMETRY as G}from'../src/campaigns/c/content.js';
import{projectVoyageScene,projectDockContext,vesselPoint,berthPoint,QUAY_WATER_GAP_METRES}from'../src/rendering/c-adapter.js';
import{ACCEPTED_MAP_MATERIALS}from'../src/rendering/material-assets.js';import{replayCampaignCertificate}from'../src/solver/campaign-replay.js';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} ~= ${b}`),inside=(p,poly)=>poly.every((a,i)=>{const b=poly[(i+1)%poly.length];return(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0])>=-1e-8;});
function deckState(r){let s=r.initialState();for(const action of[{type:'move',direction:'left'},{type:'traverse',edgeId:'C-M01.board'}]){const next=r.dispatch(s,action);assert.equal(next.ok,true);s=next.state;}return s;}
test('current berth context is derived only from its real shore cells; gangway sampling is not invented land',()=>{const r=createVoyageCampaign();for(let n=1;n<=5;n++){const id=`C-M0${n}`,dock=r.region(id),context=projectDockContext(r,id,true);assert.equal(context.dockId,id);assert.equal(context.sourceMap,dock.map.join('|'));assert.equal(context.polygons.length,27);assert.ok(!context.polygons.some(p=>p.sourceCell.join()==='6,7'));for(const p of context.polygons){const[x,y]=p.sourceCell;assert.ok(['.','#'].includes(dock.map[y][x]));for(const[px,py]of p.berthPolygon){assert.ok(px>=x-.5&&px<=x+.5);assert.ok(py>=y-.5&&py<=y+.5);}}const shore=projectDockContext(r,id,false);for(let i=0;i<context.polygons.length;i++)for(let j=0;j<4;j++){assert.deepEqual(context.polygons[i].polygon[j],berthPoint(context.polygons[i].berthPolygon[j],true));assert.deepEqual(shore.polygons[i].polygon[j],berthPoint(context.polygons[i].berthPolygon[j],false));}}});
test('both mooring lines end on the same supported, permanently visible berth bollards in both camera scales',()=>{const r=createVoyageCampaign(),s=deckState(r);for(let n=1;n<=5;n++){s.boat.dock=`C-M0${n}`;const v=projectVoyageScene(r,s),m=v.fixtures.mooring;assert.equal(m.dockId,s.boat.dock);assert.equal(m.bollards.length,2);assert.equal(m.lines.length,2);for(let i=0;i<2;i++){assert.deepEqual(m.fairleads[i],vesselPoint([G.fixtures.mooring.bowFairleadXYZ,G.fixtures.mooring.sternFairleadXYZ][i],true));assert.deepEqual(m.bollards[i],berthPoint(G.fixtures.mooring.shoreBollardsGrid[i],true));assert.deepEqual(m.lines[i].from,m.fairleads[i]);assert.deepEqual(m.lines[i].to,m.bollards[i]);assert.ok(v.dockContext.polygons.some(p=>inside(m.bollards[i],p.polygon)));assert.equal(v.structures.filter(c=>c.structureId===`shore-bollard-${i}`).length,1);}s.boat.moored=false;const unmoored=projectVoyageScene(r,s);assert.equal(unmoored.fixtures.mooring.lines.length,0);assert.equal(unmoored.structures.filter(c=>c.structureId?.startsWith('shore-bollard-')).length,2);s.boat.moored=true;}
 for(const id of['C-M03','C-M05']){s.location.regionId=id;s.boat.dock=id;const v=projectVoyageScene(r,s);for(let i=0;i<2;i++){assert.deepEqual(v.fixtures.mooring.bollards[i],berthPoint(G.fixtures.mooring.shoreBollardsGrid[i],false));assert.ok(v.dockContext.polygons.some(p=>inside(v.fixtures.mooring.bollards[i],p.polygon)));}}});
test('one gangway has a hull bearing and a quay bearing across a narrow water gap without adding navigable deck cells',()=>{const r=createVoyageCampaign(),s=deckState(r),before=r.serialize(s),spec=JSON.stringify(r.spec),v=projectVoyageScene(r,s),g=v.fixtures.gangway;assert.equal(g.supports.length,2);assert.deepEqual(g.centerline,G.berthSampling.gangwayCenterlineGrid.map(p=>berthPoint(p,true)));assert.ok(inside(g.supports[0].at,v.hullOutline));assert.ok(v.dockContext.polygons.some(p=>inside(g.supports[1].at,p.polygon)));assert.equal(v.structures.filter(c=>c.structureId==='unique-gangway').length,1);assert.equal(v.structures.filter(c=>c.structureId?.startsWith('gangway-')&&c.structureId.endsWith('-bearing')).length,2);close(g.width*G.deckSampling.pitch,.45);
 const right=Math.max(...v.hullOutline.map(p=>p[0])),shoreX=Math.min(...v.dockContext.polygons.flatMap(p=>p.polygon.map(p=>p[0])));close((shoreX-right)*G.deckSampling.pitch,QUAY_WATER_GAP_METRES);assert.equal(v.passability.flat().filter(Boolean).length,42);for(let y=0;y<11;y++)for(let x=0;x<11;x++){assert.equal(v.passability[y][x],r.passable(s,x,y));if(v.contextCellDescriptions[y][x]){assert.equal(r.passable(s,x,y),false);assert.match(v.contextCellDescriptions[y][x],/岸.*跳板/);}}
 assert.equal(r.serialize(s),before);assert.equal(JSON.stringify(r.spec),spec);assert.equal(r.dispatch(s,{type:'move',direction:'right'}).ok,false);const exit=r.dispatch(s,{type:'traverse',edgeId:'c.leaveDeck'});assert.equal(exit.ok,true);assert.deepEqual(exit.state.location,{regionId:'C-M01',x:7,y:7});});
test('same plank source now means a 2.4m X cycle and 6m unbroken Y in both scales, with unchanged pixels',()=>{const r=createVoyageCampaign(),s=deckState(r),deck=projectVoyageScene(r,s).surfaces.find(p=>p.id==='C_FERRY_HULL_01-deck');s.location.regionId='C-M03';s.boat.dock='C-M03';const shore=projectVoyageScene(r,s).surfaces.find(p=>p.id==='C_FERRY_HULL_01-deck');close(deck.uv.periodX,4);close(deck.uv.periodX*G.deckSampling.pitch,2.4);close(shore.uv.periodX*G.berthSampling.metresPerCell,2.4);close(deck.uv.height*G.deckSampling.pitch,6);close(shore.uv.height*G.berthSampling.metresPerCell,6);close(deck.uv.periodX/shore.uv.periodX,5/3);const material=ACCEPTED_MAP_MATERIALS.find(a=>a.id==='warm-planks');assert.equal(material.mode,'repeat-x-preview');assert.match(material.physicalUV,/4 deck tiles = 2.4m/);assert.match(material.physicalUV,/8–9 visible plank/);assert.doesNotMatch(material.physicalUV,/4\.8m|8 deck tiles/);const bytes=readFileSync(new URL('../public/'+material.file,import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),material.sha256);});
test('all three frozen actual victory certificates still replay under unchanged content identity',()=>{const r=createVoyageCampaign();assert.equal(r.identity.contentHash,'c5a5f809d5548f36');for(const name of['c-normal','c-normal-short-bypass','c-normal-bypass-short']){const cert=JSON.parse(readFileSync(new URL(`../artifacts/campaigns/${name}.certificate.json`,import.meta.url)));assert.equal(replayCampaignCertificate(r,cert).ok,true);}});

test('when the existing M05 quay becomes visible, the single unloaded crate and same rollway use its berth projection',()=>{const r=createVoyageCampaign(),cert=JSON.parse(readFileSync(new URL('../artifacts/campaigns/c-normal.certificate.json',import.meta.url)));let state=r.initialState();for(const step of cert.steps){state=r.dispatch(state,step.action).state;if(step.action.entityId==='c.unload'){const v=projectVoyageScene(r,state),cargo=v.fixtures.cargo;assert.equal(state.location.regionId,'C-D01');assert.equal(cargo.length,1);assert.equal(cargo[0].state,'ashore');assert.deepEqual(cargo[0].sourceCell,[r.entity('c.rollCargo').x,r.entity('c.rollCargo').y]);assert.deepEqual(cargo[0].at,berthPoint(cargo[0].sourceCell,true));assert.ok(v.dockContext.polygons.some(p=>inside(cargo[0].at,p.polygon)));assert.ok(v.structures.some(o=>o.structureId==='same-shore-rollway'));return;}}assert.fail('unload not reached');});
