// Executes the real app against DOM doubles; this is NOT a browser visual signoff.
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.events={};this.style={};this.open=false;this.hidden=false;this.disabled=false;this.classes=new Set();this.classList={add:(...s)=>s.forEach(x=>this.classes.add(x))};}append(...n){this.children.push(...n);}replaceChildren(...n){this.children=[...n];}setAttribute(k,v){this[k]=v;}addEventListener(k,v){this.events[k]=v;}showModal(){this.open=true;}close(){this.open=false;}}
const html=readFileSync(new URL('../public/campaigns/index.html',import.meta.url),'utf8'),source=readFileSync(new URL('../public/campaigns/app.js',import.meta.url),'utf8').replaceAll("from '../src/",`from '${new URL('../src/',import.meta.url).href}`);
function environment(storage){const nodes=new Map([...html.matchAll(/<([a-z-]+)[^>]*\bid="([^"]+)"[^>]*>/g)].map(([,tag,id])=>[id,new Element(tag)])),dirs=['up','down','left','right'].map(dir=>{const el=new Element('button');el.dataset.dir=dir;return el;}),events={};return{nodes,dirs,window:{},localStorage:storage,document:{getElementById:id=>nodes.get(id),createElement:tag=>new Element(tag),querySelector:selector=>selector==='dialog[open]'?[...nodes.values()].find(n=>n.tagName==='DIALOG'&&n.open)??null:null,querySelectorAll:selector=>selector==='[data-dir]'?dirs:[],addEventListener:(type,fn)=>events[type]=fn},events};}
test('C real UI blocks map, pad, keyboard and repeated actions behind story/confirmation, cancel is pure and reload retains state',async()=>{
 const entries=new Map(),storage={getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v),removeItem:k=>entries.delete(k)},keys=['window','document','localStorage','confirm','setTimeout','clearTimeout'],saved=Object.fromEntries(keys.map(k=>[k,globalThis[k]]));
 try{const env=environment(storage);Object.assign(globalThis,{...env,confirm:()=>true,setTimeout:()=>0,clearTimeout:()=>{}});await import(`data:text/javascript;base64,${Buffer.from(source+'\n// first-ui-load').toString('base64')}`);
 const get=id=>env.nodes.get(id),state=()=>env.window.__CAMPAIGN_PREVIEW__.getState(),pad=d=>env.dirs.find(b=>b.dataset.dir===d).onclick(),key=k=>env.events.keydown({key:k,preventDefault(){}}),map=(x,y)=>get('board').children[y*11+x].onclick();assert.equal(get('board').children.length,121);assert.ok(get('map-canvas'));pad('right');for(let i=0;i<5;i++)pad('up');get('actions').children.find(row=>row.children[0]?.textContent?.includes('核对货单')).children[0].onclick();assert.equal(get('story').open,true);const initial=JSON.stringify(state());pad('left');key('ArrowLeft');map(6,7);assert.equal(JSON.stringify(state()),initial);
 let limit=100;while(get('story').open&&limit--)get('story-skip').onclick();assert.ok(limit>0);pad('down');pad('down');pad('down');assert.deepEqual(state().location,{regionId:'C-M01',x:8,y:5});
 const requestShop=()=>get('actions').children.find(row=>row.children[0]?.textContent?.includes('护航护具')).children[0].onclick();requestShop();assert.equal(get('confirmation').open,true);const before=JSON.stringify(state());pad('up');key('ArrowUp');map(8,4);requestShop();assert.equal(JSON.stringify(state()),before);get('confirm-cancel').onclick();assert.equal(get('confirmation').open,false);assert.equal(JSON.stringify(state()),before);
 requestShop();get('confirm-yes').onclick();const after=JSON.stringify(state());assert.equal(state().stats.gold,3);assert.equal(state().stats.def,10);get('confirm-yes').onclick();assert.equal(JSON.stringify(state()),after);
 const e2=environment(storage);Object.assign(globalThis,{...e2,confirm:()=>true,setTimeout:()=>0,clearTimeout:()=>{}});await import(`data:text/javascript;base64,${Buffer.from(source+'\n// refresh-ui-load').toString('base64')}`);assert.equal(JSON.stringify(e2.window.__CAMPAIGN_PREVIEW__.getState()),after);assert.equal(e2.nodes.get('board').children.length,121);
 }finally{for(const k of keys)if(saved[k]===undefined)delete globalThis[k];else globalThis[k]=saved[k];}
});

test('C actual D01 buttons describe projected shore truthfully; shore clicks do not move or teleport, only the existing portal exits',async()=>{
 const{createVoyageCampaign}=await import('../src/campaigns/c/content.js'),{createSaveRepository}=await import('../src/core/campaign.js'),r=createVoyageCampaign();let state=r.initialState();for(const action of[{type:'move',direction:'left'},{type:'traverse',edgeId:'C-M01.board'}]){const next=r.dispatch(state,action);assert.equal(next.ok,true);state=next.state;}
 const entries=new Map(),storage={getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v),removeItem:k=>entries.delete(k)};createSaveRepository(storage,r).save('auto',state,{seenIds:[],queue:[],turnIndex:0});const keys=['window','document','localStorage','confirm','setTimeout','clearTimeout'],saved=Object.fromEntries(keys.map(k=>[k,globalThis[k]]));
 try{const env=environment(storage);Object.assign(globalThis,{...env,confirm:()=>true,setTimeout:()=>0,clearTimeout:()=>{}});await import(`data:text/javascript;base64,${Buffer.from(source+'\n// dock-support-qa').toString('base64')}`);const get=id=>env.nodes.get(id);let limit=100;while(get('story').open&&limit--)get('story-skip').onclick();assert.ok(limit>0);assert.equal(get('board').children.length,121);const tile=get('board').children[5*11+9];assert.match(tile['aria-label'],/岸上.*跳板/);assert.doesNotMatch(tile['aria-label'],/水面/);const before=JSON.stringify(env.window.__CAMPAIGN_PREVIEW__.getState());tile.onclick();assert.match(get('status').textContent,/岸上.*跳板/);assert.equal(JSON.stringify(env.window.__CAMPAIGN_PREVIEW__.getState()),before);const exit=get('actions').children.find(row=>row.children[0]?.textContent?.includes('回到当前泊位岸上'));assert.ok(exit);exit.children[0].onclick();assert.deepEqual(env.window.__CAMPAIGN_PREVIEW__.getState().location,{regionId:'C-M01',x:7,y:7});}finally{for(const k of keys)if(saved[k]===undefined)delete globalThis[k];else globalThis[k]=saved[k];}
});
