// C-scoped copy of six unchanged shared/C assertions from the frozen continuous samples r1 package.
import test from 'node:test';import assert from 'node:assert/strict';
import{createVoyageCampaign,VOYAGE_VESSEL_GEOMETRY as G}from'../src/campaigns/c/content.js';
import{compileBoundaryRuns,renderContinuousMap,setMaterialImage,fitMapViewport,command,label}from'../src/rendering/continuous-map.js';
import{projectVoyageScene}from'../src/rendering/c-adapter.js';
import{readFileSync}from'node:fs';
const mock=()=>{const calls=[];const ctx=new Proxy({calls},{get(o,k){if(k in o)return o[k];return(...args)=>calls.push([k,...args]);},set(o,k,v){o[k]=v;return true;}});return ctx;};
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} ~= ${b}`);
test('union boundaries close straight, convex, concave, T, cross and diagonal masks without inner seams',()=>{
 const shapes=[[[0,0]],[[0,0],[1,0],[2,0]],[[0,0],[1,0],[0,1]],[[0,0],[1,0],[2,0],[1,1]],[[1,0],[0,1],[1,1],[2,1],[1,2]],[[0,0],[1,1]]];
 for(const cells of shapes){const runs=compileBoundaryRuns(cells),n=new Set(cells.map(String));let perimeter=0;for(const[x,y]of cells)for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]])if(!n.has([x+dx,y+dy].join()))perimeter++;assert.equal(runs.reduce((a,b)=>a+Math.hypot(b.points[1][0]-b.points[0][0],b.points[1][1]-b.points[0][1]),0),perimeter);const vertices=new Map();for(const r of runs)for(const p of r.points)vertices.set(String(p),(vertices.get(String(p))??0)+1);assert.ok([...vertices.values()].every(n=>n%2===0));}
 assert.equal(compileBoundaryRuns([[0,0],[1,0],[2,0]]).length,4);assert.equal(compileBoundaryRuns([[0,0],[1,1]]).length,8);
});
test('surface union is clipped once and world UV never restarts on each gameplay cell',()=>{
 const ctx=mock(),image={width:1024,height:1024};setMaterialImage('dry-stone',image,{mode:'world-domain'});const camera=renderContinuousMap(ctx,{width:11,height:11,surfaces:[{material:'dry-stone',cells:[[0,0],[1,0],[2,0]]}]},{width:360,height:360,dpr:2});assert.equal(ctx.calls.filter(c=>c[0]==='clip').length,1);assert.deepEqual(ctx.calls.find(c=>c[0]==='drawImage').slice(2),[0,0,11,11]);assert.deepEqual(camera.cellAt(359,359),{x:10,y:10});close(camera.scale,360/11);assert.deepEqual(ctx.calls.find(c=>c[0]==='setTransform').slice(1),[2,0,0,2,0,0]);
});
test('C reuses exact same 2:1 hull with isotropic 5/3 zoom, six flush slots and exactly three state-bound weights',()=>{
 const r=createVoyageCampaign(),state=r.initialState(),base=r.stateHash(state);state.location={regionId:'C-D01',x:7,y:7};const deck=projectVoyageScene(r,state);state.location={regionId:'C-M03',x:7,y:7};const berth=projectVoyageScene(r,state);const extent=s=>[Math.max(...s.hullOutline.map(p=>p[0]))-Math.min(...s.hullOutline.map(p=>p[0])),Math.max(...s.hullOutline.map(p=>p[1]))-Math.min(...s.hullOutline.map(p=>p[1]))];const a=extent(deck),b=extent(berth);close(a[1]/a[0],2);close(b[1]/b[0],2);close(a[0]/b[0],5/3);close(a[1]/b[1],5/3);for(const s of[deck,berth]){assert.equal(s.geometryId,G.geometryId);assert.equal(s.fixtures.slots.length,6);assert.equal(s.fixtures.weights.length,3);assert.deepEqual(s.fixtures.weights.map(w=>w.id).sort(),['w1','w2','w3']);assert.equal(s.fixtures.cargo.length,1);assert.equal(s.structures.filter(o=>o.structureId==='unique-gangway').length,1);}
 state.location={regionId:'C-D01',x:7,y:7};for(let n=1;n<=5;n++){state.boat.dock=`C-M0${n}`;const hash=r.stateHash(state),s=projectVoyageScene(r,state);assert.equal(s.visibleEntities.includes('c.openBarrier'),n===3);assert.equal(s.visibleEntities.includes('c.unload'),n===5);assert.equal(s.passability.flat().filter(Boolean).length,42);assert.equal(r.stateHash(state),hash);}assert.equal(r.identity.contentHash,'c5a5f809d5548f36');
});
test('C legal certificate states show one cargo, connected winch, crane, empty racks and retained closed bad platform',()=>{
 const r=createVoyageCampaign(),cert=JSON.parse(readFileSync(new URL('../artifacts/campaigns/c-normal.certificate.json',import.meta.url)));let s=r.initialState(),seen=new Set();for(const step of cert.steps){const out=r.dispatch(s,step.action);assert.equal(out.ok,true);s=out.state;if(!['C-D01','C-M03','C-M05'].includes(s.location.regionId))continue;const before=r.stateHash(s),scene=projectVoyageScene(r,s);assert.equal(r.stateHash(s),before);assert.equal(scene.fixtures.weights.length,3);assert.equal(scene.structures.filter(o=>o.structureId?.startsWith('rack-')).length,3);assert.equal(scene.fixtures.cargo.length,1);if(s.boat.dock==='C-M03'&&s.boat.cargo==='left'){assert.ok(scene.fixtures.devices.some(d=>d.id==='one-gate-winch'));seen.add('winch');}if(s.boat.dock==='C-M05'){assert.ok(scene.fixtures.devices.some(d=>d.id==='one-cargo-davit'));seen.add('crane');}if(s.location.regionId==='C-M05'){assert.equal(scene.passability[3][10],false);seen.add('bad-platform');}if(s.boat.cargo==='ashore')seen.add('unload');}assert.deepEqual([...seen].sort(),['bad-platform','crane','unload','winch']);assert.equal(s.victory,true);
});
test('desktop map sizing reserves the full trailing controls; short/mobile-sized budgets remain scrollable',()=>{assert.equal(fitMapViewport({viewportHeight:757,top:220,trailing:150,width:520}),371);assert.equal(fitMapViewport({viewportHeight:900,top:230,trailing:160,width:610}),494);assert.equal(fitMapViewport({viewportHeight:620,top:220,trailing:150,width:400}),308);assert.equal(fitMapViewport({viewportHeight:600,top:300,trailing:160,width:280}),280);});

test('approved texture axes keep wood Y continuous and C deck/berth UV physically identical',()=>{const r=createVoyageCampaign(),s=r.initialState();s.location={regionId:'C-D01',x:7,y:7};const d=projectVoyageScene(r,s).surfaces.find(x=>x.id==='C_FERRY_HULL_01-deck');s.location={regionId:'C-M03',x:7,y:7};const b=projectVoyageScene(r,s).surfaces.find(x=>x.id==='C_FERRY_HULL_01-deck');close(d.uv.periodX/b.uv.periodX,5/3);close(d.uv.height/b.uv.height,5/3);setMaterialImage('warm-planks',{width:1254,height:1254},{mode:'repeat-x-preview',periodX:4});const ctx=mock();renderContinuousMap(ctx,{width:11,height:11,surfaces:[{material:'warm-planks',cells:[[1,1],[2,1]],uv:{origin:[0,1],periodX:4,height:1}}]});const images=ctx.calls.filter(x=>x[0]==='drawImage');assert.equal(images.length,3);assert.ok(images.every(c=>c[3]===1&&c[5]===1),'one Y-domain only');command(ctx,label(0,0,'L1',.1,'#fff',{minPixels:7}),30);close(parseFloat(ctx.font.split(' ')[1])*30,7);});
