// Actual app import with deterministic DOM/canvas/RAF helpers. No real browser.
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{createForestCampaign}from'../src/campaigns/b/content.js';
import{createSaveRepository}from'../src/core/campaign.js';
import{createForestPreviewSession}from'../src/campaigns/b/preview-session.js';
import{createFineForestSaveExtension}from'../src/rendering/forest-fine-save.js';
import{nativeWorldCell}from'../src/rendering/forest-world-native.js';
const html=readFileSync(new URL('../public/campaigns-b/index.html',import.meta.url),'utf8');
const context=()=>new Proxy({measureText:t=>({width:t.length*7}),createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}}),getImageData:(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4),width:w,height:h})},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.events={};this.style={};this.open=false;this.hidden=false;this.disabled=false;this.classList={add(){}};if(tag==='canvas')this.getContext=()=>this.context??=context();}append(...c){this.children.push(...c);}replaceChildren(...c){this.children=c;}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}addEventListener(k,v){this.events[k]=v;}showModal(){this.open=true;}close(){this.open=false;}getBoundingClientRect(){return{width:700,height:500,left:0,top:0};}}
function memory(){const entries=new Map();return{entries,getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v),removeItem:k=>entries.delete(k)};}
async function boot(storage=memory()){
 const nodes=new Map([...html.matchAll(/<([a-z-]+)[^>]*\bid="([^"]+)"[^>]*>/g)].map(([,tag,id])=>[id,new Element(tag)])),dirs=['up','down','left','right'].map(dir=>{const b=new Element('button');b.dataset.dir=dir;return b;}),events={},windowEvents={},frames=new Map(),images=[];let clock=0,id=0;
 const document={hidden:false,getElementById:id=>nodes.get(id),createElement:t=>new Element(t),createTextNode:t=>({textContent:t}),querySelector:s=>s==='dialog[open]'?[...nodes.values()].find(n=>n.tagName==='DIALOG'&&n.open)??null:null,querySelectorAll:s=>s==='[data-dir]'?dirs:s==='[data-close]'?[]:[],addEventListener:(k,fn)=>events[k]=fn};
 class Image{set src(s){this.url=s;this.naturalWidth=s.includes('hero-four-views')?1774:s.includes('world-')?4096:1024;this.naturalHeight=s.includes('hero-four-views')?887:s.includes('world-')?1792:1536;images.push(this);}get src(){return this.url;}}
 const saved={};for(const k of['window','document','confirm','requestAnimationFrame','cancelAnimationFrame','Image','setTimeout','clearTimeout'])saved[k]=globalThis[k];Object.assign(globalThis,{window:{localStorage:storage,addEventListener:(k,fn)=>windowEvents[k]=fn},document,confirm:()=>true,Image,requestAnimationFrame:fn=>{frames.set(++id,fn);return id;},cancelAnimationFrame:i=>frames.delete(i),setTimeout:()=>0,clearTimeout:()=>{}});
 let code=readFileSync(new URL('../public/campaigns-b/app.js',import.meta.url),'utf8').replaceAll("from '../src/",`from '${new URL('../src/',import.meta.url).href}`);code+=`\n// unique harness ${Math.random()}\n//# sourceURL=fine-entry-harness.js`;await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);for(const image of images.splice(0))image.onload?.();
 const qa=window.__FOREST_PREVIEW__,get=k=>nodes.get(k),tick=(n=25,dt=100)=>{for(let i=0;i<n;i++){clock+=dt;const callbacks=[...frames.values()];frames.clear();for(const fn of callbacks)fn(clock);assert.ok(frames.size<=1,`fine entry must retain one animation driver, found ${frames.size}`);}},down=(key,code,extra={})=>events.keydown({key,code,target:{tagName:'BODY'},repeat:false,preventDefault(){},...extra}),up=(key,code)=>events.keyup({key,code}),tap=(key,code)=>{down(key,code);up(key,code);},click=id=>get('board').children.find(n=>n.dataset.fineNode===id).onclick();
 return{qa,get,tick,down,up,tap,click,storage,events,windowEvents,document,restore:()=>Object.assign(globalThis,saved)};
}


import {buildForestWitness,createForestWalker} from '../src/campaigns/b/witness.js';
import {createForestStory,FOREST_STORY_CONTENT as C} from '../src/campaigns/b/story/index.js';
import {FOREST_MONSTER_IDENTITIES} from '../src/campaigns/b/story/monster-identity.js';
function fixture(id,revision){const r=createForestCampaign(),w=buildForestWitness({runtime:r,stopBefore:id==='b06.sideTender'?'b06.sawPuppet':id});const walk=createForestWalker(r,w.state);walk.approach(id);const state=walk.state,story=createForestStory(r,{monsterStoryRevision:revision}),seen=story.location(state).seenIds,storage=memory();createSaveRepository(storage,r).save('auto',state,{storyVersion:C.id,openingRevision:'opening-r1',monsterStoryRevision:revision,seenIds:seen,queue:[],turnIndex:0,paused:false});return storage;}
test('actual app map title, aria and action rows show all four species only in new sessions',async()=>{
 for(const [id,row]of Object.entries(FOREST_MONSTER_IDENTITIES))for(const revision of ['mechanical-r1','forest-species-r1']){const e=await boot(fixture(id,revision));try{const name=revision==='forest-species-r1'?row.name:row.legacy,tiles=e.get('board').children.filter(t=>t.title?.includes(name));assert.ok(tiles.length,id+' map title');assert.ok(tiles.some(t=>t['aria-label'].includes(name)));const action=e.get('actions').children.find(x=>x.dataset.entityId===id);assert.equal(action.children[0].textContent,name);const enabled=revision==='forest-species-r1';assert.equal(tiles.some(t=>t.children.some(n=>n.dataset?.entityArt)),enabled);assert.equal(action.children[0].children.some(n=>n.dataset?.entityArt),enabled);if(enabled){const image=action.children[0].children.find(n=>n.dataset?.entityArt);image.naturalWidth=1254;image.naturalHeight=1254;image.onload();assert.equal(image.hidden,false);assert.ok(!image.src.includes('anthro'));}}finally{e.restore();}}
});
test('actual app moth GAL choice, cancel and confirm share one state settlement and species log',async()=>{
 const e=await boot(fixture('b06.sideTender','forest-species-r1'));try{const {get,qa}=e,before=qa.getState();const row=get('actions').children.find(x=>x.dataset.entityId==='b06.sideTender');row.children.at(-1).children.at(-1).onclick();assert.equal(get('story-title').textContent,'石坎上的牵丝');get('story-next').onclick();get('story-next').onclick();assert.ok(get('story-portrait').src.endsWith('BBOSS-001_anthro-avatar_v3-style.png'));const oldFace=get('story-portrait').onload;get('story-next').onclick();oldFace();assert.equal(get('story-portrait').hidden,true);assert.equal(get('story-portrait').src,undefined);get('story-skip').onclick();const choice=get('story-choices').children[0].children[0];choice.onclick();assert.equal(get('confirm-title').textContent,'缚杉冠蛾');assert.ok(get('confirm-copy').children.some(n=>n.dataset?.entityArt==='BBOSS-001'));assert.ok(get('confirm-copy').children.every(n=>!n.src?.includes('anthro')));get('confirm-cancel').onclick();assert.deepEqual(qa.getState(),before);get('story-choices').children[0].children[0].onclick();const confirm=get('confirm-yes').onclick;confirm();assert.equal(get('story-title').textContent,'借一块歇脚的石头');const after=qa.getState();assert.ok(after.cleared.includes('b06.sideTender'));assert.equal(after.stats.gold,before.stats.gold+5);assert.ok(get('log').children.some(n=>n.textContent.startsWith('击退缚杉冠蛾')));confirm();assert.deepEqual(qa.getState(),after);}finally{e.restore();}
});
