import test from 'node:test';import assert from 'node:assert/strict';
import {createForestCampaign} from '../src/campaigns/b/content.js';
import {createSaveRepository} from '../src/core/campaign.js';
import {createForestPreviewSession} from '../src/campaigns/b/preview-session.js';
import {createFineForestSaveExtension} from '../src/rendering/forest-fine-save.js';
import {createFineForestAppAdapter} from '../src/rendering/forest-fine-app.js';
import {FINE_FOREST,buildFineForestGeometry,createFineForestNavigation,fineColliderAt,fineSweptCollider,fineGroundSample,fineForestPose,validateFineForestPose} from '../src/rendering/forest-fine-navigation.js';
import {NATIVE_FOREST_WORLD as native} from '../src/rendering/forest-world-contract.js';
import {nativeGroundSupportAt} from '../src/rendering/forest-ground-support.js';
import {fineControlPolygon,nearestFineControl} from '../src/rendering/forest-fine-controls.js';
import {nativeToScreen} from '../src/rendering/forest-world-native.js';
import {createWorldMotion,worldPoint} from '../src/rendering/forest-world.js';
const r=createForestCampaign(),ids=['B-01','B-02','B-03'],graphs=new Map(ids.map(id=>[id,buildFineForestGeometry(r,id)]));
const memory=()=>{const entries=new Map();return{entries,getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v),removeItem:k=>entries.delete(k)};};
function initial(regionId){const s=r.initialState();s.location={regionId,...r.region(regionId).arrival};s.visited=[...new Set([...s.visited,regionId])];s.flags['b01.basicEntrance']=true;s.cleared.push('b01.timberPuppet');r.assertValidState(s);return s;}
function setup(regionId,{storage=memory(),state=initial(regionId),blocked=()=>false}={}){if(!storage.entries.size)createSaveRepository(storage,r).save('auto',state);const ext=createFineForestSaveExtension(r),session=createForestPreviewSession(r,storage,{extension:ext}),results=[],confirmations=[],fine=createFineForestAppAdapter(r,session,ext,{blocked,onResult:q=>results.push(q),onConfirmation:q=>confirmations.push(q)});session.pause();fine.sync(true);return{storage,ext,session,fine,results,confirmations};}
function settle(fine){for(let i=0;i<5000;i++){const s=fine.snapshot();if(!s.moving&&!s.held&&!s.queuedMicrosteps)return s;fine.tick(1/60);}throw Error('fine world route timeout');}

test('FW01 finite region lattices preserve all 173 old centres and all 498 directed source edges',()=>{const totals={nodes:0,centres:0,edges:0};for(const [i,id]of ids.entries()){const g=graphs.get(id),nodes=[...g.nodes.values()],expected=new Set(native.edges.filter(e=>e.sourceRegionId===id).flatMap(e=>[e.from+'>'+e.to,e.to+'>'+e.from])),actual=new Set(),seen=new Set([nodes[0].id]),queue=[nodes[0].id];for(let k=0;k<queue.length;k++)for(const e of g.nodes.get(queue[k]).neighbors)if(!seen.has(e.id)){seen.add(e.id);queue.push(e.id);}assert.equal(seen.size,g.nodes.size);assert.equal(g.nodes.size,[481,1019,820][i]);for(const c of native.cells.filter(c=>c.sourceRegionId===id&&c.walkable)){const n=g.nodes.get(`${(c.localX+.5)*4},${(c.localY+.5)*4}`);assert(n);assert(Math.hypot(...n.sample.worldFootM.map((v,j)=>v-c.worldFootM[j]))<2e-6);totals.centres++;}for(const n of nodes)for(const e of n.neighbors){const m=g.nodes.get(e.id);assert.equal(Math.abs(n.ix-m.ix)+Math.abs(n.iy-m.iy),1);assert.equal(m.source.regionId,id);if(e.logicalMove)actual.add(`${n.source.x},${n.source.y}>${m.source.x},${m.source.y}`);}assert.deepEqual([...actual].sort(),[...expected].sort());totals.nodes+=g.nodes.size;totals.edges+=actual.size;}assert.deepEqual(totals,{nodes:2320,centres:173,edges:498});assert.equal(r.spec.regions.length,30);assert.equal(native.joins.length,2);});

test('FW02 every complete fine edge has analytic swept body clearance and dense native ground support',()=>{for(const[id,g]of graphs)for(const n of g.nodes.values()){assert.equal(fineColliderAt(n.sample),null);for(const e of n.neighbors){const m=g.nodes.get(e.id);if(n.id>m.id)continue;assert.equal(fineSweptCollider(n.sample,m.sample),null,`${id}:${n.id}>${m.id}`);assert(e.distanceM>.05&&e.distanceM<.5);const steps=Math.ceil(e.distanceM/.025);for(let j=0;j<=steps;j++){const t=j/steps,s=nativeGroundSupportAt(n.sample,(m.sample.worldFootM[0]-n.sample.worldFootM[0])*t,(m.sample.worldFootM[1]-n.sample.worldFootM[1])*t);assert(s);assert.equal(fineColliderAt(s),null);for(let k=0;k<16;k++){const a=k*Math.PI/8,ring=nativeGroundSupportAt(s,Math.cos(a)*.18,Math.sin(a)*.18);assert(ring,`${id}:${n.id}>${m.id}:support ring`);assert(Math.abs(ring.worldFootM[2]-s.worldFootM[2])<=FINE_FOREST.maxStepM);}}}}});

test('FW03 native furniture/roots trim real nodes and no wall, diagonal or other-region control is invented',()=>{assert(graphs.get('B-02').rejected.some(x=>x.reason==='B02_winter_material_table'));assert(graphs.get('B-02').rejected.some(x=>x.reason.startsWith('B02_table_leg')));assert(graphs.get('B-03').rejected.some(x=>x.reason.startsWith('B03_old_root_block')));for(const[id,g]of graphs)for(const n of g.nodes.values())assert.equal(r.region(id).map[n.source.y][n.source.x],'.');assert.equal(fineGroundSample(1.5,5.5,'B-04'),null);assert.throws(()=>buildFineForestGeometry(r,'B-04'),/Unsupported/);const same=ids.map(id=>graphs.get(id).nodes.get('6,22')),view={width:700,height:500,scale:1},camera={x:0,y:0};const polygons=same.map(n=>fineControlPolygon(n,camera,view));for(let i=0;i<same.length;i++){assert(polygons[i].every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));const p=nativeToScreen(same[i].sample.footPx,camera,view);assert.equal(nearestFineControl(graphs.get(ids[i]),p.x,p.y,camera,view),'6,22');if(i)assert(Math.abs(polygons[i][0].x-polygons[i-1][0].x)>900);}});

test('FW04 B02 and B03 taps use 0.3m physical steps/1.2mps and exact logical receipt replay',()=>{for(const id of ids.slice(1)){const s=initial(id),nav=createFineForestNavigation(r,{state:s});const before=r.serialize(s);nav.press('right');nav.tick(.03);nav.release();assert(Math.abs(nav.snapshot().distanceM-.036)<1e-9);const after=settle(nav);assert.equal(after.nodeId,'7,22');assert(after.distanceM>.25&&after.distanceM<.35);assert.equal(r.serialize(after.state),before);assert.equal(after.facing,'right');nav.press('right');for(let i=0;i<45;i++)nav.tick(1/60);nav.release();settle(nav);nav.step('left');settle(nav);assert.equal(nav.snapshot().facing,'left');let replay=s;for(const a of nav.snapshot().actions){const q=r.dispatch(replay,a);assert(q.ok);replay=q.state;}assert.deepEqual(nav.snapshot().state,replay);assert.equal(nav.snapshot().actions.length,replay.revision-s.revision);}});

test('FW05 shared multi-cell winter plan, heat box and route brief settle once without extra confirmations or resources',()=>{for(const[id,entity]of[['B-02','b02.winterPlan'],['B-03','b03.heatBox'],['B-03','b03.routeBrief']]){const state=initial(id);if(entity.endsWith('routeBrief')){state.flags['b03.heatBoxOwned']=true;state.cleared.push('b03.heatBox');state.resources.heat=8;}const x=setup(id,{state}),shape=x.fine.snapshot().footprints.find(f=>f.entityId===entity);assert(shape.cells.length>1);assert(x.fine.entity(entity).ok);settle(x.fine);assert(x.session.state.cleared.includes(entity));assert.equal(x.confirmations.length,0);assert.equal(x.results.filter(q=>q.receipt?.action.entityId===entity).length,1);const before=structuredClone(x.session.state);for(let i=0;i<30;i++)assert.equal(x.fine.entity(entity).ok,false);assert.deepEqual(x.session.state,before);assert.equal(x.session.state.resources.heat,entity==='b03.heatBox'||entity==='b03.routeBrief'?8:0);assert.equal(x.session.state.resources.wedges,state.resources.wedges);assert(!x.fine.snapshot().footprints.some(f=>f.entityId===entity));}});

test('FW06 all old region-centre saves and old B01 offset poses restore, future and cross-region sidecars fail closed',()=>{for(const id of ids){const x=setup(id);assert.equal(x.fine.snapshot().nodeId,'6,22');assert(x.fine.step('right').ok);settle(x.fine);assert(x.session.save());const raw=x.storage.getItem(x.session.repo.key('manual')),saved=JSON.parse(raw);if(id==='B-01'){assert.equal(saved.presentation.finePose.collisionRevision,'forest-native-collision-hulls/v1:43820134c4c4a72ebd0585817dea3e7e7d14d50e3c03abcf3e78b310dfd0ac37');assert.equal(saved.presentation.finePose.collisionContentHash,'c87827c8a5f3ed6ce59ce8aa2d8c7ef968264eec3903c0a9e42d3f80432804a9');}for(let i=0;i<3;i++){const fresh=setup(id,{storage:x.storage});assert.equal(fresh.fine.snapshot().nodeId,'7,22');assert.deepEqual(fresh.session.state,x.session.state);fresh.fine.dispose();}const pose=saved.presentation.finePose;assert(validateFineForestPose(r,x.session.state,pose).ok);for(const[k,v]of[['schema','future'],['meshRevision','future'],['collisionRevision','future'],['collisionContentHash','wrong'],['regionId',id==='B-01'?'B-02':'B-01']]){const bad=structuredClone(saved);bad.presentation.finePose[k]=v;x.storage.setItem(x.session.repo.key('manual'),JSON.stringify(bad));const auto=x.storage.getItem(x.session.repo.key('auto')),state=structuredClone(x.session.state),physical=x.fine.snapshot().physical;assert.equal(x.session.load('manual').ok,false);assert.deepEqual(x.session.state,state);assert.deepEqual(x.fine.snapshot().physical,physical);assert.equal(x.storage.getItem(x.session.repo.key('auto')),auto);assert.equal(x.storage.getItem(x.session.repo.key('manual')),JSON.stringify(bad));}x.storage.setItem(x.session.repo.key('manual'),raw);assert(x.session.load('manual').ok);assert.equal(x.fine.snapshot().nodeId,'7,22');}const external=initial('B-04');assert.equal(validateFineForestPose(r,external,fineForestPose(r,external)).ok,false);});

test('FW07 logical traverse and smooth presentation bridge retain exact world registration in both directions',()=>{for(const[from,to,direction,x]of[['B-01','B-02','right',9],['B-02','B-01','left',1],['B-02','B-03','right',9],['B-03','B-02','left',1]]){const state=initial(from);state.location.x=x;const h=setup(from,{state}),motion=createWorldMotion(r);h.fine.click(`${x*4+3},22`);settle(h.fine);motion.adoptFine(h.session.state.location,h.fine.snapshot());assert.equal(motion.snapshot().hero.x,worldPoint(state.location).x+.25);assert(h.fine.step(direction).ok);settle(h.fine);assert.equal(h.session.state.location.regionId,to);assert.equal(h.results.filter(q=>q.events?.some(e=>e.type==='traverse')).length,1);assert.equal(h.fine.step(direction).ok,false,'old fine owner cannot move in target region before sync');assert.equal(h.fine.click('7,22').ok,false);h.fine.sync(false);motion.adoptFine(state.location,{...h.fine.snapshot(),fine:{x:x+.5,y:5.5}});motion.sync(h.session.state.location);assert(motion.snapshot().crossing);assert.equal(motion.snapshot().queuedSegments,1);const before=motion.snapshot();motion.tick(0);assert.deepEqual(motion.snapshot().hero,before.hero);for(let i=0;i<300;i++)motion.tick(1/60);assert.equal(motion.snapshot().moving,false);assert.deepEqual(motion.snapshot().hero,worldPoint(h.session.state.location));h.fine.sync(true);assert.equal(h.fine.geometry.regionId,to);assert.equal(h.fine.snapshot().state.location.regionId,to);assert.equal(h.fine.snapshot().nodeId,to==='B-01'||from==='B-03'?'38,22':'6,22');assert(h.session.save());const restored=setup(to,{storage:h.storage});assert.deepEqual(restored.session.state,h.session.state);assert.equal(restored.fine.geometry.regionId,to);}});
