import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {FOREST_GAL_FINAL_BACKGROUND_CONTRACT as rows,forestGalFinalBackgroundRow as match} from '../src/rendering/forest-gal-final-background-contract.js';
import {FOREST_GAL_FINAL_ENVIRONMENTS as assets} from '../src/rendering/forest-gal-assets.js';
import {forestGalPresentation,forestGalActors,presentForestGal,clearForestGal} from '../src/rendering/forest-gal-stage.js';
import {createForestCampaign} from '../src/campaigns/b/content.js';import {createForestStory} from '../src/campaigns/b/story/index.js';import {buildForestWitness,createForestWalker} from '../src/campaigns/b/witness.js';
const witnesses=JSON.parse(fs.readFileSync(new URL('./fixtures/b-final-background-witnesses.json',import.meta.url))),sha=b=>createHash('sha256').update(b).digest('hex');
test('121 reviewed direct rows retain exact historical facts, full stage, text, and queue bytes',()=>{const hit=new Set();assert.equal(rows.filter(r=>!r.monsterStoryRevision).length,145);assert.equal(new Set(rows.filter(r=>!r.monsterStoryRevision).map(r=>r.turnId+'|'+r.textSha256)).size,121);for(const w of witnesses){const scene={sceneId:w.sceneId},t=w.turn,before=JSON.stringify(t),row=match(scene,t);assert.ok(row,t.id);hit.add(row);assert.equal(forestGalPresentation(scene,t).asset.id,w.assetId);assert.equal(match(scene,JSON.parse(before)),row);assert.equal(JSON.stringify(t),before);for(const mutate of [t=>delete t.storySnapshot,t=>t.storySnapshot.origin='review',t=>t.storySnapshot.sourceHash='0'.repeat(64),t=>t.storySnapshot.resolvedTextSha256='0'.repeat(64),t=>t.storySnapshot.authoredTextSha256='0'.repeat(64),t=>t.storySnapshot.monsterStoryRevision='unknown',t=>t.storySnapshot.routes=null,t=>t.storySnapshot.warm=null,t=>t.text+='x',...['id','sourceLine','branch','phase','speaker','portrait','kind'].map(k=>t=>t[k]='wrong'),...['locationId','camera','backdropAssetId','portraitAllowed','winterClothing','actors','offscreen'].map(k=>t=>t.stage[k]='wrong')]){const c=structuredClone(t);mutate(c);assert.equal(match({...scene,state:{flags:{}}},c),null,t.id);}assert.equal(match({sceneId:'wrong'},t),null);}assert.equal(hit.size,145);});
test('16 new runtime assets are native PNGs with exact source bytes and dimensions',()=>{assert.equal(Object.keys(assets).length,16);for(const a of Object.values(assets)){const b=fs.readFileSync(new URL('../public/'+a.file,import.meta.url));assert.equal(sha(b),a.sha256);assert.equal(a.sourceSha256,a.sha256);assert.equal(b.length,a.bytes);assert.equal(b.subarray(1,4).toString(),'PNG');assert.equal(b.readUInt32BE(16),a.width);assert.equal(b.readUInt32BE(20),a.height);}});
function receipt(){const r=createForestCampaign(),f=createForestStory(r,{monsterStoryRevision:'forest-species-r1'}),w=buildForestWitness({runtime:r,stopBefore:'b06.sawPuppet'}),walk=createForestWalker(r,w.state);walk.approach('b06.sideTender');const before=walk.state,scene=f.resolve('b06_moth_before',before);const result=r.dispatch(before,{type:'interact',entityId:'b06.sideTender'});assert.ok(result.ok);const queue=f.fromDispatch({stateBefore:before,stateAfter:result.state,events:result.events,receipt:result.receipt,seenIds:[]});const after=queue.scenes.find(s=>s.sceneId==='b06_moth_after');assert.ok(after);return {r,f,before,scene,result,after};}
test('moth runtime real receipt gives eight before and five separately reviewed after backgrounds',()=>{const {r,f,before,scene,result,after}=receipt();assert.equal(scene.turns.length,8);assert.equal(after.turns.length,5);assert.ok(result.state.cleared.includes('b06.sideTender'));assert.throws(()=>f.resolve('b06_moth_after',result.state));for(const s of [scene,after])for(const t of s.turns){const expected=s===scene;assert.equal(Boolean(match(s,t)),expected);assert.equal(forestGalPresentation(s,t).asset?.id??null,'B_FINAL_BENV_006M');assert.deepEqual(forestGalActors(t,forestGalPresentation(s,t)),[]);if(!expected)continue;for(const mutate of [t=>delete t.storySnapshot,t=>t.monsterStoryRevision='mechanical-r1',t=>t.monsterStoryRevision='unknown',t=>t.storySnapshot.monsterStoryRevision='mechanical-r1',t=>t.storySnapshot.constructionHash='0'.repeat(64),t=>t.storySnapshot.origin='review',t=>t.stage.monsterForm='beast',t=>t.monsterForm='beast',t=>t.text+='x',t=>t.stage.actors={hero:{}},t=>t.stage.portraitAllowed=true]){const c=structuredClone(t);mutate(c);assert.equal(match(s,c),null);}assert.equal(match({...s,monsterStoryRevision:'mechanical-r1'},t),null);assert.equal(match({...s,sceneId:'b06_enter'},t),null);}assert.equal(createForestStory(r).revision??null,null);});
function node(){return{dataset:{},children:[],style:{},replaceChildren(...c){this.children=c;},removeAttribute(k){delete this[k];}};}
test('moth reviewed background survives receipt then clears on exit, failure and stale callbacks',()=>{const {scene,after}=receipt(),ui={backdrop:node(),actors:node(),portrait:node(),label:node(),stage:node(),dialog:node()};presentForestGal(ui,scene,scene.turns[0]);const oldLoad=ui.backdrop.onload;ui.backdrop.naturalWidth=1672;ui.backdrop.naturalHeight=941;oldLoad();assert.equal(ui.backdrop.hidden,false);presentForestGal(ui,after,after.turns[0]);assert.ok(ui.backdrop.src.endsWith('BENV-006M_moth-side-ledge_pre-neutral_v1.png'));oldLoad();assert.equal(ui.backdrop.hidden,false);clearForestGal(ui);oldLoad();assert.equal(ui.backdrop.hidden,true);presentForestGal(ui,scene,scene.turns[0]);const late=ui.backdrop.onload;ui.backdrop.onerror();late();assert.equal(ui.backdrop.hidden,true);assert.equal(ui.backdrop.src,undefined);clearForestGal(ui);late();assert.equal(ui.backdrop.hidden,true);assert.equal(ui.stage.dataset.artStatus,'inactive');});
