// Actual app import with deterministic DOM/canvas/RAF helpers. No real browser.
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{createForestCampaign}from'../src/campaigns/b/content.js';
import{createSaveRepository}from'../src/core/campaign.js';
import{createForestPreviewSession}from'../src/campaigns/b/preview-session.js';
import{createFineForestSaveExtension}from'../src/rendering/forest-fine-save.js';
import{nativeWorldCell}from'../src/rendering/forest-world-native.js';
const html=readFileSync(new URL('../public/campaigns-b/index.html',import.meta.url),'utf8');
const context=()=>new Proxy({measureText:t=>({width:t.length*7}),createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}}),getImageData:(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4),width:w,height:h})},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.events={};this.style={};this.open=false;this.hidden=false;this.disabled=false;this.classList={add(){}};if(tag==='canvas')this.getContext=()=>this.context??=context();}append(...c){this.children.push(...c);}replaceChildren(...c){this.children=c;}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}addEventListener(k,v){this.events[k]=v;}showModal(){this.open=true;}close(){this.open=false;}getBoundingClientRect(){return{width:700,height:500,left:0,top:0};}}
function memory(){const entries=new Map();return{entries,getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v),removeItem:k=>entries.delete(k)};}
async function boot(storage=memory()){
 const nodes=new Map([...html.matchAll(/<([a-z-]+)[^>]*\bid="([^"]+)"[^>]*>/g)].map(([,tag,id])=>[id,new Element(tag)])),dirs=['up','down','left','right'].map(dir=>{const b=new Element('button');b.dataset.dir=dir;return b;}),events={},windowEvents={},frames=new Map(),images=[];let clock=0,id=0;
 const document={hidden:false,getElementById:id=>nodes.get(id),createElement:t=>new Element(t),createTextNode:t=>({textContent:t}),querySelector:s=>s==='dialog[open]'?[...nodes.values()].find(n=>n.tagName==='DIALOG'&&n.open)??null:null,querySelectorAll:s=>s==='[data-dir]'?dirs:s==='[data-close]'?[]:[],addEventListener:(k,fn)=>events[k]=fn};
 class Image{set src(s){this.url=s;this.naturalWidth=s.includes('hero-four-views')?1774:s.includes('world-')?4096:1024;this.naturalHeight=s.includes('hero-four-views')?887:s.includes('world-')?1792:1536;images.push(this);}get src(){return this.url;}}
 const saved={};for(const k of['window','document','confirm','requestAnimationFrame','cancelAnimationFrame','Image','setTimeout','clearTimeout'])saved[k]=globalThis[k];Object.assign(globalThis,{window:{localStorage:storage,addEventListener:(k,fn)=>windowEvents[k]=fn},document,confirm:()=>true,Image,requestAnimationFrame:fn=>{frames.set(++id,fn);return id;},cancelAnimationFrame:i=>frames.delete(i),setTimeout:()=>0,clearTimeout:()=>{}});
 let code=readFileSync(new URL('../public/campaigns-b/app.js',import.meta.url),'utf8').replaceAll("from '../src/",`from '${new URL('../src/',import.meta.url).href}`);code+=`\n// unique harness ${Math.random()}\n//# sourceURL=fine-entry-harness.js`;await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);for(const image of images.splice(0))image.onload?.();
 const qa=window.__FOREST_PREVIEW__,get=k=>nodes.get(k),tick=(n=25,dt=100)=>{for(let i=0;i<n;i++){clock+=dt;const callbacks=[...frames.values()];frames.clear();for(const fn of callbacks)fn(clock);assert.ok(frames.size<=1,`fine entry must retain one animation driver, found ${frames.size}`);}},down=(key,code,extra={})=>events.keydown({key,code,target:{tagName:'BODY'},repeat:false,preventDefault(){},...extra}),up=(key,code)=>events.keyup({key,code}),tap=(key,code)=>{down(key,code);up(key,code);},click=id=>get('board').children.find(n=>n.dataset.fineNode===id).onclick();
 return{qa,get,tick,down,up,tap,click,storage,events,windowEvents,document,restore:()=>Object.assign(globalThis,saved)};
}

test('A01/A02/A07 actual native-loaded entry supports fine tap, click, held keys and all interruption guards',async()=>{const e=await boot();try{const{qa,get,tick,tap,down,up,click}=e;assert.equal(qa.getVisualState().fine.active,true);assert.equal(get('board').children.length,481);assert.equal(qa.getVisualState().readable,false);assert.equal(qa.getVisualState().world.heroGaitStatus,'visual-hold');assert.ok(get('board').children.find(n=>n.dataset.fineNode==='7,22').style.clipPath.startsWith('polygon('));get('story-pause').onclick();const state=qa.getState();tap('D','KeyD');tick(8);assert.equal(qa.getVisualState().fine.nodeId,'7,22');assert.deepEqual(qa.getState(),state);
 click('7,23');tick(8);assert.equal(qa.getVisualState().fine.nodeId,'7,23');down('W','KeyW',{shiftKey:true});up('w','KeyW');tick(8);assert.equal(qa.getVisualState().fine.nodeId,'7,22');down('s','KeyS');down('d','KeyD');up('d','KeyD');up('s','KeyS');tick(8);assert.equal(qa.getVisualState().fine.held,null);assert.equal(qa.getVisualState().heldMovement.length,0);
 down('d','KeyD');tick(1,20);e.windowEvents.blur();const paused=qa.getVisualState().fine.physical;tick(8);assert.deepEqual(qa.getVisualState().fine.physical,paused);e.windowEvents.focus();down('d','KeyD',{repeat:true});tick(8);assert.equal(qa.getVisualState().fine.held,null);up('d','KeyD');
 down('a','KeyA');tick(1,20);e.document.hidden=true;e.events.visibilitychange();const hidden=qa.getVisualState().fine.physical;tick(8);assert.deepEqual(qa.getVisualState().fine.physical,hidden);e.document.hidden=false;tick(8);assert.equal(qa.getVisualState().fine.moving,false);
 get('help').onclick();assert.equal(get('settings').open,true);const stopped=qa.getVisualState().fine.physical;down('s','KeyS');tick(8);assert.deepEqual(qa.getVisualState().fine.physical,stopped);get('settings').close();down('s','KeyS',{repeat:true});tick(4);assert.equal(qa.getVisualState().fine.held,null);up('s','KeyS');
 down('a','KeyA');tick(40);assert.equal(qa.getVisualState().fine.moving,false);get('help').onclick();assert.equal(get('settings').open,true);assert.equal(qa.getVisualState().fine.held,null,'opening settings clears an idle blocked held direction without relying on focus');assert.equal(qa.getVisualState().heldMovement.length,0);get('settings').close();up('a','KeyA');down('d','KeyD');tick(1,20);assert.equal(qa.getVisualState().fine.moving,true);get('resume-story').onclick();assert.equal(get('story').open,true,'mid-microstep story must open without waiting for a paused segment');const storyPose=qa.getVisualState().fine.physical;tick(8);assert.deepEqual(qa.getVisualState().fine.physical,storyPose);get('story-pause').onclick();up('d','KeyD');tick(8);assert.equal(qa.getVisualState().fine.moving,false);e.windowEvents.resize();e.windowEvents.pagehide();tick(5);assert.equal(qa.getVisualState().fine.held,null);e.windowEvents.focus();const same=qa.getState();get('map-world-mode').onclick();assert.equal(qa.getVisualState().fine.active,false);get('map-world-mode').onclick();assert.equal(qa.getVisualState().fine.active,true);assert.deepEqual(qa.getState(),same);
 }finally{e.restore();}});

test('A04/A05/A06/A08/A09 actual entry settles whole entity once and invalidates stale confirmation on failed load',async()=>{const e=await boot();try{const{qa,get,tick,click}=e;get('story-pause').onclick();click('16,20');tick(60);assert.equal(get('confirmation').open,true);const stale=get('confirm-yes').onclick,before=qa.getState();get('confirm-cancel').onclick();click('16,20');tick(10);const fresh=get('confirm-yes').onclick;stale();assert.deepEqual(qa.getState(),before);assert.equal(get('confirmation').open,true,'stale callback must not dismiss the newer dialog');fresh();const won=qa.getState();assert.equal(won.stats.hp,before.stats.hp-12);assert.equal(won.stats.gold,before.stats.gold+3);fresh();assert.deepEqual(qa.getState(),won);assert.ok(!qa.getVisualState().fine.footprints.some(f=>f.entityId==='b01.timberPuppet'));get('story-pause').onclick();const pickup=qa.getVisualState().fine.footprints.find(f=>f.entityId==='b01.guardPlate');click(pickup.cells[0]);tick(60);assert.equal(qa.getState().stats.def,before.stats.def+2);assert.equal(get('confirmation').open,false);get('save').onclick();const saved=qa.getState(),pose=qa.getVisualState().fine.nodeId;get('load-manual').onclick();assert.deepEqual(qa.getState(),saved);assert.equal(qa.getVisualState().fine.nodeId,pose);assert.ok(!qa.getVisualState().fine.footprints.some(f=>f.entityId==='b01.guardPlate'));
 }finally{e.restore();}});

test('A11 actual entry preserves single visual owner and continuous camera at both portal boundaries',async()=>{const runtime=createForestCampaign(),storage=memory(),repo=createSaveRepository(storage,runtime);let s=runtime.initialState();for(let i=0;i<2;i++)s=runtime.dispatch(s,{type:'move',direction:'right'}).state;s=runtime.dispatch(s,{type:'interact',entityId:'b01.timberPuppet'}).state;while(s.location.x<9)s=runtime.dispatch(s,{type:'move',direction:'right'}).state;repo.save('auto',s);const pre=createForestPreviewSession(runtime,storage,{extension:createFineForestSaveExtension(runtime)});pre.pause();pre.save();const e=await boot(storage);try{const{qa,tick,tap,click,get}=e;get('story-pause').onclick();click('39,22');tick(8);const before=qa.getVisualState();assert.equal(before.world.visualOwner,'fine-b01');tap('ArrowRight','ArrowRight');assert.equal(qa.getState().location.regionId,'B-01');let old=qa.getVisualState(),switched=false;for(let i=0;i<100;i++){tick(1,50);const now=qa.getVisualState();if(old.world.visualOwner==='fine-b01'&&now.world.visualOwner==='coarse'){switched=true;assert.ok(Math.hypot(now.world.nativeCamera.x-old.world.nativeCamera.x,now.world.nativeCamera.y-old.world.nativeCamera.y)<8);assert.equal(now.fine.active,false);assert.ok(now.world.queuedSegments<=1);}old=now;if(qa.getState().location.regionId==='B-02'&&!now.world.moving)break;}assert.ok(switched);assert.equal(qa.getState().location.regionId,'B-02');tap('ArrowLeft','ArrowLeft');assert.equal(qa.getState().location.regionId,'B-01');assert.equal(qa.getVisualState().fine.active,false);assert.equal(qa.getVisualState().world.visualOwner,'coarse');const committed=qa.getState(),bridgeHero=qa.getVisualState().world.hero;e.document.hidden=true;e.events.visibilitychange();tick(10,100);assert.deepEqual(qa.getVisualState().world.hero,bridgeHero,'hidden tab must retain the exact visible bridge position');assert.equal(qa.getVisualState().fine.active,false);e.document.hidden=false;tap('ArrowRight','ArrowRight');assert.deepEqual(qa.getState(),committed);tick(100,50);assert.equal(qa.getVisualState().fine.active,true);assert.equal(qa.getVisualState().fine.nodeId,'38,22');const native=nativeWorldCell('B-01',9,5);assert.ok(Math.hypot(...qa.getVisualState().fine.physical.worldFootM.map((v,i)=>v-native.worldFootM[i]))<1e-6,'fine mesh and stored native centre agree within 1 micrometre');assert.ok(!qa.getVisualState().world.moving);assert.equal(qa.getState().stats.gold,s.stats.gold);
 }finally{e.restore();}});


test('B04 and B27 keep original fallback navigation with no fine owner',async()=>{const runtime=createForestCampaign();for(const regionId of ['B-04','B-27']){const storage=memory(),state=runtime.initialState();state.location={regionId,...runtime.region(regionId).arrival};state.visited.push(regionId);runtime.assertValidState(state);createSaveRepository(storage,runtime).save('auto',state);const e=await boot(storage);try{assert.equal(e.qa.getVisualState().fine.active,false);assert.notEqual(e.qa.getVisualState().renderer,'continuous-world');assert.deepEqual(e.qa.getState(),state);assert.equal(e.get('board').children.length,121);}finally{e.restore();}}});
