import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{createForestCampaign}from'../src/campaigns/b/content.js';import{createSaveRepository}from'../src/core/campaign.js';import{createForestPreviewSession}from'../src/campaigns/b/preview-session.js';import{createFineForestSaveExtension}from'../src/rendering/forest-fine-save.js';import{createFineForestAppAdapter}from'../src/rendering/forest-fine-app.js';
const r=createForestCampaign(),memory=()=>{const data=new Map();return{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};};
function setup(state){const storage=memory();createSaveRepository(storage,r).save('auto',state);const extension=createFineForestSaveExtension(r),session=createForestPreviewSession(r,storage,{extension}),results=[],confirmations=[],fine=createFineForestAppAdapter(r,session,extension,{onResult:q=>results.push(q),onConfirmation:q=>confirmations.push(q)});session.pause();fine.sync(true);return{storage,session,fine,results,confirmations};}
function settle(f){for(let i=0;i<8000;i++){const q=f.snapshot();if(!q.moving&&!q.held&&!q.queuedMicrosteps)return q;f.tick(.1);}throw Error('late fine route timed out');}
function replay(filename,{skipBrief=false}={}){const c=JSON.parse(readFileSync(new URL(`../artifacts/campaigns/${filename}.certificate.json`,import.meta.url)));let state=r.initialState();const records=[];for(const step of c.steps){const action=step.action;if(skipBrief&&action.entityId==='b03.routeBrief')continue;const result=r.dispatch(state,action);assert(result.ok,`${action.entityId??action.edgeId??action.direction}: ${result.reason}`);records.push({state,action,result});state=result.state;}return records;}
const reference=replay('b-normal-partial-none');
const pick=id=>reference.find(q=>q.action.entityId===id).state;
const fields=['stats','resources','flags','cleared'];

test('FW12 late handrail/readiness interactions remain exact one-time authority actions from real route predecessors',()=>{for(const id of['b24.installHandrail','b26.readinessReview']){const state=pick(id),expected=r.dispatch(state,{type:'interact',entityId:id}),x=setup(state);assert(x.fine.entity(id).ok);settle(x.fine);assert.equal(x.results.filter(q=>q.receipt?.action.entityId===id).length,1);assert.equal(x.confirmations.length,0);for(const field of fields)assert.deepEqual(x.session.state[field],expected.state[field],id+':'+field);for(let i=0;i<5;i++)assert.equal(x.fine.entity(id).ok,false);assert(x.session.save());assert(x.session.load('manual').ok);assert(!x.fine.snapshot().footprints.some(f=>f.entityId===id));}});

test('FW13 all seven legal heat masks retain target entity and original irreversible confirmation/cost exactly once',()=>{const baseline=pick('b26.confirmHeat.0');for(let mask=0;mask<7;mask++){const state=structuredClone(baseline);let spent=0;for(const[i,[name,cost]]of[['greenhouse',2],['pear',1],['lodge',2]].entries()){state.flags[`b.warm.${name}`]=Boolean(mask&(1<<i));if(mask&(1<<i))spent+=cost;}state.resources.heat=4-spent;r.assertValidState(state);const id=`b26.confirmHeat.${mask}`,expected=r.dispatch(state,{type:'interact',entityId:id});assert(expected.ok);const x=setup(state);assert(x.fine.entity(id).ok);let q=settle(x.fine);assert.equal(q.pending.entityId,id);assert.equal(x.confirmations.length,1);assert.deepEqual(x.session.state.resources,state.resources);assert(!x.session.state.flags['b26.heatPlanFrozen']);const stale=q.pending.token;x.fine.cancel();assert.equal(x.fine.confirm(stale).ok,false);assert(x.fine.entity(id).ok);q=settle(x.fine);assert.notEqual(q.pending.token,stale);assert(x.fine.confirm(q.pending.token).ok);assert.equal(x.fine.confirm(q.pending.token).ok,false);for(const field of fields)assert.deepEqual(x.session.state[field],expected.state[field],id+':'+field);assert.equal(x.results.filter(a=>a.receipt?.action.entityId===id).length,1);assert(!x.fine.snapshot().footprints.some(f=>f.entityId.startsWith('b26.confirmHeat.')));}});

test('FW14 skipped early route briefing cannot hijack a later explicit same-cell heat choice, including deferred click',()=>{const records=replay('b-normal-partial-none',{skipBrief:true}),state=records.find(q=>q.action.entityId==='b26.confirmHeat.0').state;assert(!state.cleared.includes('b03.routeBrief'));for(const deferred of[false,true]){const x=setup(state),shapes=x.fine.snapshot().footprints;assert(shapes.find(f=>f.entityId==='b03.routeBrief').cells.some(id=>shapes.find(f=>f.entityId==='b26.confirmHeat.0').cells.includes(id)));if(deferred){const dir=x.fine.geometry.nodes.get(x.fine.snapshot().nodeId).neighbors.find(e=>!e.logicalMove).direction;assert(x.fine.step(dir).ok);x.fine.tick(.02);}assert(x.fine.entity('b26.confirmHeat.0').ok);const q=settle(x.fine);assert.equal(q.pending.entityId,'b26.confirmHeat.0');assert(!x.session.state.cleared.includes('b03.routeBrief'),'approach keeps the requested operation identity');assert.deepEqual(x.session.state.resources,state.resources);assert(x.fine.confirm(q.pending.token).ok);assert(x.session.state.flags['b26.heatPlanFrozen']);assert(!x.session.state.cleared.includes('b03.routeBrief'));}});

test('FW15 B03 co-located portals keep their own original gate and never implicitly perform handrail/readiness',()=>{for(const[entityId,edgeId]of[['b24.installHandrail','b.edge.03-25'],['b26.readinessReview','b.edge.03-26']]){const state=pick(entityId),x=setup(state),edge=r.spec.transitions.find(e=>e.id===edgeId),anchor=r.entity(edge.anchor),legal=r.preview(state,{type:'traverse',edgeId}).legal;const returnToSource=()=>{x.fine.sync(false);const back=x.session.request({type:'traverse',edgeId:edge.reciprocal});assert(back.ok);x.session.pause();x.fine.sync(true);assert.equal(x.fine.geometry.regionId,'B-03');assert.equal(x.fine.snapshot().nodeId,`${anchor.x*4+2},${anchor.y*4+2}`);};assert(x.fine.portalAction({type:'traverse',edgeId}).ok);settle(x.fine);assert.equal(x.session.state.location.regionId,legal?edge.to:'B-03');assert(!x.session.state.cleared.includes(entityId));assert.equal(x.results.filter(q=>q.receipt?.action.entityId===entityId).length,0);assert.deepEqual(x.session.state.resources,state.resources);if(legal)returnToSource();else assert.equal(x.fine.snapshot().nodeId,`${anchor.x*4+2},${anchor.y*4+2}`);assert(x.fine.entity(entityId).ok);settle(x.fine);assert(x.session.state.cleared.includes(entityId));assert.equal(x.results.filter(q=>q.receipt?.action.entityId===entityId).length,1);assert(x.fine.portalAction({type:'traverse',edgeId}).ok);settle(x.fine);assert.equal(x.session.state.location.regionId,edge.to);assert.equal(x.results.filter(q=>q.receipt?.action.type==='traverse').length,legal?2:1);assert.equal(x.session.presentation.finePose,undefined);returnToSource();assert.equal(x.results.filter(q=>q.receipt?.action.entityId===entityId).length,1);}});

test('FW16 actual certificate visits cover fine/non-fine portal save round-trips with exact origin poses',()=>{const seen=new Set();for(const record of reference){if(record.action.type!=='traverse')continue;const from=record.state.location.regionId,to=record.result.state.location.regionId;if(!['B-01','B-02','B-03'].includes(from)||['B-01','B-02','B-03'].includes(to)||seen.has(record.action.edgeId))continue;seen.add(record.action.edgeId);const x=setup(record.state);assert(x.fine.portalAction(record.action).ok);settle(x.fine);assert.equal(x.session.state.location.regionId,to);assert.equal(x.session.presentation.finePose,undefined);x.fine.sync(false);assert(x.session.save());assert(x.session.load('manual').ok);assert.equal(x.fine.active,false);const edge=r.spec.transitions.find(e=>e.id===record.action.edgeId),back=x.session.request({type:'traverse',edgeId:edge.reciprocal});assert(back.ok);x.session.pause();x.fine.sync(true);assert.equal(x.fine.geometry.regionId,from);assert(x.session.save());assert(x.session.load('manual').ok);assert.equal(x.fine.snapshot().state.location.regionId,from);assert.deepEqual(x.session.state.resources,record.state.resources);}assert(seen.has('b.edge.02-04'));assert(seen.has('b.edge.03-27'));});


test('FW17 cancelling the last ground-only portal half-step never revives a co-located operation',()=>{for(const[entityId,edgeId]of[['b24.installHandrail','b.edge.03-25'],['b26.readinessReview','b.edge.03-26']])for(const interruption of['blur','cancel','new-floor-click','new-key']){const state=structuredClone(pick(entityId)),entity=r.entity(entityId);state.location={regionId:'B-03',x:entity.x-1,y:entity.y};r.assertValidState(state);const x=setup(state);assert(x.fine.portalAction({type:'traverse',edgeId}).ok);let q;for(let i=0;i<3000;i++){x.fine.tick(.005);q=x.fine.snapshot();if(q.moving&&!q.queuedMicrosteps)break;}assert(q.moving&&!q.queuedMicrosteps);const before=structuredClone(x.session.state.resources);if(interruption==='cancel')x.fine.cancel();else if(interruption==='new-floor-click'){assert(x.fine.click(`${entity.x*4-1},${entity.y*4+2}`).ok);}else if(interruption==='new-key'){x.fine.press('left');x.fine.release();}else x.fine.interrupt();settle(x.fine);assert.equal(x.session.state.location.regionId,'B-03');assert(!x.session.state.cleared.includes(entityId),`${entityId}:${interruption}`);assert.equal(x.results.filter(a=>a.receipt?.action.entityId===entityId).length,0);assert.deepEqual(x.session.state.resources,before);assert.equal(x.fine.snapshot().pending,null);assert.equal(x.fine.snapshot().portal,null);}});

test('FW18 walking past an operation preserves coarse-map opt-in, while a beneficial pickup still auto-collects once',()=>{for(const entityId of['b02.winterPlan','b24.installHandrail','b26.readinessReview','b03.heatBox']){const state=structuredClone(pick(entityId)),e=r.entity(entityId);state.location={regionId:e.regionId,x:e.x-1,y:e.y};r.assertValidState(state);const x=setup(state);assert(x.fine.press('right').ok);for(let i=0;i<90;i++)x.fine.tick(1/60);x.fine.release();settle(x.fine);const pickup=entityId==='b03.heatBox';assert.equal(x.session.state.cleared.includes(entityId),pickup,entityId);assert.equal(x.results.filter(q=>q.receipt?.action.entityId===entityId).length,pickup?1:0);assert.equal(x.confirmations.length,0);if(!pickup)assert.deepEqual(x.session.state.resources,state.resources);else assert.equal(x.session.state.resources.heat,state.resources.heat+8);}});
