import test from 'node:test';
import assert from 'node:assert/strict';
import {createForestCampaign} from '../src/campaigns/b/content.js';
import {createSaveRepository} from '../src/core/campaign.js';
import {createForestPreviewSession} from '../src/campaigns/b/preview-session.js';
import {createFineForestSaveExtension} from '../src/rendering/forest-fine-save.js';
import {createFineForestAppAdapter} from '../src/rendering/forest-fine-app.js';
import {fineForestPose} from '../src/rendering/forest-fine-navigation.js';
const runtime=createForestCampaign(),memory=()=>{const entries=new Map(),writes=[];return{entries,writes,getItem:k=>entries.get(k)??null,setItem(k,v){entries.set(k,v);writes.push(k);},removeItem:k=>entries.delete(k)};};
function setup(storage=memory(),options={}){const extension=createFineForestSaveExtension(runtime),session=createForestPreviewSession(runtime,storage,{extension}),results=[],confirmations=[],fine=createFineForestAppAdapter(runtime,session,extension,{...options,onResult:r=>results.push(r),onConfirmation:r=>confirmations.push(r)});session.pause();fine.sync(true);return{storage,extension,session,fine,results,confirmations};}
function settle(fine,limit=5000){let i=0;while(i++<limit){fine.tick(.1);const s=fine.snapshot();if(!s.moving&&!s.queuedMicrosteps&&!s.held)return;}throw Error('not settled');}
function clearedState(){let s=runtime.initialState();for(let i=0;i<2;i++)s=runtime.dispatch(s,{type:'move',direction:'right'}).state;return runtime.dispatch(s,{type:'interact',entityId:'b01.timberPuppet'}).state;}

test('A01 session authority: short tap changes only a real physical microstep',()=>{const{fine,session,storage}=setup(),before=runtime.serialize(session.state),story=structuredClone(session.presentation),p=fine.snapshot().physical.worldFootM;fine.press('right');fine.release();settle(fine);assert.equal(runtime.serialize(session.state),before);assert.ok(Math.hypot(...fine.snapshot().physical.worldFootM.map((v,i)=>v-p[i]))>.29);assert.equal(fine.snapshot().nodeId,'7,22');const now=structuredClone(session.presentation);delete now.finePose;delete story.finePose;assert.deepEqual(now,story);assert.equal(JSON.parse(storage.getItem(session.repo.key('auto'))).presentation.finePose.nodeId,'7,22');});

test('A03/A05 session emits one receipt per logical move, one puppet settlement and immediate free pickup',()=>{const{fine,session,results,confirmations}=setup();fine.entity('b01.timberPuppet');settle(fine);assert.equal(confirmations.length,1);assert.equal(fine.snapshot().footprints.find(f=>f.entityId==='b01.timberPuppet').cells.length,13);const before=structuredClone(session.state),token=confirmations[0].token;assert.equal(fine.confirm(token).ok,true);assert.equal(fine.confirm(token).ok,false);assert.equal(session.state.stats.hp,before.stats.hp-12);assert.equal(session.state.stats.gold,before.stats.gold+3);assert.equal(session.state.flags['b01.basicEntrance'],true);assert.ok(!fine.snapshot().footprints.some(f=>f.entityId==='b01.timberPuppet'));session.pause();fine.entity('b01.guardPlate');settle(fine);assert.equal(session.state.stats.def,before.stats.def+2);assert.equal(confirmations.length,1,'free pickup must not show confirmation');const receipts=results.filter(r=>r.receipt);assert.equal(receipts.length,session.state.revision);let replay=runtime.initialState();for(const r of receipts){assert.equal(r.receipt.before,runtime.stateHash(replay));replay=runtime.dispatch(replay,r.receipt.action).state;assert.equal(r.receipt.after,runtime.stateHash(replay));}assert.deepEqual(replay,session.state);});

test('A06/A08 invalid load clears input and tokens, retains exact partial segment, bytes and campaign',()=>{const{fine,session,storage}=setup();fine.press('right');fine.tick(.03);const before=fine.snapshot(),state=runtime.serialize(session.state);storage.setItem(session.repo.key('manual'),'null');assert.equal(session.load('manual').ok,false);assert.equal(runtime.serialize(session.state),state);assert.deepEqual(fine.snapshot().physical,before.physical);assert.equal(fine.snapshot().moving,true);assert.equal(fine.snapshot().held,null);assert.equal(fine.snapshot().queuedMicrosteps,0);assert.equal(storage.getItem(session.repo.key('manual')),'null');settle(fine);assert.equal(fine.snapshot().nodeId,'7,22');fine.entity('b01.timberPuppet');settle(fine);const old=fine.snapshot().pending.token;assert.equal(session.load('missing').ok,false);fine.entity('b01.timberPuppet');settle(fine);assert.notEqual(fine.snapshot().pending.token,old);assert.equal(fine.confirm(old).ok,false);});

test('A08 save defers a microstep; settled pose restores exact campaign and story envelope',()=>{const{fine,session,storage}=setup();session.save();const initial=storage.getItem(session.repo.key('manual'));fine.press('right');fine.tick(.05);assert.equal(session.save(),false);assert.equal(storage.getItem(session.repo.key('manual')),initial);fine.release();settle(fine);assert.equal(session.save(),true);const before=runtime.serialize(session.state),pose=fine.snapshot().nodeId,presentation=structuredClone(session.presentation);fine.step('down');settle(fine);assert.equal(session.load('manual').ok,true);assert.equal(runtime.serialize(session.state),before);assert.equal(fine.snapshot().nodeId,pose);assert.deepEqual(session.presentation,presentation);});

test('A08 malformed, future, mismatched or occupied fine metadata rejects without overwriting either slot',()=>{for(const mutate of[p=>p.finePose=null,p=>p.finePose.schema='future',p=>p.finePose.stateHash='wrong',p=>p.finePose.presentationHash='wrong',p=>p.finePose.actorRadiusM=.24,p=>p.finePose.campaignIdentity={foreign:true},p=>p.openingRevision='future']){const{storage,session,fine}=setup();session.save();const raw=JSON.parse(storage.getItem(session.repo.key('manual')));mutate(raw.presentation);const bad=JSON.stringify(raw);storage.setItem(session.repo.key('manual'),bad);const auto=storage.getItem(session.repo.key('auto')),state=runtime.serialize(session.state),pose=fine.snapshot().nodeId;assert.equal(session.load('manual').ok,false);assert.equal(runtime.serialize(session.state),state);assert.equal(fine.snapshot().nodeId,pose);assert.equal(storage.getItem(session.repo.key('manual')),bad);assert.equal(storage.getItem(session.repo.key('auto')),auto);assert.equal(session.save(),false);}});

test('A08 legacy raw state and full story envelope restore at supported centres with no campaign rewrite',()=>{for(const envelope of[false,true]){const storage=memory(),repo=createSaveRepository(storage,runtime),s=clearedState();repo.save('auto',s,envelope?{storyVersion:'forest-road-v1.1',seenIds:[],queue:[],turnIndex:0,paused:true}:null);if(envelope){const raw=JSON.parse(storage.getItem(repo.key('auto')));raw.presentation.storyVersion=(setup().session.presentation.storyVersion);storage.setItem(repo.key('auto'),JSON.stringify(raw));}const{session,fine}=setup(storage);assert.deepEqual(session.state,s);assert.equal(fine.snapshot().nodeId,'14,22');}});

test('A09 both cleared entity footprints remain absent across save and recreate',()=>{const{fine,session,storage}=setup();fine.entity('b01.timberPuppet');settle(fine);fine.confirm(fine.snapshot().pending.token);session.pause();fine.entity('b01.guardPlate');settle(fine);session.save();const state=runtime.serialize(session.state),restored=setup(storage);assert.equal(runtime.serialize(restored.session.state),state);assert.ok(!restored.fine.snapshot().footprints.some(f=>['b01.timberPuppet','b01.guardPlate'].includes(f.entityId)));assert.equal(restored.fine.entity('b01.guardPlate').ok,false);});

test('A11 off-centre portal approaches exact centre before one original traverse; interruption cancels it',()=>{for(const offset of['37,22','39,22','38,21']){const storage=memory(),repo=createSaveRepository(storage,runtime);let state=clearedState();while(state.location.x<9)state=runtime.dispatch(state,{type:'move',direction:'right'}).state;repo.save('auto',state);const x=setup(storage);x.fine.click(offset);settle(x.fine);assert.equal(x.fine.snapshot().nodeId,offset);assert.equal(x.fine.step('right').ok,true);assert.equal(x.session.state.location.regionId,'B-01');settle(x.fine);assert.equal(x.session.state.location.regionId,'B-02');assert.equal(x.results.filter(r=>r.events?.some(e=>e.type==='traverse')).length,1);}
 const storage=memory(),repo=createSaveRepository(storage,runtime);let state=clearedState();while(state.location.x<9)state=runtime.dispatch(state,{type:'move',direction:'right'}).state;repo.save('auto',state);const x=setup(storage);x.fine.click('39,22');settle(x.fine);x.fine.step('right');x.fine.tick(.02);x.fine.interrupt();settle(x.fine);assert.equal(x.session.state.location.regionId,'B-01');});

test('A12 paused/modal/terminal session does not tick or accept fine input',()=>{let modal=false;const x=setup(undefined,{blocked:()=>modal});x.fine.press('right');x.fine.tick(.02);const before=x.fine.snapshot().physical;modal=true;x.fine.interrupt();x.fine.tick(50);assert.deepEqual(x.fine.snapshot().physical,before);assert.equal(x.fine.step('right').ok,false);modal=false;settle(x.fine);assert.equal(x.fine.snapshot().nodeId,'7,22');});


test('A02 newer pointer target waits for one existing microstep and invalidation removes it',()=>{const{fine}=setup();fine.press('right');fine.tick(.04);const pose=fine.snapshot().physical;assert.equal(fine.click('7,23').ok,true);assert.deepEqual(fine.snapshot().physical,pose);settle(fine);assert.equal(fine.snapshot().nodeId,'7,23');fine.press('up');fine.tick(.04);fine.click('6,22');fine.interrupt();settle(fine);assert.equal(fine.snapshot().nodeId,'7,22');assert.equal(fine.snapshot().queuedClick,null);});

test('A04 denied lethal authority battle neither confirms nor grants progress',()=>{const storage=memory(),state=runtime.initialState();state.stats.hp=12;createSaveRepository(storage,runtime).save('auto',state);const{session,fine,confirmations}=setup(storage);fine.entity('b01.timberPuppet');settle(fine);assert.equal(confirmations.length,0);assert.equal(fine.snapshot().pending,null);assert.equal(session.state.stats.hp,12);assert.equal(session.state.stats.gold,0);assert.ok(!session.state.flags['b01.basicEntrance']);assert.equal(fine.snapshot().footprints.find(f=>f.entityId==='b01.timberPuppet').cells.length,13);});

test('A08 startup future fine metadata blocks writes; restart replaces only auto and invalidates old instances',()=>{const{storage,session,fine}=setup();session.save();const raw=JSON.parse(storage.getItem(session.repo.key('auto')));raw.presentation.finePose.schema='future';const bad=JSON.stringify(raw),manual=storage.getItem(session.repo.key('manual'));storage.setItem(session.repo.key('auto'),bad);const extension=createFineForestSaveExtension(runtime),blocked=createForestPreviewSession(runtime,storage,{extension});assert.equal(blocked.compatibilityFailure.code,'fine-pose-compatibility');assert.equal(blocked.save(),false);assert.equal(storage.getItem(session.repo.key('auto')),bad);blocked.restart();assert.equal(blocked.compatibilityFailure,null);assert.equal(storage.getItem(session.repo.key('manual')),manual);assert.notEqual(storage.getItem(session.repo.key('auto')),bad);fine.entity('b01.timberPuppet');settle(fine);const stale=fine.snapshot().pending.token;fine.dispose();const newFine=createFineForestAppAdapter(runtime,session,createFineForestSaveExtension(runtime));newFine.sync(true);newFine.entity('b01.timberPuppet');settle(newFine);assert.equal(newFine.confirm(stale).ok,false);});


test('A11 an explicit adjacent portal action approaches the exact centre before gated traversal',()=>{const storage=memory(),repo=createSaveRepository(storage,runtime);let state=clearedState();while(state.location.x<8)state=runtime.dispatch(state,{type:'move',direction:'right'}).state;repo.save('auto',state);const{fine,session,results}=setup(storage);assert.equal(fine.portalAction({type:'traverse',edgeId:'b.edge.01-02'}).ok,true);settle(fine);assert.equal(session.state.location.regionId,'B-02');assert.equal(results.filter(r=>r.events?.some(e=>e.type==='traverse')).length,1);assert.equal(fine.step('right').ok,false);});


test('A08 repeated startup preserves the exact restored fine auto pose before adapter binding',()=>{const first=setup();first.fine.step('right');settle(first.fine);const key=first.session.repo.key('auto');assert.equal(JSON.parse(first.storage.getItem(key)).presentation.finePose.nodeId,'7,22');first.fine.dispose();for(let i=0;i<3;i++){const extension=createFineForestSaveExtension(runtime),session=createForestPreviewSession(runtime,first.storage,{extension});assert.equal(JSON.parse(first.storage.getItem(key)).presentation.finePose.nodeId,'7,22','constructor must not overwrite restored pose with its centre');const fine=createFineForestAppAdapter(runtime,session,extension);fine.sync(true);assert.equal(fine.snapshot().nodeId,'7,22');fine.dispose();}});


test('A07 hard mode/authority replacement cannot revive a stale partial physical segment',()=>{const{fine,session}=setup();fine.press('right');fine.tick(.03);assert.equal(fine.snapshot().moving,true);fine.sync(false);assert.equal(session.move({type:'move',direction:'right'}).ok,true);assert.equal(session.move({type:'move',direction:'left'}).ok,true);fine.sync(true);assert.equal(fine.snapshot().moving,false);assert.equal(fine.snapshot().nodeId,'6,22');fine.tick(.1);assert.equal(fine.snapshot().nodeId,'6,22');assert.equal(session.state.revision,2);});
