// Actual app import with deterministic DOM/canvas/RAF helpers. No real browser.
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{createForestCampaign}from'../src/campaigns/b/content.js';
import{createSaveRepository}from'../src/core/campaign.js';
import{createForestPreviewSession}from'../src/campaigns/b/preview-session.js';
import{createFineForestSaveExtension}from'../src/rendering/forest-fine-save.js';
import{nativeWorldCell}from'../src/rendering/forest-world-native.js';
const mesh=JSON.parse(readFileSync(new URL('../public/assets/hero-world/hero-mesh.json',import.meta.url),'utf8'));
const html=readFileSync(new URL('../public/campaigns-b/index.html',import.meta.url),'utf8');
const context=()=>new Proxy({measureText:t=>({width:t.length*7}),createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}}),getImageData:(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4),width:w,height:h})},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.events={};this.style={};this.open=false;this.hidden=false;this.disabled=false;this.classList={add(){}};if(tag==='canvas')this.getContext=()=>this.context??=context();}append(...c){this.children.push(...c);}replaceChildren(...c){this.children=c;}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}addEventListener(k,v){this.events[k]=v;}showModal(){this.open=true;}close(){this.open=false;}getBoundingClientRect(){return{width:700,height:500,left:0,top:0};}}
function memory(){const entries=new Map();return{entries,getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v),removeItem:k=>entries.delete(k)};}
async function boot(storage=memory()){
 const nodes=new Map([...html.matchAll(/<([a-z-]+)[^>]*\bid="([^"]+)"[^>]*>/g)].map(([,tag,id])=>[id,new Element(tag)])),dirs=['up','down','left','right'].map(dir=>{const b=new Element('button');b.dataset.dir=dir;return b;}),events={},windowEvents={},frames=new Map(),images=[];let clock=0,id=0;
 const document={hidden:false,getElementById:id=>nodes.get(id),createElement:t=>new Element(t),createTextNode:t=>({textContent:t}),querySelector:s=>s==='dialog[open]'?[...nodes.values()].find(n=>n.tagName==='DIALOG'&&n.open)??null:null,querySelectorAll:s=>s==='[data-dir]'?dirs:s==='[data-close]'?[]:[],addEventListener:(k,fn)=>events[k]=fn};
 class Image{set src(s){this.url=s;this.naturalWidth=s.includes('hero-four-views')?1774:s.includes('world-')?4096:1024;this.naturalHeight=s.includes('hero-four-views')?887:s.includes('world-')?1792:1536;images.push(this);}get src(){return this.url;}}
 const saved={};for(const k of['window','document','confirm','requestAnimationFrame','cancelAnimationFrame','Image','ImageData','fetch','setTimeout','clearTimeout'])saved[k]=globalThis[k];Object.assign(globalThis,{window:{localStorage:storage,addEventListener:(k,fn)=>windowEvents[k]=fn},document,confirm:()=>true,Image,ImageData:class{constructor(data,width,height){Object.assign(this,{data,width,height});}},fetch:async url=>{assert(String(url).endsWith('/assets/hero-world/hero-mesh.json'));return{ok:true,json:async()=>mesh};},requestAnimationFrame:fn=>{frames.set(++id,fn);return id;},cancelAnimationFrame:i=>frames.delete(i),setTimeout:()=>0,clearTimeout:()=>{}});
 let code=readFileSync(new URL('../public/campaigns-b/app.js',import.meta.url),'utf8').replaceAll("from '../src/",`from '${new URL('../src/',import.meta.url).href}`);code+=`\n// unique harness ${Math.random()}\n//# sourceURL=fine-entry-harness.js`;await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);for(let round=0;round<8;round++){await new Promise(resolve=>setImmediate(resolve));for(const image of images.splice(0))image.onload?.();}
 const qa=window.__FOREST_PREVIEW__,get=k=>nodes.get(k),tick=(n=25,dt=100)=>{for(let i=0;i<n;i++){clock+=dt;const callbacks=[...frames.values()];frames.clear();for(const fn of callbacks)fn(clock);assert.ok(frames.size<=1,`fine entry must retain one animation driver, found ${frames.size}`);}},down=(key,code,extra={})=>events.keydown({key,code,target:{tagName:'BODY'},repeat:false,preventDefault(){},...extra}),up=(key,code)=>events.keyup({key,code}),tap=(key,code)=>{down(key,code);up(key,code);},click=id=>get('board').children.find(n=>n.dataset.fineNode===id).onclick();
 return{qa,get,tick,down,up,tap,click,storage,events,windowEvents,document,restore:()=>Object.assign(globalThis,saved)};
}


test('actual app owns one CPU world rig across fine steps, GAL pause, redraw and successful off-center load',async()=>{const e=await boot();try{const{qa,get,tick,down,up,tap}=e;const initial=qa.getVisualState();assert.equal(initial.world.heroRuntime.ready,true);assert.equal(initial.world.heroPresentationMode,'cpu-world-rig');assert.equal(initial.world.heroRuntime.error,null);get('story-pause').onclick();tap('d','KeyD');tick(30,16.6667);assert.equal(qa.getVisualState().fine.nodeId,'7,22');let h=qa.getVisualState().world.heroRuntime;assert(h.lastPaint.poseTravelM>.22&&h.lastPaint.poseTravelM<.42);assert.equal(h.bindings,1);assert.equal(h.error,null);const generation=h.generation;get('map-readability').onclick();assert.equal(qa.getVisualState().world.heroRuntime.lastPaint.poseTravelM,h.lastPaint.poseTravelM);get('save').onclick();const savedRoot=qa.getVisualState().fine.physical.worldFootM;
 down('d','KeyD');tick(5,16.6667);get('resume-story').onclick();assert(get('story').open);tick(1,16.6667);const paused=qa.getVisualState().world.heroRuntime.lastPaint;assert(paused.paused);tick(10,16.6667);const after=qa.getVisualState().world.heroRuntime.lastPaint;assert.deepEqual({...after,ms:0},{...paused,ms:0});get('story-pause').onclick();up('d','KeyD');tick(45,16.6667);h=qa.getVisualState().world.heroRuntime;assert(h.lastPaint.poseTravelM>paused.poseTravelM);assert.equal(h.generation,generation);assert.equal(h.error,null);get('load-manual').onclick();assert.deepEqual(qa.getVisualState().fine.physical.worldFootM,savedRoot);h=qa.getVisualState().world.heroRuntime;assert.equal(h.generation,generation+1);assert.equal(h.lastPaint.poseTravelM,0);assert.equal(h.error,null);assert.equal(qa.getState().stats.gold,0);
}finally{e.restore();}});
