import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {forestGalReadRows,createForestGalReader} from '../src/rendering/forest-gal-reader.js';
import {forestGalComposition} from '../src/rendering/forest-gal-stage.js';
class Node {
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attributes={};this.events={};this.hidden=false;this.inert=false;this.scrollHeight=100;}
 append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}setAttribute(k,v){this.attributes[k]=v;}removeAttribute(k){delete this.attributes[k];}addEventListener(k,f){this.events[k]=f;}focus(){Node.active=this;}
}
const scene=()=>({sceneId:'b01_enter',title:'南坡村口',turns:[{id:'one',text:'台阶上还挂着雨水。',speaker:'旁白'},{id:'two',text:'慢一点。',speaker:'珂珂',portrait:'merchant'},{id:'three',text:'尚未读到的未来。',speaker:'璃',portrait:'hero'},{id:'choice',kind:'choice-prompt',text:'',speaker:'你的选择',choices:[{id:'a',label:'先听她说完'},{id:'b',label:'问问路况'}]}]});
function harness(){const keys=['dialog','stage','body','historyButton','historyPanel','historyEntries','historyClose','hideButton','restoreButton','historyTitle'],nodes=Object.fromEntries(keys.map(k=>[k,new Node()]));return {...nodes,reader:createForestGalReader(nodes,{createElement:tag=>new Node(tag)})};}
test('read rows reveal only displayed turns, copy text, and never mutate the resolved queue',()=>{const s=scene(),before=structuredClone(s),rows=forestGalReadRows(s,1);assert.deepEqual(rows.map(r=>r.id),['one','two']);assert.equal(rows[1].current,true);rows[0].text='local copy';assert.deepEqual(s,before);assert.equal(forestGalReadRows(s,-7).length,1);assert.equal(forestGalReadRows(s,999).length,4);assert.deepEqual(forestGalReadRows(null,0),[]);});
test('history choice record shows only the already selected answer',()=>{const s=scene();s.turns[3].choiceResolved='a';const rows=forestGalReadRows(s,3,'你想怎样回答？');assert.equal(rows[3].text,'你想怎样回答？');assert.equal(rows[3].response,'先听她说完');assert.equal(JSON.stringify(rows).includes('问问路况'),false);});
test('history isolates controls, focuses close, restores focus and leaves source untouched',()=>{const h=harness(),s=scene(),before=structuredClone(s);h.reader.sync(s,1,'');h.historyButton.onclick();assert.equal(h.reader.mode,'history');assert.equal(h.body.inert,true);assert.equal(h.stage.inert,true);assert.equal(h.historyPanel.hidden,false);assert.equal(Node.active,h.historyClose);assert.equal(h.historyEntries.children.length,2);assert.equal(h.historyEntries.scrollTop,100);h.historyClose.onclick();assert.equal(Node.active,h.historyButton);assert.equal(h.body.inert,false);assert.equal(h.historyPanel.hidden,true);assert.equal(h.dialog.attributes['aria-describedby'],'story-copy');assert.deepEqual(s,before);});
test('pure art has reachable restore and Escape dismisses the view before pausing',()=>{const h=harness();h.reader.sync(scene(),1,'');h.hideButton.onclick();assert.equal(h.body.hidden,true);assert.equal(h.stage.inert,true);assert.equal(h.restoreButton.hidden,false);assert.equal(Node.active,h.restoreButton);assert.equal(h.dialog.attributes['aria-describedby'],undefined);assert.equal(h.reader.dismiss(),true);assert.equal(Node.active,h.hideButton);assert.equal(h.body.hidden,false);assert.equal(h.restoreButton.hidden,true);assert.equal(h.reader.dismiss(),false);});
test('H toggles art, ignores modified/repeated/input events and does not hide history',()=>{const h=harness();h.reader.sync(scene(),1,'');const key=(extra={})=>h.dialog.events.keydown({key:'h',target:{tagName:'BUTTON'},preventDefault(){},...extra});for(const extra of [{ctrlKey:true},{metaKey:true},{altKey:true},{repeat:true},{target:{tagName:'TEXTAREA'}},{target:{isContentEditable:true}},{defaultPrevented:true}]){key(extra);assert.equal(h.reader.mode,'reading');}key();assert.equal(h.reader.mode,'art');key();assert.equal(h.reader.mode,'reading');h.historyButton.onclick();key();assert.equal(h.reader.mode,'history');});
test('refresh preserves mode; new scene and reset cannot resurrect stale history',()=>{const h=harness(),s=scene();h.reader.sync(s,1);h.historyButton.onclick();h.reader.sync(s,2);assert.equal(h.reader.mode,'history');assert.equal(h.historyEntries.children.length,3);h.reader.sync({...s,sceneId:'b02_enter'},0);assert.equal(h.reader.mode,'reading');h.hideButton.onclick();h.reader.reset();assert.equal(h.reader.mode,'reading');assert.equal(h.historyEntries.children.length,0);assert.equal(h.body.hidden,false);assert.equal(h.stage.inert,false);});
test('composition stays fixed as speakers change; only explicit horizontal placement accepted',()=>{const cast=[{id:'merchant',position:'scene-merchant',speaking:true},{id:'hero',position:'scene-hero'},{id:'guide',position:'scene-guide'}],a=forestGalComposition(cast),b=forestGalComposition(cast.map(c=>({...c,speaking:c.id==='guide'})));assert.deepEqual(a,b);assert.deepEqual(a.map(p=>p.left),[35.75,49.25,64.25]);assert.deepEqual(a.map(p=>p.depth),['middle','near','far']);assert.equal(forestGalComposition([{id:'hero',position:'right'}])[0].left,77);assert.equal(forestGalComposition([{id:'hero',position:'door'}])[0].left,50);});
test('CSS safeguards maintain restore, reduced motion and stable mobile cast',()=>{const css=readFileSync(new URL('../public/campaigns-b/styles.css',import.meta.url),'utf8');assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/story-restore\{position:absolute/);assert.match(css,/story-body\{left:4%;right:4%/);assert.match(css,/max-height:53%/);assert.doesNotMatch(css,/\[data-speaking="true"\][^{]*\{[^}]*left:/);assert.match(css,/orientation:landscape/);assert.match(css,/overflow:auto;overscroll-behavior:contain/);});

test('portrait contain geometry reserves 118px for location, even on short screens',()=>{
 for(const [w,h]of [[320,568],[375,667],[390,844],[768,1024]])for(const [fraction,bottom,width]of [[.64,.25,.78],[.59,.30,.65],[.55,.33,.58],[.70,.23,.98]]){const boxHeight=Math.min(fraction*h,(1-bottom)*h-118),imageHeight=Math.min(boxHeight,width*w*1.5),top=h-bottom*h-imageHeight;assert.ok(top>=118-1e-8,`${w}x${h}: head-safe image begins ${top}`);assert.ok(imageHeight>0);}
});
