import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {PORTRAITS,STANDING,createPreviewArtRegistry,EXPRESSIONS} from '../public/campaigns-b/moth-preview/src/portrait-contract.mjs';
import {projectMothScene,defaultExpressionForTurn} from '../public/campaigns-b/moth-preview/src/preview-model.mjs';
import {createMothPortraitStage} from '../public/campaigns-b/moth-preview/src/portrait-stage.mjs';
import {mountMothPreview} from '../public/campaigns-b/moth-preview/src/preview.mjs';
import {createDocument,deferred} from './fixtures/moth-preview-fake-dom.mjs';
const sha=bytes=>createHash('sha256').update(new Uint8Array(bytes)).digest('hex');
const assets=[...Object.values(PORTRAITS),STANDING],bytes=new Map();
for(const asset of assets)bytes.set(asset.file,await readFile(new URL('../public/assets/moth-preview/'+asset.file,import.meta.url)));
const arrayBuffer=b=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);
function dependencies(overrides={}){return {fetchAsset:async url=>({ok:true,arrayBuffer:async()=>arrayBuffer(bytes.get(new URL(url).pathname.split('/').at(-1)))}),sha256:async bytes=>sha(bytes),decode:async value=>{const b=Buffer.from(value);return {image:{src:'blob:'+sha(value)},width:b.readUInt32BE(16),height:b.readUInt32BE(20)};},...overrides};}
function harness(){const h=createDocument();return{...h,nodes:{dialog:h.$('story'),portrait:h.$('story-portrait'),actors:h.$('story-actors'),backdrop:h.$('story-backdrop'),label:h.$('story-art-label'),stage:h.$('story-stage'),standing:h.$('preview-standing'),largePortrait:h.$('preview-large-portrait')}};}
const scene=projectMothScene('portrait_check'),request={enemyId:'b06.sideTender',role:'portrait',view:'neutral',phase:'before'};
const tick=()=>new Promise(r=>setImmediate(r));

test('all four actual asset hashes and PNG dimensions match their own descriptors',()=>{for(const asset of assets){const b=bytes.get(asset.file);assert.equal(sha(b),asset.sha256,asset.file);assert.equal(b.readUInt32BE(16),asset.width);assert.equal(b.readUInt32BE(20),asset.height);}assert.equal(new Set(assets.map(a=>a.sha256)).size,4);});
test('three expressions select owned portraits while every standing request keeps the same neutral file',()=>{for(const expression of EXPRESSIONS){const r=createPreviewArtRegistry(expression.id);assert.equal(r.productionReport.holds.length,8);assert.equal(r.resolve(request).asset.sha256,PORTRAITS[expression.id].sha256);const body=r.resolve({...request,role:'dialogue-standing'});assert.equal(body.asset.sha256,STANDING.sha256);assert.equal(body.asset.expressionId,'neutral-fixed');assert.equal(body.productionReady,false);}assert.throws(()=>createPreviewArtRegistry('tired-relief'));});
test('preview art never promotes world, combat, back view, resolution or extra state overrides',()=>{for(const expression of EXPRESSIONS){const r=createPreviewArtRegistry(expression.id);for(const patch of [{role:'world-sprite'},{role:'combat-sprite',phase:'resolution'},{role:'dialogue-standing',view:'back'},{phase:'resolution'},{hp:1},{expressionId:'other'}]){const result=r.resolve({...request,...patch});assert.equal(result.status,'HOLD');assert.equal(result.asset,undefined);}}});
test('default expressions are source-grounded preview mapping without mutating source turns',()=>{const before=structuredClone(scene);assert.equal(defaultExpressionForTurn(scene.turns[0]),'alert');assert.equal(defaultExpressionForTurn(projectMothScene('after_hurt').turns[0]),'gentle-smile');assert.equal(defaultExpressionForTurn(projectMothScene('intro').turns[0]),null);assert.deepEqual(scene,before);});
test('portrait, large inspector and standing all display verified actual bytes atomically',async()=>{const h=harness(),stage=createMothPortraitStage(h.nodes,{dependencies:dependencies()});assert.equal((await stage.present(scene,scene.turns[0],{expressionId:'alert'})).status,'ready');for(const image of [h.nodes.portrait,h.nodes.largePortrait]){assert.equal(image.src,'blob:'+PORTRAITS.alert.sha256);assert.equal(image.hidden,false);assert.equal(image.dataset.expressionId,'alert');}assert.equal(h.nodes.standing.src,'blob:'+STANDING.sha256);assert.equal(h.nodes.standing.dataset.expressionId,'neutral-fixed');});
test('expression switching clears all old layers immediately and keeps the standing neutral',async()=>{const h=harness(),d=deferred();const base=dependencies();const stage=createMothPortraitStage(h.nodes,{dependencies:dependencies({decode:async b=>{if(sha(b)===PORTRAITS['gentle-smile'].sha256)await d.promise;return base.decode(b);}})});await stage.present(scene,scene.turns[0],{expressionId:'alert'});const pending=stage.present(scene,scene.turns[0],{expressionId:'gentle-smile'});for(const image of [h.nodes.portrait,h.nodes.largePortrait,h.nodes.standing]){assert.equal(image.hidden,true);assert.equal(image.src,'');}await tick();d.resolve();assert.equal((await pending).status,'ready');assert.equal(h.nodes.portrait.dataset.expressionId,'gentle-smile');assert.equal(h.nodes.standing.dataset.expressionId,'neutral-fixed');});
test('a delayed old expression cannot overwrite a newer explicit selection',async()=>{const h=harness(),d=deferred(),base=dependencies();const stage=createMothPortraitStage(h.nodes,{dependencies:dependencies({decode:async b=>{if(sha(b)===PORTRAITS.alert.sha256)await d.promise;return base.decode(b);}})});const old=stage.present(scene,scene.turns[0],{expressionId:'alert'});await tick();await stage.present(scene,scene.turns[0],{expressionId:'gentle-smile'});d.resolve();assert.equal((await old).status,'superseded');assert.equal(h.nodes.largePortrait.src,'blob:'+PORTRAITS['gentle-smile'].sha256);assert.equal(h.nodes.standing.hidden,false);});
test('one failed layer blocks the whole pair and releases a late success from its sibling',async()=>{const h=harness(),d=deferred();let disposed=0;const base=dependencies();const stage=createMothPortraitStage(h.nodes,{dependencies:dependencies({fetchAsset:async url=>url.endsWith(STANDING.file)?{ok:false}:base.fetchAsset(url),decode:async b=>{await d.promise;const r=await base.decode(b);r.image.dispose=()=>disposed++;return r;}})});const pending=stage.present(scene,scene.turns[0]);await tick();assert.equal((await pending).status,'failed');d.resolve();await tick();assert.equal(disposed,1);for(const image of [h.nodes.portrait,h.nodes.largePortrait,h.nodes.standing]){assert.equal(image.hidden,true);assert.equal(image.src,'');}});
test('closing during large-display decode or moving to a non-moth line clears every layer',async()=>{const h=harness(),d=deferred();h.nodes.largePortrait.decode=()=>d.promise;const stage=createMothPortraitStage(h.nodes,{dependencies:dependencies()});const pending=stage.present(scene,scene.turns[0]);await tick();stage.clear();d.resolve();assert.equal((await pending).status,'superseded');for(const image of [h.nodes.portrait,h.nodes.largePortrait,h.nodes.standing])assert.equal(image.src,'');h.nodes.largePortrait.decode=async()=>{};await stage.present(scene,scene.turns[0]);const intro=projectMothScene('intro');await stage.present(intro,intro.turns[0]);for(const image of [h.nodes.portrait,h.nodes.largePortrait,h.nodes.standing])assert.equal(image.hidden,true);});
test('unknown expressions fail closed without borrowing the neutral asset',async()=>{const h=harness(),stage=createMothPortraitStage(h.nodes,{dependencies:dependencies()});await stage.present(scene,scene.turns[0]);assert.equal((await stage.present(scene,scene.turns[0],{expressionId:'unknown'})).status,'failed');for(const image of [h.nodes.portrait,h.nodes.largePortrait,h.nodes.standing])assert.equal(image.src,'');});
test('inspector is collapsed by default, does not advance story, and resets expression on new turn',async()=>{const h=harness(),app=mountMothPreview(h.document,{dependencies:dependencies()});h.$('preview-start').click();await tick();assert.equal(h.$('preview-art-tools').hidden,true);assert.equal(h.$('story-portrait').dataset.expressionId,'alert');h.$('preview-art-open').click();assert.equal(h.$('preview-art-tools').hidden,false);assert.equal(h.$('story-body').inert,true);h.document.expressions.find(b=>b.dataset.previewExpression==='neutral').click();await tick();assert.equal(h.$('story-portrait').dataset.expressionId,'neutral');assert.equal(app.snapshot().index,0);h.$('story').emit('keydown',{key:'Enter',target:h.$('preview-large-portrait')});assert.equal(app.snapshot().index,0);h.$('preview-art-close').click();h.$('story-next').click();await tick();assert.equal(app.snapshot().index,1);assert.equal(h.$('story-portrait').dataset.expressionId,'alert');assert.equal(h.$('preview-art-tools').hidden,true);});
test('inspector cancel and held Escape restore tools first without double-closing dialogue',()=>{const h=harness(),app=mountMothPreview(h.document,{dependencies:dependencies()});h.$('preview-start').click();h.$('preview-art-open').click();h.document.emit('keydown',{key:'Escape',target:h.$('preview-art-close')});assert.equal(h.$('preview-art-tools').hidden,true);assert.equal(h.$('story').open,true);h.document.emit('keydown',{key:'Escape',repeat:true,target:h.$('preview-art-open')});h.$('story').emit('cancel');assert.equal(h.$('story').open,true);h.document.emit('keyup',{key:'Escape'});h.$('story').emit('cancel');assert.equal(h.$('story').open,false);assert.equal(app.snapshot().scene,null);});
test('inspector H and wheel do not alter reader mode; closing/reopening restores collapsed default',()=>{const h=harness();mountMothPreview(h.document,{dependencies:dependencies()});h.$('preview-start').click();h.$('preview-art-open').click();h.document.emit('keydown',{key:'h',target:h.$('preview-art-close')});h.$('story').emit('wheel',{deltaY:-40,deltaX:0,target:h.$('preview-large-portrait')});assert.equal(h.$('story').dataset.readerMode,'reading');h.$('story').emit('cancel');assert.equal(h.$('preview-art-tools').hidden,true);assert.equal(h.$('story').open,true);h.$('preview-menu').click();h.$('preview-start').click();assert.equal(h.$('preview-art-tools').hidden,true);assert.equal(h.$('story-body').inert,false);});
test('inspector is a separate shell sibling, while compact frame dimensions and contain safeguards are retained',async()=>{const html=await readFile(new URL('../public/campaigns-b/moth-preview/index.html',import.meta.url),'utf8'),css=await readFile(new URL('../public/campaigns-b/moth-preview/src/portrait-preview.css',import.meta.url),'utf8'),base=await readFile(new URL('../public/campaigns-b/moth-preview/vendor/b-source/preview.css',import.meta.url),'utf8');assert.ok(html.indexOf('id="preview-art-tools"')<html.indexOf('id="story-body"'));assert.match(html,/id="preview-art-tools"[^>]* hidden/);assert.match(css,/\.preview-art-tools\{position:absolute/);assert.match(css,/#preview-standing\{width:80%;height:80%;object-fit:contain/);assert.match(base,/width:28px;height:28px/);assert.match(base,/width:24px;height:24px/);assert.doesNotMatch(css,/\.story-speaker-row[^}]*width:[3-9][0-9]px/);});
test('standing frame uses actual dialogue upper edge without altering dialogue geometry',async()=>{const {standingFrameLayout}=await import('../public/campaigns-b/moth-preview/src/standing-layout.mjs');for(const [height,bodyHeight,headingBottom]of [[768,180,130],[568,280,140],[320,160,120],[1080,450,120]]){const stage={top:20,bottom:height+20,height},body={top:height+20-bodyHeight,bottom:height+20,height:bodyHeight},heading={top:40,bottom:headingBottom,height:headingBottom-40},copy=structuredClone({stage,body,heading});const result=standingFrameLayout({stage,body,heading});if(result.visible){assert.ok(stage.bottom-result.bottom<=body.top-8);assert.ok(stage.top+result.top>=heading.bottom+12);assert.ok(result.height>=80);}else assert.ok(result.height<80);assert.deepEqual({stage,body,heading},copy);}assert.equal(standingFrameLayout({stage:{top:0,bottom:0,height:0},body:null,heading:null}).visible,false);});
test('art-only reader mode can use the space released by hidden dialogue',async()=>{const {standingFrameLayout}=await import('../public/campaigns-b/moth-preview/src/standing-layout.mjs');const stage={top:0,bottom:568,height:568},heading={top:48,bottom:120,height:72},body={top:340,bottom:548,height:208};const reading=standingFrameLayout({stage,heading,body}),art=standingFrameLayout({stage,heading,body,bodyHidden:true});assert.ok(art.height>reading.height);assert.equal(art.bottom,16);});
test('live shell refreshes measured standing frame on open, resize and close without changing the body',()=>{const h=harness();let bodyTop=560;h.$('story-stage').getBoundingClientRect=()=>({top:0,bottom:768,height:768});h.$('story-body').getBoundingClientRect=()=>({top:bodyTop,bottom:740,height:740-bodyTop});h.$('story-location').parentElement.getBoundingClientRect=()=>({top:48,bottom:140,height:92});const app=mountMothPreview(h.document,{dependencies:dependencies()});h.$('preview-start').click();assert.equal(h.$('preview-standing-frame').hidden,false);assert.equal(h.$('preview-standing-frame').style.top,'152px');assert.equal(h.$('preview-standing-frame').style.bottom,'216px');bodyTop=230;h.document.defaultView.emit('resize');assert.equal(h.$('preview-standing-frame').hidden,true);assert.deepEqual(h.$('story-body').style,{});app.close();assert.equal(h.$('preview-standing-frame').hidden,true);});
test('document/BODY-targeted held Escape cannot close inspector and dialogue in one gesture',()=>{const h=harness();mountMothPreview(h.document,{dependencies:dependencies()});h.$('preview-start').click();h.$('preview-art-open').click();const body=h.document.createElement('body');const first=h.document.emit('keydown',{key:'Escape',target:body});h.$('story').emit('cancel');assert.equal(first.defaultPrevented,true);assert.equal(h.$('preview-art-tools').hidden,true);assert.equal(h.$('story').open,true);const repeat=h.document.emit('keydown',{key:'Escape',repeat:true,target:body});h.$('story').emit('cancel');assert.equal(repeat.defaultPrevented,true);assert.equal(h.$('story').open,true);h.document.emit('keyup',{key:'Escape',target:body});h.document.emit('keydown',{key:'Escape',target:body});h.$('story').emit('cancel');assert.equal(h.$('story').open,false);const closed=h.document.emit('keydown',{key:'Escape',target:body});assert.equal(closed.defaultPrevented,false);});
