import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {mountMothPreview} from '../public/campaigns-b/moth-preview/src/preview.mjs';
import {createDocument} from './fixtures/moth-preview-fake-dom.mjs';
const dependencies={fetchAsset:async()=>({ok:false}),sha256:async()=>'',decode:async()=>{throw new Error('Not needed by reader test');}};
function harness(){const h=createDocument();for(const name of ['localStorage','sessionStorage','indexedDB'])Object.defineProperty(h.document.defaultView,name,{get(){throw new Error('Forbidden state access: '+name);}});const app=mountMothPreview(h.document,{dependencies});h.$('preview-start').click();return {...h,app};}
const key=(h,extra={})=>h.$('story').emit('keydown',{key:'Enter',target:h.$('story-copy'),...extra});
const wheel=(h,extra={})=>h.$('story').emit('wheel',{target:h.$('story-copy'),deltaY:-40,deltaX:0,...extra});
test('real compact shell IDs remain present, unique and wired; frozen reader is imported',async()=>{const html=await readFile(new URL('../public/campaigns-b/moth-preview/index.html',import.meta.url),'utf8'),source=await readFile(new URL('../public/campaigns-b/moth-preview/src/preview.mjs',import.meta.url),'utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);for(const [,id]of source.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.includes(id),id);assert.match(html,/story-speaker-row" id="preview-speaker-badge"/);assert.match(html,/<img id="story-portrait"/);assert.match(html,/preview-dialog-panel/);assert.match(source,/vendor\/b-source\/forest-gal-reader.js/);});
test('continue and guarded body click advance once while holding/repeating Enter does not',()=>{const h=harness();key(h,{repeat:true});assert.equal(h.app.snapshot().index,0);key(h);assert.equal(h.app.snapshot().index,1);key(h);assert.equal(h.app.snapshot().index,1);h.$('story-back').click();h.$('story-body').emit('click',{target:h.$('story-copy'),detail:0});assert.equal(h.app.snapshot().index,1);});
test('modified/composing keys, selection, controls and draggable pointer gestures do not advance',()=>{for(const extra of [{ctrlKey:true},{metaKey:true},{altKey:true},{shiftKey:true},{isComposing:true},{target:{tagName:'INPUT'}},{target:{tagName:'DIV',isContentEditable:true}}]){const h=harness();key(h,extra);assert.equal(h.app.snapshot().index,0);}const h=harness();h.document.selection='selected';key(h);h.$('story-body').emit('click',{target:h.$('story-copy')});assert.equal(h.app.snapshot().index,0);h.document.selection='';key(h,{target:h.$('story-next')});assert.equal(h.app.snapshot().index,0);h.$('story-next').click();assert.equal(h.app.snapshot().index,1);h.$('story-back').click();h.$('story-body').emit('pointerdown',{target:h.$('story-copy'),pointerId:1,clientX:0,clientY:0});h.$('story-body').emit('pointermove',{pointerId:1,clientX:20,clientY:20});h.$('story-body').emit('click',{target:h.$('story-copy'),detail:1});assert.equal(h.app.snapshot().index,0);});
test('wheel up opens already-read history without advancing; text scroll gets priority',()=>{const h=harness();h.$('story-body').scrollTop=20;wheel(h);assert.equal(h.$('story').dataset.readerMode,'reading');h.$('story-body').scrollTop=0;const event=wheel(h);assert.equal(event.defaultPrevented,true);assert.equal(h.$('story').dataset.readerMode,'history');assert.equal(h.app.snapshot().index,0);assert.equal(h.$('story-history-entries').children.length,1);key(h);assert.equal(h.app.snapshot().index,0);h.$('story-history-close').click();key(h);wheel(h);assert.equal(h.$('story-history-entries').children.length,2);});
test('wheel down, horizontal, modified, small-delta and selected-text scrolling do not open history',()=>{for(const extra of [{deltaY:40},{deltaX:50},{ctrlKey:true},{deltaY:-5},{target:{tagName:'INPUT'}}]){const h=harness();wheel(h,extra);assert.equal(h.$('story').dataset.readerMode,'reading');}const h=harness();h.document.selection='text';wheel(h);assert.equal(h.$('story').dataset.readerMode,'reading');});
test('H/art and cancel/history restore before closing, and reopening clears read history',()=>{const h=harness();key(h,{key:'h'});assert.equal(h.$('story').dataset.readerMode,'art');key(h);assert.equal(h.app.snapshot().index,0);h.$('story').emit('cancel');assert.equal(h.$('story').dataset.readerMode,'reading');assert.equal(h.$('story').open,true);wheel(h);h.$('story').emit('cancel');assert.equal(h.$('story').dataset.readerMode,'reading');assert.equal(h.$('story').open,true);h.$('story').emit('cancel');assert.equal(h.$('story').open,false);assert.equal(h.app.snapshot().scene,null);h.$('preview-start').click();assert.equal(h.app.snapshot().index,0);assert.equal(h.$('story-history-entries').children.length,0);assert.equal(h.$('story-portrait').hidden,true);});
test('BFCache pagehide closes read-only preview and invalidates art',()=>{const h=harness();h.document.defaultView.emit('pagehide');assert.equal(h.$('story').open,false);assert.equal(h.app.snapshot().scene,null);assert.equal(h.$('story-portrait').hidden,true);assert.equal(h.$('story-portrait').src,'');});
test('changing scenario clears old history and cannot execute combat or alter progress',()=>{const h=harness();key(h);wheel(h);h.document.variants.find(b=>b.dataset.previewScenario==='after_hurt').click();assert.equal(h.app.snapshot().scene.sceneId,'after_hurt');assert.equal(h.app.snapshot().index,0);assert.equal(h.$('story').dataset.readerMode,'reading');assert.equal(h.$('story-history-entries').children.length,0);assert.equal(h.app.snapshot().turn.speaker,'冠蛾');});
test('headless geometry contract uses entire uncropped image with safe container padding',async()=>{const css=await readFile(new URL('../public/campaigns-b/moth-preview/src/portrait-preview.css',import.meta.url),'utf8');assert.match(css,/object-fit:contain/);assert.match(css,/border-radius:0/);assert.match(css,/padding:2px/);assert.match(css,/#story-portrait\[hidden\]\{display:none!important\}/);assert.doesNotMatch(css,/clip-path|object-fit:cover|scale\(/);for(const width of [24,28]){const inner=width-4,scale=inner/1254;assert.ok(inner>0);assert.equal(1254*scale,inner);assert.ok(2+12*scale>2);}});
test('moth speaker is not styled as narration, while original source turns stay untouched',()=>{const h=harness();assert.equal(h.$('story').dataset.narration,'false');assert.equal(h.app.snapshot().turn.portrait,undefined);h.document.variants.find(b=>b.dataset.previewScenario==='intro').click();assert.equal(h.$('story').dataset.narration,'true');});
