import test from 'node:test';import assert from 'node:assert/strict';
import {createForestCampaign}from'../src/campaigns/b/content.js';
import {FINE_FOREST,buildFineForestGeometry,createFineForestNavigation,fineColliderAt}from'../src/rendering/forest-fine-navigation.js';
import {NATIVE_FOREST_WORLD as native}from'../src/rendering/forest-world-contract.js';
const r=createForestCampaign(),g=buildFineForestGeometry(r);
function settle(nav,limit=2400){for(let i=0;i<limit;i++){const s=nav.snapshot();if(!s.moving&&!s.queuedMicrosteps&&!s.held)return s;nav.tick(1/60);}throw Error('Navigation did not settle');}
function approachPuppet(nav){assert.equal(nav.click('16,22').ok,true);const s=settle(nav);assert.equal(s.pending.entityId,'b01.timberPuppet');return s;}
function clearPuppet(nav){const s=approachPuppet(nav);assert.equal(nav.confirm(s.pending.token).ok,true);return nav.snapshot();}

test('B01 has genuinely finer supported local positions, 4 per old axis, original identity unchanged',()=>{assert.equal(FINE_FOREST.subdivision,4);assert.equal(g.nodes.size,481);assert.equal(g.rejected.length,143);assert.equal(r.identity.contentHash,'a12cd07ee1ccc762');assert.equal(r.region('B-01').map.join('').split('.').length-1,39);assert.equal(r.spec.regions.length,30);for(const n of g.nodes.values()){assert.equal(fineColliderAt(n.sample),null);assert.equal(n.sample.source,'saved-native-support-triangle');}});

test('every fine edge has support and maps only to an original legal source edge',()=>{const edges=new Set(native.edges.filter(e=>e.sourceRegionId==='B-01').flatMap(e=>[`${e.from}>${e.to}`,`${e.to}>${e.from}`]));for(const n of g.nodes.values())for(const e of n.neighbors){const m=g.nodes.get(e.id);assert.ok(Math.abs(n.ix-m.ix)+Math.abs(n.iy-m.iy)===1);assert.ok(e.distanceM>.05&&e.distanceM<.5);if(e.logicalMove)assert.ok(edges.has(`${n.source.x},${n.source.y}>${m.source.x},${m.source.y}`));}});

test('all 39 original floor centres remain connected after the gate clears',()=>{const nav=createFineForestNavigation(r);clearPuppet(nav);let count=0;for(let y=0;y<11;y++)for(let x=0;x<11;x++)if(r.region('B-01').map[y][x]==='.'){assert.equal(nav.plan(`${4*x+2},${4*y+2}`).ok,true,`${x},${y}`);count++;}assert.equal(count,39);});

test('short key tap finishes only one 0.3 m microstep, without changing logical state',()=>{const nav=createFineForestNavigation(r),before=r.serialize(nav.snapshot().state);nav.press('right');nav.tick(.03);nav.release();const result=settle(nav);assert.equal(result.nodeId,'7,22');assert.ok(result.distanceM>.25&&result.distanceM<.35);assert.equal(r.serialize(result.state),before);assert.equal(result.actions.length,0);const p=result.physical.worldFootM;for(let i=0;i<120;i++)nav.tick(1/60);assert.deepEqual(nav.snapshot().physical.worldFootM,p);});

test('held travel and release never queue whole old cells; accumulated phase is metre based',()=>{const nav=createFineForestNavigation(r);nav.press('right');for(let i=0;i<45;i++)nav.tick(1/60);nav.release();const before=nav.snapshot().distanceM,s=settle(nav);assert.ok(s.distanceM-before<.35);assert.ok(s.distanceM>.6);assert.equal(s.actions.length,s.state.revision);assert.equal(s.state.location.x,2);});

test('multi-cell puppet blocks the entire logical gate, cannot be skirted around vegetation',()=>{const nav=createFineForestNavigation(r),s=nav.snapshot(),shape=s.footprints.find(e=>e.entityId==='b01.timberPuppet');assert.equal(shape.cells.length,13);for(const id of shape.cells)assert.equal(nav.plan(id).ok,false);assert.equal(nav.plan('22,22').ok,false);assert.equal(nav.plan('18,34').ok,false);assert.equal(nav.snapshot().state.stats.gold,0);});

test('many contact cells produce one pending action, one battle, one reward, one atomic footprint release',()=>{const nav=createFineForestNavigation(r),s=approachPuppet(nav);const hp=s.state.stats.hp;for(let i=0;i<50;i++){const result=nav.contact('b01.timberPuppet');assert.equal(result.duplicate,true);assert.equal(result.token,s.pending.token);}const result=nav.confirm(s.pending.token);assert.equal(result.ok,true);assert.equal(result.events.filter(e=>e.type==='battle').length,1);const after=nav.snapshot();assert.equal(after.state.stats.gold,3);assert.equal(after.state.stats.hp,hp-12);assert.equal(after.footprints.some(e=>e.entityId==='b01.timberPuppet'),false);assert.equal(nav.confirm(s.pending.token).ok,false);for(let i=0;i<50;i++)assert.equal(nav.contact('b01.timberPuppet').ok,false);assert.deepEqual(nav.snapshot().state,after.state);assert.equal(nav.plan('22,22').ok,true);});

test('click approaches multi-cell pickup and duplicate contacts never repeat defence gain',()=>{const nav=createFineForestNavigation(r);clearPuppet(nav);const before=nav.snapshot().state.stats.def;assert.equal(nav.click('18,34').ok,true);let s=settle(nav);assert.equal(s.pending.entityId,'b01.guardPlate');assert.equal(nav.confirm(s.pending.token).ok,true);s=nav.snapshot();assert.equal(s.state.stats.def,before+2);assert.equal(s.footprints.some(e=>e.entityId==='b01.guardPlate'),false);for(let i=0;i<30;i++)assert.equal(nav.contact('b01.guardPlate').ok,false);assert.equal(nav.snapshot().state.stats.def,before+2);});

test('cancel is costless, stale confirmation cannot commit a later repeated interaction',()=>{const nav=createFineForestNavigation(r),before=approachPuppet(nav),old=before.pending.token;nav.cancel();assert.deepEqual(nav.snapshot().state,before.state);for(let i=0;i<10;i++)assert.equal(nav.contact('b01.timberPuppet').ok,false);assert.equal(nav.click('16,22').ok,true);const token=nav.snapshot().pending.token;assert.notEqual(token,old);assert.equal(nav.confirm(old).ok,false);assert.deepEqual(nav.snapshot().state,before.state);assert.equal(nav.confirm(token).ok,true);});

test('collapsed fine actions replay exactly through the unchanged original reducer',()=>{const nav=createFineForestNavigation(r);clearPuppet(nav);nav.click('18,34');let s=settle(nav);nav.confirm(s.pending.token);s=nav.snapshot();let replay=r.initialState();for(const action of s.actions){const result=r.dispatch(replay,action);assert.equal(result.ok,true);replay=result.state;}assert.deepEqual(replay,s.state);});

test('fine save restores exact offset; legacy save imports unchanged at its source centre',()=>{const nav=createFineForestNavigation(r);nav.step('right');settle(nav);const saved=nav.save();assert.equal(saved.ok,true);const fresh=createFineForestNavigation(r);assert.equal(fresh.load(saved.value).migration,'fine-sidecar-restored');assert.equal(fresh.snapshot().nodeId,'7,22');assert.deepEqual(fresh.snapshot().state,nav.snapshot().state);assert.deepEqual(fresh.snapshot().physical,nav.snapshot().physical);const raw=r.serialize(r.initialState());assert.equal(fresh.load(raw).migration,'legacy-state-unchanged-center-anchor');assert.equal(r.serialize(fresh.snapshot().state),raw);assert.equal(fresh.snapshot().nodeId,'6,22');});

test('save mid microstep is explicit; tampered or mismatched sidecars are rejected without campaign rewrite',()=>{const nav=createFineForestNavigation(r);nav.press('right');nav.tick(.05);nav.release();assert.equal(nav.save().reason,'microstep-in-progress');settle(nav);const good=JSON.parse(nav.save().value),before=r.serialize(nav.snapshot().state);for(const[k,v]of [['subdivision',8],['revision','future'],['stateHash','wrong'],['nodeId','18,34']]){const bad=structuredClone(good);bad.navigation[k]=v;assert.equal(nav.load(JSON.stringify(bad)).ok,false);assert.equal(r.serialize(nav.snapshot().state),before);}});

test('analytic swept capsule catches a thin blocker between legal endpoints and rejects corner squeezing',async()=>{const{fineCapsuleHitsPolygon,fineSweptCollider}=await import('../src/rendering/forest-fine-navigation.js');const post=[[.145,-.005],[.155,-.005],[.155,.005],[.145,.005]];assert.equal(fineCapsuleHitsPolygon([0,0],[.3,0],post,.01),true);assert.equal(fineCapsuleHitsPolygon([0,.2],[.3,.2],post,.18),false);assert.equal(fineCapsuleHitsPolygon([0,.17],[.3,.17],post,.18),true);for(const n of g.nodes.values())for(const e of n.neighbors)assert.equal(fineSweptCollider(n.sample,g.nodes.get(e.id).sample),null);});

test('collapsed fine graph is exactly the 100 directed B01 source edges, without diagonal corner cutting',()=>{const expected=new Set(native.edges.filter(e=>e.sourceRegionId==='B-01').flatMap(e=>[`${e.from}>${e.to}`,`${e.to}>${e.from}`])),actual=new Set();for(const n of g.nodes.values())for(const e of n.neighbors){const m=g.nodes.get(e.id);assert.equal(Math.abs(m.ix-n.ix)+Math.abs(m.iy-n.iy),1);if(e.logicalMove)actual.add(`${n.source.x},${n.source.y}>${m.source.x},${m.source.y}`);}assert.equal(actual.size,100);assert.deepEqual([...actual].sort(),[...expected].sort());});

test('held keys and clicks while confirmation is pending never enqueue post-battle travel',()=>{const nav=createFineForestNavigation(r),s=approachPuppet(nav);for(let i=0;i<30;i++){assert.equal(nav.press('right').ok,false);assert.equal(nav.click('22,22').ok,false);nav.tick(.1);}assert.equal(nav.confirm(s.pending.token).ok,true);const at=nav.snapshot().physical;for(let i=0;i<30;i++)nav.tick(.1);assert.deepEqual(nav.snapshot().physical,at);assert.equal(nav.snapshot().queuedMicrosteps,0);assert.equal(nav.snapshot().held,null);});

test('actor radius also protects the dynamic gate from the opposite side, with the same entity ID',()=>{const state=r.initialState();state.location={regionId:'B-01',x:5,y:5};const nav=createFineForestNavigation(r,{state});assert.equal(nav.step('left').ok,true);settle(nav);assert.equal(nav.snapshot().nodeId,'21,22');const contact=nav.step('left');assert.equal(contact.pending,true);assert.equal(nav.snapshot().pending.entityId,'b01.timberPuppet');assert.equal(nav.snapshot().nodeId,'21,22');assert.equal(nav.confirm(nav.snapshot().pending.token).ok,true);assert.equal(nav.step('left').ok,true);settle(nav);assert.equal(nav.snapshot().nodeId,'20,22');});

test('R2 every failed load invalidates the old pending token without changing campaign or pose',()=>{for(const raw of ['{','null','[]','12','"save"','false',JSON.stringify({schema:'unknown'})]){const nav=createFineForestNavigation(r),before=approachPuppet(nav),old=before.pending.token;const result=nav.load(raw);assert.equal(result.ok,false);assert.equal(nav.snapshot().pending,null);assert.deepEqual(nav.snapshot().state,before.state);assert.deepEqual(nav.snapshot().physical,before.physical);assert.equal(nav.contact('b01.timberPuppet').pending,true);assert.notEqual(nav.snapshot().pending.token,old);assert.equal(nav.confirm(old).ok,false);assert.deepEqual(nav.snapshot().state,before.state);assert.equal(nav.confirm(nav.snapshot().pending.token).ok,true);}});

test('R2 failed load during movement preserves the current physical pose instead of snapping to an old node',()=>{const nav=createFineForestNavigation(r);nav.press('right');nav.tick(.05);const before=nav.snapshot();assert.equal(nav.load('{').ok,false);const after=nav.snapshot();assert.deepEqual(after.state,before.state);assert.deepEqual(after.physical,before.physical);assert.equal(after.distanceM,before.distanceM);assert.equal(after.held,null);assert.equal(after.queuedMicrosteps,0);});

test('R2 victory freezes physical microsteps, held input and click planning just as it freezes the reducer',()=>{const state=r.initialState();state.victory=true;const nav=createFineForestNavigation(r,{state}),before=nav.snapshot();assert.equal(nav.step('right').reason,'campaign-complete');assert.equal(nav.press('right').reason,'campaign-complete');assert.equal(nav.click('7,22').reason,'campaign-complete');assert.equal(nav.plan('7,22').reason,'campaign-complete');for(let i=0;i<50;i++)nav.tick(.1);const after=nav.snapshot();assert.deepEqual(after.state,before.state);assert.deepEqual(after.physical,before.physical);assert.equal(after.distanceM,before.distanceM);assert.equal(after.moving,false);assert.equal(after.held,null);});

test('R2 fine sidecars cannot restore a body overlapping a still-active multi-cell blocker',()=>{const state=r.initialState();state.location={regionId:'B-01',x:5,y:5};const nav=createFineForestNavigation(r,{state}),saved=JSON.parse(nav.save().value);saved.navigation.nodeId='20,22';const before=nav.snapshot();assert.equal(nav.load(JSON.stringify(saved)).reason,'occupied-navigation-position');assert.deepEqual(nav.snapshot().state,before.state);assert.deepEqual(nav.snapshot().physical,before.physical);});

test('R2 construction rejects a logical floor occupied by the live puppet',()=>{const state=r.initialState();state.location={regionId:'B-01',x:4,y:5};assert.throws(()=>createFineForestNavigation(r,{state}),/clear actor footprint/);});

test('R2 confirmation tokens cannot be reused across replaced navigation instances',()=>{const a=createFineForestNavigation(r),b=createFineForestNavigation(r);const old=approachPuppet(a),fresh=approachPuppet(b);assert.notEqual(old.pending.token,fresh.pending.token);assert.equal(b.confirm(old.pending.token).reason,'stale-confirmation');assert.deepEqual(b.snapshot().state,fresh.state);assert.equal(b.confirm(fresh.pending.token).ok,true);});

test('R2 zero, negative and non-finite speeds are rejected before movement can deadlock saving',()=>{for(const speedMps of [0,-1,NaN,Infinity,-Infinity,'1.2'])assert.throws(()=>createFineForestNavigation(r,{speedMps}),/finite and positive/);const nav=createFineForestNavigation(r,{speedMps:.1});assert.equal(nav.step('right').ok,true);assert.equal(settle(nav).nodeId,'7,22');assert.equal(nav.save().ok,true);});
