import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{createHash}from'node:crypto';
import{FOREST_REVIEWED_PORTRAITS as ART,FOREST_REVIEWED_PORTRAIT_ROWS as ROWS,forestReviewedPortrait as match}from'../src/rendering/forest-reviewed-portraits.js';
import{FOREST_CAST_ART}from'../src/rendering/forest-cast-art.js';import{FOREST_STORY_CONTENT as C}from'../src/campaigns/b/story/content.js';import{forestTurnStage}from'../src/campaigns/b/story/presentation.js';import{presentForestGal,clearForestGal,forestGalActors,forestGalPresentation}from'../src/rendering/forest-gal-stage.js';
const turn=r=>{const t=C.scenes[r.sceneId].turns.find(t=>t.id===r.turnId);return{...structuredClone(t),stage:forestTurnStage(r.sceneId,t,{})};};
test('only 25 reviewed watchful fox and 2 home daily queen turns; source bytes retained',()=>{assert.equal(ROWS.length,27);assert.equal(ROWS.filter(r=>r.portrait==='fox_boss').length,25);assert.deepEqual(ROWS.filter(r=>r.portrait==='final_queen').map(r=>r.turnId),['b29_home.L1793','b29_home.L1797']);assert.equal(Object.keys(FOREST_CAST_ART).length,4);for(const a of Object.values(ART))assert.equal(createHash('sha256').update(readFileSync(new URL('../public/'+a.file,import.meta.url))).digest('hex'),a.sha256);for(const r of ROWS){const t=turn(r),before=JSON.stringify(t);assert.equal(match({sceneId:r.sceneId},t),ART[r.portrait]);assert.equal(match({sceneId:r.sceneId},JSON.parse(before)),ART[r.portrait]);assert.equal(JSON.stringify(t),before);assert.ok(!forestGalActors(t,forestGalPresentation({sceneId:r.sceneId},t)).some(a=>a.id===r.portrait));}});
test('all authored turns are fail-closed outside whitelist; identity, text, geography and safety gates are exact',()=>{for(const[sid,s]of Object.entries(C.scenes))for(const source of s.turns){const t={...source,stage:forestTurnStage(sid,source,{})};assert.equal(!!match({sceneId:sid},t),ROWS.some(r=>r.turnId===t.id));}for(const r of ROWS){for(const mutate of [t=>delete t.stage,t=>t.text+=' ',...['id','sourceLine','branch','phase','portrait','speaker','kind'].map(k=>t=>t[k]='bad'),...['locationId','backdropAssetId','camera'].map(k=>t=>t.stage[k]='bad'),t=>t.stage.portraitAllowed=false,t=>t.stage.winterClothing=true,t=>t.stage.offscreen[t.portrait]=true,t=>delete t.stage.actors[t.portrait]]){const t=turn(r);mutate(t);assert.equal(match({sceneId:r.sceneId},t),null);}assert.equal(match({sceneId:'other'},turn(r)),null);}});
class Node{constructor(){this.dataset={};this.style={};this.children=[];this.hidden=true;this.complete=false;}removeAttribute(k){delete this[k];}replaceChildren(...x){this.children=x;}load(w,h){this.naturalWidth=w;this.naturalHeight=h;this.onload?.();}}
const nodes=()=>Object.fromEntries(['backdrop','actors','portrait','label','stage','dialog'].map(k=>[k,new Node()]));
test('renderer new portraits load, fail and clear safely; crop never leaks to next speaker/CG/hidden',()=>{const old=globalThis.document;globalThis.document={createElement:()=>new Node()};try{for(const r of ROWS){const n=nodes(),t=turn(r),scene={sceneId:r.sceneId},a=ART[r.portrait];presentForestGal(n,scene,t);assert.ok(n.portrait.src.endsWith(a.file));assert.equal(n.portrait.hidden,true);n.portrait.load(a.width,a.height);assert.equal(n.portrait.hidden,false);assert.equal(n.portrait.dataset.portraitCrop,a.crop??'');const stale=n.portrait.onload;clearForestGal(n);stale();assert.equal(n.portrait.hidden,true);assert.equal(n.portrait.dataset.portraitCrop,'');presentForestGal(n,scene,t);n.portrait.load(1,1);assert.equal(n.portrait.hidden,true);assert.equal(n.portrait.src,undefined);clearForestGal(n);presentForestGal(n,scene,t);n.portrait.onerror();assert.equal(n.portrait.src,undefined);clearForestGal(n);presentForestGal(n,scene,t);const stale2=n.portrait.onload;presentForestGal(n,scene,{...t,text:t.text+'changed'});stale2();assert.equal(n.portrait.hidden,true);assert.equal(n.portrait.dataset.portraitCrop,'');assert.equal(n.portrait.src,undefined);}const n=nodes(),r=ROWS.at(-1);presentForestGal(n,{sceneId:r.sceneId},turn(r));const a=C.scenes.b29_home.turns.find(t=>t.id==='b29_home.L1789');presentForestGal(n,{sceneId:'b29_home'},{...a,stage:forestTurnStage('b29_home',a,{})});assert.equal(n.portrait.hidden,true);assert.equal(n.portrait.dataset.portraitCrop,'');assert.deepEqual(n.actors.children,[]);}finally{globalThis.document=old;}});
test('daily PNG is CSS-cropped inside a dedicated window; no pixel-edited runtime asset',()=>{const css=readFileSync(new URL('../public/campaigns-b/styles.css',import.meta.url),'utf8'),html=readFileSync(new URL('../public/campaigns-b/index.html',import.meta.url),'utf8');assert.match(html,/<span class="story-portrait-window"><img id="story-portrait"/);assert.match(css,/width:320%;height:480%;max-width:none;left:-110%;top:-5%;object-fit:contain;object-position:50% 50%/);for(const n of [26,34,38]){const scale=n/320;assert.ok(440*scale-352*scale>0);assert.ok(570*scale-352*scale<n);assert.ok(200*scale-16*scale<n);}assert.equal(ART.final_queen.width,1024);assert.equal(ART.final_queen.height,1536);});
