import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{createForestCampaign}from'../src/campaigns/b/content.js';import{createSaveRepository}from'../src/core/campaign.js';import{FOREST_STORY_CONTENT}from'../src/campaigns/b/story/index.js';import{forestWalkPath}from'../src/campaigns/b/view.js';
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.events={};this.style={};this.open=false;this.hidden=false;this.disabled=false;this.classList={add(){}};}append(...c){this.children.push(...c);}replaceChildren(...c){this.children=c;}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}addEventListener(k,v){this.events[k]=v;}showModal(){this.open=true;}close(){this.open=false;}getBoundingClientRect(){return{width:570,height:439};}}
const html=readFileSync(new URL('../public/campaigns-b/index.html',import.meta.url),'utf8');
test('real app serializes keyrepeat, reverse input, modal and renderer toggle during a seam; restores saved source position',async()=>{
 const runtime=createForestCampaign();let initial=runtime.initialState();for(const a of forestWalkPath(runtime,initial,3,5))initial=runtime.dispatch(initial,a).state;initial=runtime.dispatch(initial,{type:'interact',entityId:'b01.timberPuppet'}).state;for(const a of forestWalkPath(runtime,initial,9,5))initial=runtime.dispatch(initial,a).state;
 const entries=new Map(),storage={getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v),removeItem:k=>entries.delete(k)},repo=createSaveRepository(storage,runtime),presentation={storyVersion:FOREST_STORY_CONTENT.id,seenIds:[],queue:[],turnIndex:0,paused:true};repo.save('auto',initial,presentation);repo.save('manual',initial,presentation);
 const nodes=new Map([...html.matchAll(/<([a-z-]+)[^>]*\bid="([^"]+)"[^>]*>/g)].map(([,t,id])=>[id,new Element(t)])),dirs=['up','down','left','right'].map(dir=>{const b=new Element('button');b.dataset.dir=dir;return b;}),events={},frames=new Map();let clock=0,id=0;
 const ctx=new Proxy({measureText:t=>({width:t.length*.18})},{get:(t,k)=>k in t?t[k]:()=>{},set:(t,k,v)=>(t[k]=v,true)});nodes.get('map-canvas').getContext=()=>ctx;
 const document={getElementById:id=>nodes.get(id),createElement:t=>new Element(t),createTextNode:t=>({textContent:t}),querySelector:s=>s==='dialog[open]'?[...nodes.values()].find(n=>n.open)??null:null,querySelectorAll:s=>s==='[data-dir]'?dirs:[],addEventListener:(k,fn)=>events[k]=fn};
 const saved={};for(const k of['window','document','confirm','requestAnimationFrame','cancelAnimationFrame','Image','setTimeout','clearTimeout'])saved[k]=globalThis[k];Object.assign(globalThis,{window:{localStorage:storage},document,confirm:()=>true,Image:undefined,requestAnimationFrame:fn=>{frames.set(++id,fn);return id;},cancelAnimationFrame:id=>frames.delete(id),setTimeout:()=>0,clearTimeout:()=>{}});
 function tick(n=320){for(let i=0;i<n;i++){clock+=1000/60;const callbacks=[...frames.values()];frames.clear();for(const fn of callbacks)fn(clock);}}
 try{const code=readFileSync(new URL('../public/campaigns-b/app.js',import.meta.url),'utf8').replaceAll("from '../src/",`from '${new URL('../src/',import.meta.url).href}`);await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);const qa=window.__FOREST_PREVIEW__,get=k=>nodes.get(k),key=direction=>{let prevented=false;events.keydown({key:'Arrow'+direction,target:{tagName:'BODY'},repeat:false,preventDefault(){prevented=true;}});events.keyup?.({key:'Arrow'+direction});return prevented;};
 assert.equal(qa.getVisualState().renderer,'continuous-world');key('Right');assert.equal(qa.getState().location.regionId,'B-02');assert.equal(qa.getState().revision,initial.revision+1);const committed=qa.getState();
 for(let i=0;i<50;i++)assert.equal(key(i%2?'Left':'Right'),true,'held movement key must not scroll the page while motion is blocked');get('help').onclick();get('map-world-mode').onclick();assert.deepEqual(qa.getState(),committed);assert.equal(get('settings').open,false);assert.equal(qa.getVisualState().worldMode,true);assert.equal(qa.getVisualState().world.queuedSegments,1);
 tick();assert.equal(qa.getVisualState().world.moving,false);key('Right');assert.equal(qa.getState().location.x,2);const moved=qa.getState();key('Right');key('Left');assert.deepEqual(qa.getState(),moved);tick();key('Left');tick();key('Left');assert.equal(qa.getState().location.regionId,'B-01');tick();assert.deepEqual(qa.getState().resources,initial.resources);assert.deepEqual(qa.getState().stats,initial.stats);
 get('help').onclick();assert.equal(get('settings').open,true);get('load-manual').onclick();assert.deepEqual(qa.getState(),initial);assert.deepEqual(qa.getVisualState().world.hero,qa.getVisualState().world.camera);assert.equal(qa.getVisualState().world.queuedSegments,0);
 get('map-world-mode').onclick();assert.equal(qa.getVisualState().worldMode,false);assert.deepEqual(qa.getState(),initial);get('map-world-mode').onclick();assert.equal(qa.getVisualState().worldMode,true);assert.deepEqual(qa.getState(),initial);
 get('resume-story').onclick();for(let guard=0;get('story').open&&guard<10;guard++)get('story-skip').onclick();assert.equal(get('story').open,false);key('Right');assert.equal(qa.getState().location.regionId,'B-02');assert.equal(qa.getVisualState().world.moving,true);assert.equal(get('story').open,false);tick();for(const action of forestWalkPath(runtime,qa.getState(),9,5)){key(action.direction[0].toUpperCase()+action.direction.slice(1));tick(75);}key('Right');assert.equal(qa.getState().location.regionId,'B-03');assert.equal(get('story').open,false,'new entry dialogue must not obscure the visible crossing');tick();assert.equal(get('story').open,true,'queued source dialogue opens after crossing settles');const withStory=qa.getState();key('Right');assert.deepEqual(qa.getState(),withStory);
 }finally{Object.assign(globalThis,saved);}
});
