// Small soft contact shadows in the same native projection/depth coordinates as the actor.
// Presentation only. Input foot frames come from the current world-foot pose, never a cell center.
export class SoftwareFootShadows {
 constructor({camera,terrainDepth,supportAtPixel}){if(terrainDepth&&typeof supportAtPixel!=='function')throw Error('Native support-at-pixel predicate required for terrain shadows');this.camera=camera;this.terrain=terrainDepth;this.supportAtPixel=supportAtPixel;this.groundCaches=new Map();this.capacity=0;this.data=null;}
 project(p){const a=this.camera.affine;return[a.origin_px[0]+p[0]*a.x_m[0]+p[1]*a.y_m[0]+p[2]*a.z_m[0],a.origin_px[1]+p[0]*a.x_m[1]+p[1]*a.y_m[1]+p[2]*a.z_m[1]];}
 vector(p){const a=this.camera.affine;return[p[0]*a.x_m[0]+p[1]*a.y_m[0]+p[2]*a.z_m[0],p[0]*a.x_m[1]+p[1]*a.y_m[1]+p[2]*a.z_m[1]];}
 render(pose,{scale=1,depthBiasM=.015}={}){const terms=pose.legs.map(leg=>{const n=leg.frame.normal,x=leg.frame.x,y=[n[1]*x[2]-n[2]*x[1],n[2]*x[0]-n[0]*x[2],n[0]*x[1]-n[1]*x[0]],o=leg.frame.ground.map((v,i)=>v-.04*y[i]),p=this.project(o),A=this.vector(x),B=this.vector(y),rx=.073+Math.min(.025,leg.lift*.25),ry=.132+Math.min(.04,leg.lift*.4),det=A[0]*B[1]-A[1]*B[0];const anchor=leg.frame.ground,key=anchor.join(',');let cache=this.groundCaches.get(leg.side);if(!cache||cache.key!==key){const F=this.camera.camera.forward;cache={key,sample:{worldFootM:[...anchor],footPx:this.project(anchor),footDepthM:this.camera.camera.depthOriginM+anchor[0]*F[0]+anchor[1]*F[1]+anchor[2]*F[2]},pixels:new Map()};this.groundCaches.set(leg.side,cache);}return{o,p,x,y,A,B,rx,ry,det,cache,opacity:.32*Math.exp(-leg.lift/.060),side:leg.side,extent:[Math.abs(A[0]*rx)+Math.abs(B[0]*ry),Math.abs(A[1]*rx)+Math.abs(B[1]*ry)]};});
 const left=Math.floor(Math.min(...terms.map(t=>t.p[0]-t.extent[0]))*scale)-1,top=Math.floor(Math.min(...terms.map(t=>t.p[1]-t.extent[1]))*scale)-1,right=Math.ceil(Math.max(...terms.map(t=>t.p[0]+t.extent[0]))*scale)+1,bottom=Math.ceil(Math.max(...terms.map(t=>t.p[1]+t.extent[1]))*scale)+1,width=right-left,height=bottom-top,count=width*height;if(this.capacity<count){this.capacity=2**Math.ceil(Math.log2(count));this.data=new Uint8ClampedArray(this.capacity*4);}const data=this.data.subarray(0,count*4);data.fill(0);let clipped=0,visible=0;const f=this.camera.camera.forward,origin=this.camera.camera.depthOriginM,terrain=this.terrain;
 for(let py=0;py<height;py++)for(let px=0;px<width;px++){const atlasX=(left+px+.5)/scale,atlasY=(top+py+.5)/scale;let alpha=0;for(const t of terms){const dx=atlasX-t.p[0],dy=atlasY-t.p[1],u=(dx*t.B[1]-dy*t.B[0])/t.det,w=(dy*t.A[0]-dx*t.A[1])/t.det,r2=(u/t.rx)**2+(w/t.ry)**2;if(r2>=1)continue;let a=t.opacity*(Math.exp(-3*r2)-Math.exp(-3))/(1-Math.exp(-3));const wx=t.o[0]+u*t.x[0]+w*t.y[0],wy=t.o[1]+u*t.x[1]+w*t.y[1],wz=t.o[2]+u*t.x[2]+w*t.y[2],planeDepth=origin+wx*f[0]+wy*f[1]+wz*f[2];let depth=planeDepth;if(terrain){const key=atlasX+','+atlasY;let ground;if(t.cache.pixels.has(key))ground=t.cache.pixels.get(key);else{ground=this.supportAtPixel(t.cache.sample,atlasX,atlasY);if(t.cache.pixels.size>=4096)t.cache.pixels.clear();t.cache.pixels.set(key,ground);}if(!ground){clipped++;continue;}depth=ground.footDepthM;const tx=Math.floor(atlasX),ty=Math.floor(atlasY);if(tx<0||ty<0||tx>=terrain.width||ty>=terrain.height)continue;const ti=(ty*terrain.width+tx)*4;if(!terrain.data[ti+3])continue;const scene=terrain.nearM+((terrain.data[ti]*256+terrain.data[ti+1])/65535)*(terrain.farM-terrain.nearM);if(terrain.data[ti+2]&&depth>scene+depthBiasM){clipped++;continue;}}alpha=1-(1-alpha)*(1-a);}const i=(py*width+px)*4;if(alpha>0){data[i]=5;data[i+1]=15;data[i+2]=10;data[i+3]=Math.round(alpha*255);if(data[i+3])visible++;}}
 return{width,height,data,scale,originPx:[left/scale,top/scale],stats:{visible,clipped,centers:terms.map(t=>({side:t.side,worldM:t.o,atlasPx:t.p,opacity:t.opacity}))}};
 }
}
