// Presentation-only world-foot controller. It cannot dispatch a game interaction.
export const RIG=Object.freeze({heightM:1.66,thighM:.395,shinM:.380,hipHalfM:.081,footHalfM:.077,ankleM:.085,strideM:.86,stepM:.43});
export const v={add:(a,b)=>a.map((x,i)=>x+b[i]),sub:(a,b)=>a.map((x,i)=>x-b[i]),mul:(a,k)=>a.map(x=>x*k),dot:(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),len:a=>Math.hypot(...a),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]};
v.unit=a=>v.mul(a,1/(v.len(a)||1));v.mix=(a,b,t)=>a.map((x,i)=>x+(b[i]-x)*t);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),smooth=t=>t*t*(3-2*t),angleDelta=(a,b)=>Math.atan2(Math.sin(b-a),Math.cos(b-a));
const forward=yaw=>[Math.sin(yaw),-Math.cos(yaw),0],right=yaw=>[Math.cos(yaw),Math.sin(yaw),0];
export function twoBone(hip,ankle,l1=RIG.thighM,l2=RIG.shinM,hint=[0,-1,0]){const d=v.sub(ankle,hip),n=v.len(d);if(n>l1+l2+1e-7)throw Error(`Fixed bone reach exceeded: ${n}`);const axis=v.unit(d),along=(l1*l1-l2*l2+n*n)/(2*n),height=Math.sqrt(Math.max(0,l1*l1-along*along)),bend=v.unit(v.sub(hint,v.mul(axis,v.dot(hint,axis))));return v.add(v.add(hip,v.mul(axis,along)),v.mul(bend,height));}
export function groundFrame(at,support){const c=support(at),px=support(v.add(at,[.008,0,0])),py=support(v.add(at,[0,.008,0]));if(!c||!px||!py)throw Error('Missing authorized ground support');const sx=(px.worldFootM[2]-c.worldFootM[2])/.008,sy=(py.worldFootM[2]-c.worldFootM[2])/.008;return {origin:[...c.worldFootM],normal:v.unit([-sx,-sy,1]),slope:[sx,sy]};}
export function footFrame(center,yaw,roll=0,lift=0,support){const g=groundFrame(center,support),bx=v.unit(v.sub(right(yaw),v.mul(g.normal,v.dot(right(yaw),g.normal)))),by=v.unit(v.cross(g.normal,bx)),c=Math.cos(roll),s=Math.sin(roll),pivot=roll>=0?.057:-.148;const origin=v.add(v.add(g.origin,[0,0,lift]),v.add(v.mul(by,pivot*(1-c)),v.mul(g.normal,pivot*s)));return {origin,x:bx,y:v.sub(v.mul(by,c),v.mul(g.normal,s)),z:v.add(v.mul(by,s),v.mul(g.normal,c)),ground:g.origin,normal:g.normal};}
export function transformPoint(frame,p){return v.add(frame.origin,v.add(v.mul(frame.x,p[0]),v.add(v.mul(frame.y,p[1]),v.mul(frame.z,p[2]))));}
export function boneFrame(a,b,lateral=[1,0,0]){const z=v.unit(v.sub(b,a));let x=v.sub(lateral,v.mul(z,v.dot(lateral,z)));if(v.len(x)<1e-5)x=v.cross(z,[0,0,1]);x=v.unit(x);return {origin:a,x,y:v.unit(v.cross(z,x)),z};}
export function inversePoint(frame,p){const d=v.sub(p,frame.origin);return [v.dot(d,frame.x),v.dot(d,frame.y),v.dot(d,frame.z)];}

export class WorldGait {
 constructor({support,canPlace=()=>true}={}){if(!support)throw Error('Native support callback required');this.support=support;this.canPlace=canPlace;this.state=null;this.stats={ignoredStale:0,placementFallbacks:0};}
 footClear(center,yaw,roll=0,lift=0){try{const f=footFrame(center,yaw,roll,lift,this.support);return [[0,.057],[-.04,-.05],[.04,-.05],[-.027,-.148],[.027,-.148],[0,0]].every(q=>{const p=transformPoint(f,[...q,0]);return this.support(p)&&this.canPlace(p);});}catch{return false;}}
 pathLength(nodes){let length=0;for(let i=1;i<nodes.length;i++)length+=v.len(v.sub(nodes[i].center,nodes[i-1].center))+.12*Math.abs(angleDelta(nodes[i-1].yaw,nodes[i].yaw));return length;}
 pathPoint(nodes,u){const total=this.pathLength(nodes);let target=total*u;for(let i=1;i<nodes.length;i++){const a=nodes[i-1],b=nodes[i],length=v.len(v.sub(b.center,a.center))+.12*Math.abs(angleDelta(a.yaw,b.yaw));if(target<=length||i===nodes.length-1){const t=length?clamp(target/length,0,1):1;return {center:v.mix(a.center,b.center,t),yaw:a.yaw+angleDelta(a.yaw,b.yaw)*t};}target-=length;}return nodes.at(-1);}
 clearPath(nodes,startRoll=0,endRoll=.16,startLift=0){const n=Math.max(4,Math.ceil(this.pathLength(nodes)/.022));for(let i=0;i<=n;i++){const u=i/n,q=this.pathPoint(nodes,smooth(u)),lift=Math.min(.10,startLift*(1-smooth(u))+.065*Math.sin(Math.PI*u)**1.3);if(!this.footClear(q.center,q.yaw,startRoll*(1-u)+endRoll*u,lift))return false;}return true;}
 planPath(foot,end,endYaw,endRoll=.16){const s=this.state,start={center:[...foot.center],yaw:foot.yaw},finish={center:end,yaw:endYaw};let path=[start,finish];if(this.clearPath(path,foot.roll,endRoll,foot.lift))return {path,end,endYaw,endRoll,fallback:false};
  // Accepted root samples are already protected by the unchanged body collider.
  // Keep the old foot orientation until it reaches that corridor, then turn within it.
  const trail=s.rootTrail??[s.rootM];let nearest=0;for(let i=1;i<trail.length;i++)if(v.len(v.sub(trail[i],foot.center))<v.len(v.sub(trail[nearest],foot.center)))nearest=i;
  const via=trail.slice(nearest).filter((_,i,a)=>i===0||i===a.length-1||i%3===0);const corridor=via.map((center,i)=>({center:[...center],yaw:i===0?foot.yaw:foot.yaw+angleDelta(foot.yaw,endYaw)*i/Math.max(1,via.length-1)}));
  path=[start,...corridor,{center:[...s.rootM],yaw:endYaw},finish];if(this.clearPath(path,foot.roll,endRoll,foot.lift))return {path,end,endYaw,endRoll,fallback:true};
  const F=forward(s.targetYaw),X=right(s.targetYaw);for(const advance of [.13,.08,.03,0]){const wanted=v.add(s.rootM,v.add(v.mul(F,advance),v.mul(X,foot.side*.055)));let near;try{near=this.place(wanted,endYaw,s.rootM,foot.side);}catch{continue;}path=[start,...corridor,{center:[...s.rootM],yaw:endYaw},{center:near,yaw:endYaw}];if(this.clearPath(path,foot.roll,0,foot.lift))return {path,end:near,endYaw,endRoll:0,fallback:true,short:true};}
  throw Error('No safe visual swing corridor; original navigation remains unchanged');
 }
 place(wanted,yaw,root,side){const f=forward(yaw),r=right(yaw);const choices=[wanted];for(const behind of [.06,.12,.20,.28,.36])for(const lateral of [0,.025,-.025])choices.push(v.add(wanted,v.add(v.mul(f,-behind),v.mul(r,lateral))));choices.push(v.add(root,v.mul(r,side*RIG.footHalfM)),v.add(root,v.mul(r,side*.055)));
  for(const c of choices){const g=this.support(c);if(!g)continue;const points=[[0,.057],[-.04,-.05],[.04,-.05],[-.027,-.148],[.027,-.148]].map(([x,y])=>v.add(g.worldFootM,v.add(v.mul(r,x),v.mul(f,-y))));if(this.footClear(g.worldFootM,yaw)){if(c!==wanted)this.stats.placementFallbacks++;return [...g.worldFootM];}}
  throw Error('No legal visual foot support near accepted root; gameplay collision is not altered');
 }
 reset({sceneToken,rootM,yaw=0,reason='load'}){if(!sceneToken)throw Error('Explicit scene generation token required');const f=forward(yaw),r=right(yaw);this.state={sceneToken,rootM:[...rootM],yaw,targetYaw:yaw,travelM:0,phase:0,mode:'idle',moving:false,paused:false,armAmount:0,clock:0,active:null,waitDistance:0,nextSide:-1,firstStep:true,resetReason:reason,rootTrail:[[...rootM]]};this.state.feet=[-1,1].map(side=>({side,center:this.place(v.add(rootM,v.add(v.mul(r,side*RIG.footHalfM),v.mul(f,side*.045))),yaw,rootM,side),yaw,roll:0,lift:0,stance:true,stage:'plant'}));return this.pose();}
 beginStep(side,{distance=.43,duration=null,target=null,mode='walk',age=0,endYaw=null}={}){const s=this.state,foot=s.feet.find(q=>q.side===side),f=forward(s.targetYaw),r=right(s.targetYaw);const wanted=target??v.add(s.rootM,v.add(v.mul(f,distance+.215),v.mul(r,side*RIG.footHalfM)));let yaw=endYaw??foot.yaw+clamp(angleDelta(foot.yaw,s.targetYaw),-Math.PI/2,Math.PI/2);let end=this.place(wanted,yaw,s.rootM,side);const planned=this.planPath(foot,end,yaw,mode.startsWith('walk')?.16:0);end=planned.end;yaw=planned.endYaw;if(planned.short){duration=Math.max(.16,this.pathLength(planned.path)/3.0);distance=0;mode='walk-recovery';}foot.stance=false;foot.stage=mode;s.active={side,start:[...foot.center],end,startYaw:foot.yaw,endYaw:yaw,progress:0,distance,duration,mode,startLift:foot.lift,startRoll:foot.roll,path:planned.path,age,endRoll:planned.endRoll};s.mode=mode;}

 beginStop(){const s=this.state;s.moving=false;if(s.active){const foot=s.feet.find(q=>q.side===s.active.side),other=s.feet.find(q=>q.side!==foot.side),f=forward(s.targetYaw),r=right(s.targetYaw),rel=v.dot(v.sub(foot.center,s.rootM),f),otherRel=v.dot(v.sub(other.center,s.rootM),f);const targetRel=Math.max(rel+.025,clamp(-otherRel,-.07,.10));const target=v.add(s.rootM,v.add(v.mul(f,targetRel),v.mul(r,foot.side*RIG.footHalfM)));this.beginStep(foot.side,{target,duration:.22,distance:0,mode:'settle'});}else this.finishStop();}
 finishStop(){const s=this.state,f=forward(s.targetYaw);const positions=s.feet.map(q=>({q,along:v.dot(v.sub(q.center,s.rootM),f)})).sort((a,b)=>a.along-b.along);if(positions[1].along-positions[0].along>.285){const trailing=positions[0].q;const goal=v.add(s.rootM,v.add(v.mul(f,Math.max(-.055,positions[1].along-.265)),v.mul(right(s.targetYaw),trailing.side*RIG.footHalfM)));this.beginStep(trailing.side,{target:goal,duration:.22,distance:0,mode:'settle-rear'});}else{s.mode='idle';s.active=null;s.feet.forEach(q=>{q.stance=true;q.lift=0;q.roll=0;});}}
 advanceActive(delta,dt){const s=this.state,a=s.active;if(!a)return;const foot=s.feet.find(q=>q.side===a.side);a.progress=clamp(a.progress+(a.duration?dt/a.duration:delta/a.distance),0,1);const u=a.progress,e=smooth(u),sample=this.pathPoint(a.path,e);a.age+=dt;foot.center=sample.center;foot.yaw=sample.yaw;foot.roll=a.startRoll*(1-u)+a.endRoll*u;
  foot.lift=a.mode.startsWith('walk')?Math.min(.10,a.startLift*(1-e)+.065*Math.sin(Math.PI*u)**1.3):a.startLift*(2*u*u*u-3*u*u+1)+.035*Math.sin(Math.PI*u)**2;
  if(u>=1){foot.center=[...a.end];foot.lift=0;foot.stance=true;foot.stage='plant';s.active=null;if(s.moving){s.nextSide=-a.side;s.waitDistance=.035;}else if(a.mode==='pivot'){s.mode='idle';}else this.finishStop();}
 }
 update({sceneToken,rootM,moving=false,yaw,paused=false,dt=1/60}={}){const s=this.state;if(!s)throw Error('Call reset with the authoritative world scene first');if(sceneToken!==s.sceneToken){this.stats.ignoredStale++;return this.pose();}if(paused){s.paused=true;return this.pose();}s.paused=false;dt=clamp(dt,0,.1);const delta=v.sub(rootM,s.rootM),distance=v.len(delta);if(distance>1.5)throw Error('Teleport/load must explicitly reset world feet');const oldHeading=s.targetYaw;if(yaw!==undefined)s.targetYaw=yaw;else if(Math.hypot(delta[0],delta[1])>1e-8)s.targetYaw=Math.atan2(delta[0],-delta[1]);
  // A reversed accepted path invalidates the old predicted landing, not the planted anchors.
  // Retarget only the airborne foot from its current position/lift and shorten the remaining step.
  if(moving&&s.moving&&Math.abs(angleDelta(oldHeading,s.targetYaw))>Math.PI/3){const side=s.active?.side??[...s.feet].sort((a,b)=>v.dot(v.sub(a.center,rootM),forward(s.targetYaw))-v.dot(v.sub(b.center,rootM),forward(s.targetYaw)))[0].side,foot=s.feet.find(q=>q.side===side),age=s.active?.mode==='walk-turn'?s.active.age:0;let target=v.add(rootM,v.add(v.mul(forward(s.targetYaw),.24),v.mul(right(s.targetYaw),side*RIG.footHalfM))),endYaw=foot.yaw+clamp(angleDelta(foot.yaw,s.targetYaw),-Math.PI/2,Math.PI/2);if(age>.30){target=[...foot.center];endYaw=foot.yaw;}const length=v.len(v.sub(target,foot.center)),duration=Math.max(.16,1.5*length/3.5,Math.abs(angleDelta(foot.yaw,endYaw))/12);this.beginStep(side,{target,duration,distance:0,mode:'walk-turn',age,endYaw});s.waitDistance=0;}

  const steps=Math.max(1,Math.ceil(distance/.025)),from=[...s.rootM];for(let k=0;k<steps;k++){const dd=distance/steps,tt=dt/steps;s.rootM=v.mix(from,rootM,(k+1)/steps);if(dd>1e-9){s.rootTrail.push([...s.rootM]);if(s.rootTrail.length>70)s.rootTrail.shift();}s.yaw+=clamp(angleDelta(s.yaw,s.targetYaw),-5*tt,5*tt);s.clock+=tt;s.travelM+=dd;s.phase=(s.travelM/RIG.strideM)%1;
   for(const foot of s.feet)if(foot.stance){const along=v.dot(v.sub(foot.center,s.rootM),forward(foot.yaw));foot.roll=moving?(along>.14?.16*clamp((along-.14)/.075,0,1):(along<-.13?-.25*clamp((-along-.13)/.14,0,1):0)):foot.roll*Math.exp(-tt/.07);}
   if(moving){if(!s.moving){s.moving=true;s.mode='walk';if(!s.active){this.beginStep(s.nextSide,{distance:s.firstStep?.20:RIG.stepM});s.firstStep=false;}}if(!s.active){s.waitDistance-=dd;if(s.waitDistance<=0)this.beginStep(s.nextSide,{distance:RIG.stepM});}this.advanceActive(dd,tt);}
   else{if(s.moving)this.beginStop();this.advanceActive(0,tt);if(!s.active&&Math.abs(angleDelta(s.feet[0].yaw,s.targetYaw))+Math.abs(angleDelta(s.feet[1].yaw,s.targetYaw))>.45){const foot=[...s.feet].sort((a,b)=>Math.abs(angleDelta(b.yaw,s.targetYaw))-Math.abs(angleDelta(a.yaw,s.targetYaw)))[0];const target=v.add(s.rootM,v.add(v.mul(right(s.targetYaw),foot.side*RIG.footHalfM),v.mul(forward(s.targetYaw),foot.side*.04)));this.beginStep(foot.side,{target,duration:.22,distance:0,mode:'pivot'});}}
   s.armAmount+=(Number(moving)-s.armAmount)*(1-Math.exp(-tt/.11));
  }return this.pose();
 }
 pose(){const s=this.state;if(!s)return null;const F=forward(s.yaw),X=right(s.yaw),phase=s.phase,sway=.008*Math.sin(Math.PI*2*phase)*s.armAmount;const feet=s.feet.map(q=>{const frame=footFrame(q.center,q.yaw,q.roll,q.lift,this.support);return {...q,center:[...q.center],frame,ankle:transformPoint(frame,[0,0,RIG.ankleM])};});
  let hipZ=Infinity;for(const q of feet){const hipXY=v.add(s.rootM,v.mul(X,q.side*RIG.hipHalfM+sway));const dx=q.ankle[0]-hipXY[0],dy=q.ankle[1]-hipXY[1];const reach=RIG.thighM+RIG.shinM-.010;if(dx*dx+dy*dy>=reach*reach)throw Error('Foot target outside fixed-leg horizontal reach');hipZ=Math.min(hipZ,q.ankle[2]+Math.sqrt(reach*reach-dx*dx-dy*dy));}
  const legs=feet.map(q=>{const hip=v.add(s.rootM,v.mul(X,q.side*RIG.hipHalfM+sway));hip[2]=hipZ;return {...q,hip,knee:twoBone(hip,q.ankle,RIG.thighM,RIG.shinM,F)};});const bob=hipZ-s.rootM[2]-.82,twist=-.055*Math.sin(Math.PI*2*phase)*s.armAmount;
  const arms=[-1,1].map(side=>{const a=Math.PI*2*(phase+(side===1?0:.5)),swing=-.9*clamp(v.dot(v.sub(feet.find(q=>q.side===side).center,s.rootM),F),-.27,.27)*s.armAmount,shoulder=v.add(v.add(s.rootM,v.mul(X,side*.163+sway)),v.add(v.mul(F,-side*twist*.16),[0,0,1.293+bob])),elbow=v.add(shoulder,v.add(v.mul(X,side*.042),v.add(v.mul(F,Math.sin(swing)*.244),[0,0,-Math.cos(swing)*.244]))),wrist=v.add(elbow,v.add(v.mul(X,side*.011),v.add(v.mul(F,Math.sin(swing+.16)*.214),[0,0,-Math.cos(swing+.16)*.214])));return {side,shoulder,elbow,wrist};});
  return {sceneToken:s.sceneToken,rootM:[...s.rootM],yaw:s.yaw,phase:s.phase,travelM:s.travelM,mode:s.mode,paused:s.paused,armAmount:s.armAmount,bob,sway,twist,clock:s.clock,legs,arms,forward:F,right:X,contacts:s.feet.map(q=>({side:q.side,stance:q.stance,center:[...q.center]}))};
 }
}
