import{v,boneFrame,footFrame,inversePoint,transformPoint}from'./gait-runtime.mjs';
const linear=Float32Array.from({length:256},(_,i)=>{const x=i/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;});
const srgb=Uint8Array.from({length:4096},(_,i)=>{const x=i/4095;return Math.round(255*(x<=.0031308?x*12.92:1.055*x**(1/2.4)-.055));});
const rgb=x=>srgb[Math.min(4095,Math.max(0,Math.round(x*4095)))];
function frameFor(kind,side,pose,support){const l=pose.legs.find(q=>q.side===side),a=(pose.arms??pose.hands).find(q=>q.side===side),X=pose.right??[1,0,0];switch(kind){case'foot':return l.frame??footFrame(l.footCenterM,0,l.roll,l.lift,support);case'thigh':return boneFrame(l.hip,l.knee,X);case'shin':case'knee':return boneFrame(l.knee,l.ankle,X);case'upperarm':return boneFrame(a.shoulder,a.elbow,X);case'forearm':case'elbow':return boneFrame(a.elbow,a.wrist,X);case'hand':return boneFrame(a.wrist,v.add(a.wrist,v.sub(a.wrist,a.elbow)),X);default:return null;}}
const matApply=(f,p)=>[f.x[0]*p[0]+f.y[0]*p[1]+f.z[0]*p[2],f.x[1]*p[0]+f.y[1]*p[1]+f.z[1]*p[2],f.x[2]*p[0]+f.y[2]*p[1]+f.z[2]*p[2]];
export class SoftwareHero {
 constructor(model,{camera,texture,terrainDepth=null}={}){this.model=model;this.camera=camera;this.texture=texture;this.terrainDepth=terrainDepth;this.n=model.positions.length/3;this.local=new Float32Array(this.n*3);this.localNormal=new Float32Array(this.n*3);this.world=new Float32Array(this.n*3);this.normal=new Float32Array(this.n*3);this.projected=new Float32Array(this.n*4);this.shade=new Float32Array(this.n);this.indices=Uint32Array.from(model.triangles);this.uv=Float32Array.from(model.uvs);this.vparts=Uint16Array.from(model.partIds);this.vmats=Uint16Array.from(model.materialIds);this.rest=model.restPose;this.restBob=this.rest.pelvisHeightM-.82;const [sx,sy]=this.rest.canonicalGroundSlope;const support=p=>({worldFootM:[p[0],p[1],sx*p[0]+sy*p[1]]});
  this.parts=model.parts.map(q=>({...q,restFrame:frameFor(q.kind,q.side,this.rest,support),offset:Number(q.name.match(/(\d+)(?:\.\d+)?$/)?.[1]??0)*.31}));
  // Frame slots are stable for this immutable mesh; refresh values without per-frame Maps.
  const slots=new Map();this.frameParts=[];this.frameSlot=new Uint16Array(this.parts.length);this.frames=[];
  for(let k=0;k<this.parts.length;k++){const q=this.parts[k],key=q.kind+q.side;if(!slots.has(key)){slots.set(key,this.frameParts.length);this.frameParts.push(q);}this.frameSlot[k]=slots.get(key);q.restHairSin=Math.sin(-.9+q.offset);}
  for(let i=0;i<this.n;i++){const p=model.positions.slice(i*3,i*3+3),n=model.normals.slice(i*3,i*3+3),part=this.parts[this.vparts[i]];let lp,ln;if(part.restFrame){lp=inversePoint(part.restFrame,p);ln=[v.dot(n,part.restFrame.x),v.dot(n,part.restFrame.y),v.dot(n,part.restFrame.z)];}else{lp=[p[0],p[1],p[2]-this.restBob];ln=n;}this.local.set(lp,i*3);this.localNormal.set(ln,i*3);}
 }
 skin(pose){const frames=this.frames;for(let k=0;k<this.frameParts.length;k++){const q=this.frameParts[k];frames[k]=frameFor(q.kind,q.side,pose);}const c=Math.cos(pose.yaw),s=Math.sin(pose.yaw),bodyYaw=pose.yaw+pose.twist,pelvisYaw=pose.yaw+.045*Math.sin(Math.PI*2*pose.phase)*pose.armAmount;const cache=[bodyYaw,pelvisYaw].map(a=>[Math.cos(a),Math.sin(a)]),phase=pose.phase*Math.PI*2;
  const hairSin=Math.sin(phase-.4),capeWave=Math.sin(phase-.55)*pose.armAmount-Math.sin(-.55);
  for(const part of this.parts)if(part.kind==='hair')part.hairWave=Math.sin(phase-.9+part.offset)*pose.armAmount-part.restHairSin;
  for(let i=0;i<this.n;i++){const j=i*3,k=this.vparts[i],part=this.parts[k],f=frames[this.frameSlot[k]];let x=this.local[j],y=this.local[j+1],z=this.local[j+2],nx=this.localNormal[j],ny=this.localNormal[j+1],nz=this.localNormal[j+2];if(f){this.world[j]=f.origin[0]+f.x[0]*x+f.y[0]*y+f.z[0]*z;this.world[j+1]=f.origin[1]+f.x[1]*x+f.y[1]*y+f.z[1]*z;this.world[j+2]=f.origin[2]+f.x[2]*x+f.y[2]*y+f.z[2]*z;this.normal[j]=f.x[0]*nx+f.y[0]*ny+f.z[0]*nz;this.normal[j+1]=f.x[1]*nx+f.y[1]*ny+f.z[1]*nz;this.normal[j+2]=f.x[2]*nx+f.y[2]*ny+f.z[2]*nz;}else{const pelvic=part.kind==='pelvis'||part.kind==='cape',[cc,ss]=cache[pelvic?1:0];if(part.kind==='hair'){const w=Math.max(0,Math.min(1,(1.56-z)/.75));x+=.014*w*part.hairWave;y+=.006*w*hairSin*pose.armAmount;}if(part.kind==='cape'){const w=Math.max(0,Math.min(1,(1-z)/.7));y+=.025*w*capeWave;}this.world[j]=pose.rootM[0]+cc*x-ss*y+c*pose.sway;this.world[j+1]=pose.rootM[1]+ss*x+cc*y+s*pose.sway;this.world[j+2]=pose.rootM[2]+z+pose.bob;this.normal[j]=cc*nx-ss*ny;this.normal[j+1]=ss*nx+cc*ny;this.normal[j+2]=nz;}}
  return this.world;
 }
 render(pose,{scale=1,depthBiasM=.015}={}){const t0=performance.now();this.skin(pose);const t1=performance.now(),aff=this.camera.affine,F=this.camera.camera.forward,depth0=this.camera.camera.depthOriginM;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(let i=0;i<this.n;i++){const j=i*3,k=i*4,x=this.world[j],y=this.world[j+1],z=this.world[j+2],px=aff.origin_px[0]+x*aff.x_m[0]+y*aff.y_m[0]+z*aff.z_m[0],py=aff.origin_px[1]+x*aff.x_m[1]+y*aff.y_m[1]+z*aff.z_m[1];this.projected[k]=px*scale;this.projected[k+1]=py*scale;this.projected[k+2]=depth0+x*F[0]+y*F[1]+z*F[2];minX=Math.min(minX,px*scale);maxX=Math.max(maxX,px*scale);minY=Math.min(minY,py*scale);maxY=Math.max(maxY,py*scale);const nx=this.normal[j],ny=this.normal[j+1],nz=this.normal[j+2];this.shade[i]=.70+.29*Math.max(0,nx*-.366+ny*-.488+nz*.793)+.08*Math.max(0,nx*.7+ny*.2+nz*.55);}
  const ox=Math.floor(minX)-2,oy=Math.floor(minY)-2,W=Math.ceil(maxX)-ox+3,H=Math.ceil(maxY)-oy+3;if(W*H>1600000)throw Error('Actor raster bounds exceeded');const needed=W*H;if(needed>(this.capacity??0)){this.capacity=2**Math.ceil(Math.log2(needed));this.pixelBuffer=new Uint8ClampedArray(this.capacity*4);this.depthBuffer=new Float32Array(this.capacity);this.ownerBuffer=new Uint16Array(this.capacity);this.baryU=new Float32Array(this.capacity);this.baryV=new Float32Array(this.capacity);this.terrainBuffer=new Float64Array(this.capacity);}this.ownerBuffer.fill(0,0,needed);this.pixelBuffer.fill(0,0,needed*4);this.depthBuffer.fill(Infinity,0,needed);const data=this.pixelBuffer.subarray(0,needed*4),depth=this.depthBuffer.subarray(0,needed),p=this.projected,T=this.texture,terrain=this.terrainDepth;let fragments=0,occluded=0,painted=0;
  // Decode each scene-depth sample once per actor tile, retaining the reference
  // double-precision expression and exact atlas pixel-center convention.
  const terrainZ=this.terrainBuffer;
  if(terrain){const td=terrain.data,tw=terrain.width,th=terrain.height,near=terrain.nearM,range=terrain.farM-near;for(let y=0;y<H;y++){const ty=Math.floor((oy+y+.5)/scale);for(let x=0;x<W;x++){const idx=y*W+x,tx=Math.floor((ox+x+.5)/scale);let tz=Infinity;if(tx>=0&&ty>=0&&tx<tw&&ty<th){const ti=(ty*tw+tx)*4;if(td[ti+2]&&td[ti+3])tz=near+(td[ti]*256+td[ti+1])/65535*range;}terrainZ[idx]=tz;}}}
  for(let it=0;it<this.indices.length;it+=3){const ia=this.indices[it],ib=this.indices[it+1],ic=this.indices[it+2],a=ia*4,b=ib*4,c=ic*4,ax=p[a]-ox,ay=p[a+1]-oy,bx=p[b]-ox,by=p[b+1]-oy,cx=p[c]-ox,cy=p[c+1]-oy,den=(by-cy)*(ax-cx)+(cx-bx)*(ay-cy);if(Math.abs(den)<.005)continue;const x0=Math.max(0,Math.floor(Math.min(ax,bx,cx))),x1=Math.min(W-1,Math.ceil(Math.max(ax,bx,cx))),y0=Math.max(0,Math.floor(Math.min(ay,by,cy))),y1=Math.min(H-1,Math.ceil(Math.max(ay,by,cy)));
   const bcY=by-cy,cbX=cx-bx,caY=cy-ay,acX=ax-cx,az=p[a+2],bz=p[b+2],cz=p[c+2];
   for(let y=y0;y<=y1;y++){let edgeU=bcY*(x0+.5-cx)+cbX*(y+.5-cy),edgeV=caY*(x0+.5-cx)+acX*(y+.5-cy);const row=y*W;for(let x=x0;x<=x1;x++,edgeU+=bcY,edgeV+=caY){const u=edgeU/den,w=edgeV/den,h=1-u-w;if(u<-.000001||w<-.000001||h<-.000001)continue;fragments++;const z=u*az+w*bz+h*cz,idx=row+x;if(z>=depth[idx])continue;
    if(terrain&&terrainZ[idx]<z-depthBiasM){occluded++;continue;}
    this.ownerBuffer[idx]=it/3+1;this.baryU[idx]=u;this.baryV[idx]=w;depth[idx]=z;painted++;
   }}
  }
  // Shade only the final visible surface at each pixel. Hidden surfaces are never re-shaded.
  for(let idx=0;idx<needed;idx++){const owner=this.ownerBuffer[idx];if(!owner)continue;const it=(owner-1)*3,ia=this.indices[it],ib=this.indices[it+1],ic=this.indices[it+2],u=this.baryU[idx],w=this.baryV[idx],h=1-u-w,m=this.model.materials[this.vmats[ia]];
    const light=u*this.shade[ia]+w*this.shade[ib]+h*this.shade[ic];let cr=m.linearColor[0],cg=m.linearColor[1],cb=m.linearColor[2];if(m.kind){const tu=u*this.uv[ia*2]+w*this.uv[ib*2]+h*this.uv[ic*2],tv=u*this.uv[ia*2+1]+w*this.uv[ib*2+1]+h*this.uv[ic*2+1],xx=Math.min(T.width-1,Math.max(0,Math.floor(tu*T.width))),yy=Math.min(T.height-1,Math.max(0,Math.floor((1-tv)*T.height))),ii=(yy*T.width+xx)*4;let r=linear[T.data[ii]],g=linear[T.data[ii+1]],b=linear[T.data[ii+2]];if(m.kind===2){const f=Math.min(1,Math.max(0,(.2126*r+.7152*g+.0722*b-.005)/.295));r=.012+.078*f;g=.018+.152*f;b=.06+.35*f;}cr=r;cg=g;cb=b;}const o=idx*4;data[o]=rgb(cr*light+.004);data[o+1]=rgb(cg*light+.004);data[o+2]=rgb(cb*light+.004);data[o+3]=255;
  }
  return {width:W,height:H,data,depth,originPx:[ox/scale,oy/scale],scale,pose,stats:{vertices:this.n,triangles:this.indices.length/3,fragments,painted,occluded,skinMs:t1-t0,totalMs:performance.now()-t0}};
 }
}
