import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {createOpeningPresentation,withoutReplacedOpening} from '../src/opening/presentation.js';
import {openingPortrait,OPENING_PORTRAITS} from '../src/opening/portraits.js';
import {mountOpening} from '../src/opening/ui.js';
import {startOpeningPrelude} from '../src/opening/prelude.js';
// Self-contained fixture is copied, with no sibling project dependency.
import {documentMock} from './helpers/dom-mock.js';
const opening=JSON.parse(fs.readFileSync(new URL('../public/opening/opening.json',import.meta.url)));
const turns=opening.scenes.flatMap(s=>s.turns),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
test('opening bytes and all 52 exact text turns remain sealed',()=>{assert.equal(hash(fs.readFileSync(new URL('../public/opening/opening.json',import.meta.url))),'32d1e063c5595fd4d8fe1d747e2150f5fe77931a1cb716a7bc23f05c36259d71');assert.equal(turns.length,52);});
test('all 52 DOM turns have exact speaker/text and only actual accepted speaker portraits',()=>{const c=createOpeningPresentation(opening),doc=documentMock(),root=doc.getElementById('opening-root');mountOpening(root,c);let faces=0;for(const [i,t]of turns.entries()){assert.equal(root.all().find(n=>n.attrs['data-story-text']).textContent,t.text);assert.ok(root.text.includes(t.speaker));const images=root.all().filter(n=>n.tagName==='img');if(t.speaker==='旁白')assert.equal(images.length,0);else{assert.equal(images.length,1);assert.equal(images[0].attrs['data-character-id'],t.speaker==='璃'?'hero':'merchant');assert.match(images[0].src,/assets\/portraits\//);faces++;}if(i<51)root.find('下一句').onclick();}assert.equal(faces,36);assert.equal(c.blocked(),true);root.find('读完，进入实际码头').onclick();assert.equal(c.blocked(),false);});
test('all presentation interruptions, stale callbacks, repeated finish and snapshot isolation are harmless',()=>{const c=createOpeningPresentation(opening),doc=documentMock(),root=doc.getElementById('opening-root');mountOpening(root,c);const next=root.find('下一句');next.onclick();next.onclick();assert.equal(c.snapshot().index,1);root.find('关闭阅读').onclick();assert.equal(c.blocked(),true);assert.equal(root.find('下一句'),undefined);root.find('继续阅读').onclick();assert.equal(c.snapshot().index,1);root.find('跳至结尾（不确认作业）').onclick();const finish=root.find('读完，进入实际码头');finish.onclick();finish.onclick();assert.equal(c.blocked(),false);const v=c.snapshot();v.finished=false;v.turn.text='mutated';assert.notEqual(c.snapshot().turn.text,'mutated');assert.equal(c.replacesOriginalOpening(),true);c.present('reopen');assert.equal(c.blocked(),true);c.present('back');c.present('close');assert.equal(c.blocked(),false);});
test('unknown, narration, mismatched speaker, stage-suppressed and offscreen voices cannot acquire portraits',()=>{const known=turns.find(t=>t.speaker==='璃');for(const bad of [{...known,speaker:'旁白'},{...known,speaker:'纱雾'},{...known,id:'unverified'},{...known,offscreen:true},{...known,voiceOnly:true},{...known,stage:{portraitAllowed:false}},{...known,stage:{offscreen:true}},{...known,stage:{presence:'voice'}},{...known,delivery:'voice-only'}])assert.equal(openingPortrait(bad),null);for(const t of turns.filter(t=>t.speaker==='旁白'))assert.equal(openingPortrait(t),null);});
test('missing image fallback does not block, change text or retain stale speaker portrait',()=>{const c=createOpeningPresentation(opening),doc=documentMock(),root=doc.getElementById('opening-root');mountOpening(root,c);root.find('下一句').onclick();const img=root.all().find(n=>n.tagName==='img'),v=c.snapshot();img.onerror();assert.equal(img.hidden,true);assert.equal(img.parentElement.className,'opening-turn');assert.match(root.text,/珂珂的头像暂未载入/);assert.deepEqual(c.snapshot(),v);root.find('下一句').onclick();assert.equal(root.all().find(n=>n.tagName==='img').attrs['data-character-id'],'hero');img.onerror();assert.ok(root.text.includes(c.snapshot().turn.text));});
test('fresh modal startup never resolves when unfinished reading is closed; finish resolves exactly once',async()=>{const doc=documentMock(),root=doc.getElementById('opening-root');let completed=false;const task=startOpeningPrelude({document:doc,fetch:async()=>({ok:true,json:async()=>opening})}).then(g=>{completed=true;return g;});await new Promise(r=>setImmediate(r));assert.equal(completed,false);assert.equal(doc.getElementById('opening-dialog').open,true);root.find('关闭阅读').onclick();assert.equal(completed,false);assert.equal(doc.getElementById('opening-dialog').open,true);root.find('继续阅读').onclick();root.find('跳至结尾（不确认作业）').onclick();assert.equal(completed,false);root.find('读完，进入实际码头').onclick();const g=await task;assert.equal(g.blocked(),false);assert.equal(doc.getElementById('opening-dialog').open,false);doc.getElementById('opening-review').onclick();assert.equal(g.blocked(),true);doc.getElementById('opening-dialog').events.cancel.at(-1)({preventDefault(){}});assert.equal(g.blocked(),false);});
test('valid restore skips automatic flashback; optional review remains possible and startup failure does not lock old save',async()=>{const doc=documentMock();const gate=await startOpeningPrelude({document:doc,skip:true,fetch:async()=>({ok:true,json:async()=>opening})});assert.equal(doc.getElementById('opening-dialog').open,false);assert.equal(gate.blocked(),false);assert.equal(gate.replacesOriginalOpening(),false);doc.getElementById('opening-review').onclick();assert.equal(gate.blocked(),true);assert.equal(gate.snapshot().index,0);const bad=documentMock();const unavailable=await startOpeningPrelude({document:bad,skip:true,fetch:async()=>{throw Error('offline');}});assert.equal(unavailable.blocked(),false);assert.equal(bad.getElementById('opening-dialog').open,false);assert.equal(bad.getElementById('opening-review').disabled,true);});
test('navigation reconstruction keeps prelude state only in memory; a new fresh model starts at 1 without persistence',()=>{const c=createOpeningPresentation(opening);c.present('next');const doc=documentMock();mountOpening(doc.getElementById('opening-root'),c);assert.equal(c.snapshot().index,1);assert.equal(createOpeningPresentation(opening).snapshot().index,0);assert.equal(c.save,undefined);assert.equal(c.restore,undefined);});
test('runtime manifest contains exactly two actually bound and hash-verified images',()=>{const m=JSON.parse(fs.readFileSync(new URL('../public/opening/asset-manifest.json',import.meta.url)));assert.equal(m.assets.length,2);const used=new Set(turns.map(t=>openingPortrait(t)?.id).filter(Boolean));assert.deepEqual([...used].sort(),m.assets.map(x=>x.id).sort());for(const a of m.assets){assert.deepEqual(a,OPENING_PORTRAITS[a.id]);assert.equal(hash(fs.readFileSync(new URL('../public/'+a.file,import.meta.url))),a.sha256);}});
test('replacement filter removes only verified c01 scene, retains original c02 and sidecar/event facts',()=>{const result={scenes:[{sceneId:'c01'},{sceneId:'c02'},{sceneId:'c07'}],seenIds:['c01','c02'],narrativeConflicts:[]};assert.deepEqual(withoutReplacedOpening(result),{...result,scenes:[{sceneId:'c02'},{sceneId:'c07'}]});assert.equal(result.scenes.length,3);});

test('loading-time Escape cannot dismiss fresh gate; malformed optional opening does not block a restored game',async()=>{const doc=documentMock();let resolve;const response=new Promise(r=>{resolve=r;});const task=startOpeningPrelude({document:doc,fetch:()=>response});assert.equal(doc.getElementById('opening-dialog').open,true);let prevented=false;doc.getElementById('opening-dialog').events.cancel[0]({preventDefault(){prevented=true;}});assert.equal(prevented,true);resolve({ok:true,json:async()=>opening});await new Promise(r=>setImmediate(r));const root=doc.getElementById('opening-root');root.find('跳至结尾（不确认作业）').onclick();root.find('读完，进入实际码头').onclick();await task;const bad=documentMock();const g=await startOpeningPrelude({document:bad,skip:true,fetch:async()=>({ok:true,json:async()=>({id:'bad'})})});assert.equal(g.blocked(),false);assert.equal(bad.getElementById('opening-dialog').open,false);});
