import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {PROFILES} from '../src/profiles/registry.js';
import {createProfileRuntime} from '../src/profiles/runtime.js';
import {createVoyageSpec} from '../src/campaigns/c/content.js';
import {createVoyageStory} from '../src/campaigns/c/story/index.js';
import {createVoyagePlanning} from '../src/campaigns/c/planning.js';
import {supportsVoyageGeometry} from '../src/profiles/geometry.js';
import {buildViewModel} from '../src/rendering/c-three-model.js';
import {createCampaignAdapter} from '../src/solver/campaign-adapter.js';
import {certifyCampaignActions,replayCampaignCertificate} from '../src/solver/campaign-replay.js';
import {solve} from './helpers/frozen-search/search.js';
const cert=async(p,route)=>JSON.parse(await readFile(new URL(`../artifacts/profiles/${p.id}-${route}.certificate.json`,import.meta.url)));
for(const p of PROFILES){
 test(`${p.label}: complete spec lock permits only profile identity and two bounded ATK deltas`,()=>{const base=createVoyageSpec(),spec=structuredClone(createProfileRuntime(p.id).spec);spec.version=base.version;spec.difficulty=base.difficulty;for(const id of ['c.machine1','c.machine2'])spec.regions.flatMap(r=>r.entities).find(e=>e.id===id).enemy.atk-=p.delta;assert.deepEqual(spec,base);});
 test(`${p.label}: three route certificates preserve zero-fuel endings, story, planning and read-only renderer`,async()=>{const rt=createProfileRuntime(p.id),fuels=[];for(const route of ['c-normal','c-normal-bypass-short','c-normal-short-bypass']){const c=await cert(p,route),result=replayCampaignCertificate(rt,c);assert.equal(result.ok,true,result.reason);assert.equal(result.state.victory,true);fuels.push(result.state.resources.fuel);let state=rt.initialState(),seenIds=[];const story=createVoyageStory(rt),planning=createVoyagePlanning(rt);for(const step of c.steps){const before=rt.serialize(state);const model=buildViewModel(rt,state);assert.equal(model.geometryId,'C_FERRY_HULL_01');assert.equal(rt.serialize(state),before);const dispatched=rt.dispatch(state,step.action);const narrative=story.fromDispatch({stateBefore:state,stateAfter:dispatched.state,events:dispatched.events,receipt:dispatched.receipt,seenIds});seenIds=narrative.seenIds;assert.equal(narrative.narrativeConflicts?.length??0,0);state=dispatched.state;}for(const id of ['c.machine1','c.machine2'])assert.deepEqual(planning.enemyEstimate(state,id).enemy,rt.entity(id).enemy);}assert.deepEqual(fuels,[1,0,0]);});
 test(`${p.label}: frozen fresh-search certificate and independently rerun unseeded bounded search both replay`,async()=>{const rt=createProfileRuntime(p.id);assert.equal(replayCampaignCertificate(rt,await cert(p,'fresh-search')).ok,true);const found=solve({adapter:createCampaignAdapter(rt),mode:'existence',maxExpanded:100,maxGenerated:2500});assert.equal(found.solvable,true);const checked=certifyCampaignActions(rt,found.certificate.steps.map(s=>s.action),{source:'fresh-unseeded-integration-search',coverage:'witness'});assert.equal(checked.ok,true);const replay=replayCampaignCertificate(rt,checked.certificate);assert.equal(replay.ok,true);assert.equal(replay.state.stats.hp,29-p.delta*8);assert.equal(replay.claim,'existence-only');assert.equal(replay.steps,179);});
 test(`${p.label}: same winning actions do not authorize another profile certificate`,async()=>{const rt=createProfileRuntime(p.id);for(const other of PROFILES.filter(q=>q.id!==p.id))assert.equal(replayCampaignCertificate(rt,await cert(other,'c-normal')).ok,false);});
}
test('test-only generic solver bytes are pinned and are excluded from runtime build',async()=>{const manifest=JSON.parse(await readFile(new URL('./helpers/frozen-search/provenance.json',import.meta.url)));for(const [file,expected] of Object.entries(manifest.files)){const actual=createHash('sha256').update(await readFile(new URL('./helpers/frozen-search/'+file,import.meta.url))).digest('hex');assert.equal(actual,expected);}});
test('geometry whitelist requires whole identity and actual frozen geometry/spec; foreign and forged profiles fail closed',()=>{for(const p of PROFILES){const runtime=createProfileRuntime(p.id);assert.equal(supportsVoyageGeometry(runtime),true);const forged={...runtime,identity:{...runtime.identity,contentVersion:'future'}};assert.equal(supportsVoyageGeometry(forged),false);const spec=structuredClone(runtime.spec);spec.vesselGeometry.hull.length=8;assert.equal(supportsVoyageGeometry({...runtime,spec}),false);assert.throws(()=>buildViewModel(forged,runtime.initialState()));}});
test('2D/3D rendering formulas remain byte-identical after exact eligibility-gate normalization',async()=>{const records=JSON.parse(await readFile(new URL('../reports/profile-rendering-provenance.json',import.meta.url)));for(const r of records){let source=await readFile(new URL('../'+r.file,import.meta.url),'utf8');source=source.replace("import { supportsVoyageGeometry } from '../profiles/geometry.js';\n",'').replace('!supportsVoyageGeometry(runtime)',r.originalGate);assert.equal(createHash('sha256').update(source).digest('hex'),r.baselineSha256);}});
test('shallow-frozen facade cannot cache a mutable identity and admit a later unreviewed hash',()=>{const runtime=createProfileRuntime(PROFILES[0].id),identity={...runtime.identity},spoof=Object.freeze({...runtime,identity});assert.equal(supportsVoyageGeometry(spoof),true);identity.contentHash='unreviewed';assert.equal(supportsVoyageGeometry(spoof),false);assert.throws(()=>buildViewModel(spoof,runtime.initialState()),/content identity mismatch/);});
test('shallow-frozen spec cannot cache mutable nested geometry and admit a later hull change',()=>{const runtime=createProfileRuntime(PROFILES[0].id),spec=structuredClone(runtime.spec);Object.freeze(spec);const spoof=Object.freeze({...runtime,spec});assert.equal(supportsVoyageGeometry(spoof),true);spec.vesselGeometry.hull.length=8;assert.equal(supportsVoyageGeometry(spoof),false);assert.throws(()=>buildViewModel(spoof,runtime.initialState()),/content identity mismatch/);});
test('frozen runtime accessor must not cache mutable identity selection',()=>{const runtime=createProfileRuntime(PROFILES[0].id);let identity=runtime.identity;const spoof=Object.freeze({...runtime,get identity(){return identity;}});assert.equal(supportsVoyageGeometry(spoof),true);identity=Object.freeze({...runtime.identity,contentHash:'unreviewed'});assert.equal(supportsVoyageGeometry(spoof),false);});
test('frozen nested accessor must not cache mutable geometry selection',()=>{const runtime=createProfileRuntime(PROFILES[0].id),spec=structuredClone(runtime.spec);let hull=Object.freeze({...spec.vesselGeometry.hull});Object.defineProperty(spec.vesselGeometry,'hull',{get:()=>hull,enumerable:true,configurable:false});const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}};freeze(spec);const spoof=Object.freeze({...runtime,spec});assert.equal(supportsVoyageGeometry(spoof),true);hull=Object.freeze({...hull,length:8});assert.equal(supportsVoyageGeometry(spoof),false);});
