// Executes the real browser entry and real profile/opening/story/engine modules
// against a limited DOM/storage mock. Raster, WebGL, layout and navigation are
// explicitly stubbed: this is not browser or GPU acceptance evidence.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PROFILES} from '../src/profiles/registry.js';
import {createProfileRuntime} from '../src/profiles/runtime.js';
import {createProfileRepository} from '../src/profiles/persistence.js';
import {selectionUrl} from '../src/profiles/selection.js';
import {documentMock} from './helpers/dom-mock.js';
const entry=new URL('../public/campaigns/app.js',import.meta.url),root=new URL('../',import.meta.url),prefix='c3d-prototype:';
let count=0;
const next=()=>new Promise(resolve=>setImmediate(resolve));
async function until(fn){for(let i=0;i<400;i++){if(fn())return;await new Promise(resolve=>setTimeout(resolve,5));}assert.fail('Entry did not reach expected mocked UI state');}
async function fixture({url='https://example.invalid/c/campaigns/',seed=()=>{}}={}) {
 const doc=documentMock(),data=new Map(),assigned=[],timers=[],saved=new Map();let approved=true;
 const storage={get length(){return data.size;},key:i=>[...data.keys()][i]??null,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};
 const namespaced={get length(){return data.size;},key:i=>storage.key(i)?.slice(prefix.length),getItem:k=>storage.getItem(prefix+k),setItem:(k,v)=>storage.setItem(prefix+k,v),removeItem:k=>storage.removeItem(prefix+k)};
 seed(namespaced);doc.getElementById('profile-dialog').tagName='dialog';
 for(const id of ['profile-dialog','opening-dialog','story','confirmation']){const dialog=doc.getElementById(id);dialog.close=()=>{if(!dialog.open)return;dialog.open=false;for(const fn of dialog.events.close??[])fn({type:'close'});};}
 const win={location:{href:url,assign:value=>assigned.push(value)},history:{replaceState:(_,__,value)=>{win.location.href=value;}}};
 const originalTimeout=globalThis.setTimeout;
 for(const [key,value] of Object.entries({document:doc,window:win,localStorage:storage,confirm:()=>approved,fetch:async url=>({ok:true,json:async()=>JSON.parse(await readFile(String(url).endsWith('opening.json')?new URL('public/opening/opening.json',root):url))}),setTimeout:(fn,ms,...args)=>{const timer=originalTimeout(fn,ms,...args);timers.push(timer);return timer;}})){saved.set(key,globalThis[key]);globalThis[key]=value;}
 let source=await readFile(entry,'utf8');
 source=source.replace(/import \{ installViewportLayout \} from .*?;/,"const installViewportLayout=()=>({snapshot:()=>({mocked:true})});")
 .replace(/import \{ installThreeView \} from .*?;/,"const installThreeView=()=>({refresh(){},mode:()=> 'mocked-2d',stats:()=>null,projectTile:()=>null});")
 .replace(/import \{ presentContinuousScene \} from .*?;/,'const presentContinuousScene=()=>{};')
 .replace(/from '(\.\.\/src\/[^']+)'/g,(_,p)=>`from '${new URL(p.replace('../',''),root).href}'`)
 .replaceAll('import.meta.url',JSON.stringify(entry.href));
 const task=import('data:text/javascript;base64,'+Buffer.from(`// execution ${++count}\n${source}`).toString('base64'));
 task.catch(()=>{});
 return {doc,data,storage:namespaced,win,task,assigned,setApproval:v=>{approved=v;},cleanup(){for(const timer of timers)clearTimeout(timer);for(const [key,value] of saved){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}};
}
function choose(h,p){const root=h.doc.getElementById('profile-root'),select=root.all().find(n=>n.id==='profile-choice');select.value=p.id;select.onchange();root.find('开始所选难度').onclick();}
function finish(h){const root=h.doc.getElementById('opening-root');root.find('跳至结尾（不确认作业）').onclick();const button=root.find('读完，进入实际码头');button.onclick();button.onclick();}
function drainStory(h){for(let n=0;n<80&&h.doc.getElementById('story').open;n++){const unresolved=h.doc.getElementById('story-choices').children.find(n=>!n.disabled);if(unresolved)unresolved.onclick();else h.doc.getElementById('story-skip').onclick();}assert.equal(h.doc.getElementById('story').open,false);}
for(const p of PROFILES)test(`actual entry ${p.label}: selector → mandatory opening → Finish once → correct session and scoped saves`,async()=>{const h=await fixture();try{await until(()=>h.doc.getElementById('profile-dialog').open);assert.equal(h.data.size,0);assert.equal(h.win.__C3D_QA__,undefined);choose(h,p);await until(()=>h.doc.getElementById('opening-root').find('跳至结尾（不确认作业）'));assert.equal(h.data.size,0);assert.equal(h.win.__C3D_QA__,undefined);const dialog=h.doc.getElementById('opening-dialog');for(let n=0;n<3;n++){const event={key:'Escape',preventDefault(){},stopPropagation(){}};for(const fn of h.doc.events.keydown??[])fn(event);dialog.close();assert.equal(dialog.open,true);}assert.equal(h.data.size,0);h.doc.getElementById('opening-root').find('继续阅读').onclick();finish(h);await h.task;assert.equal(h.win.__C3D_QA__.snapshot().profileId,p.id);assert.equal(h.win.__C3D_QA__.snapshot().identity.contentHash,p.identity.contentHash);assert.equal(h.win.__C3D_QA__.snapshot().state.revision,0);assert.equal(h.data.size,2);assert.ok(h.doc.getElementById('profile-status').text.includes(p.label));for(const key of h.data.keys())assert.ok(key.includes(`:${p.difficultyId}:`));}finally{h.cleanup();}});
test('actual legacy entry resume preserves exact auto/manual bytes before player action and skips fresh opening',async()=>{let auto,manual,keys;const h=await fixture({seed:storage=>{const rt=createProfileRuntime(PROFILES[0].id),repo=createProfileRepository(storage,rt,{profileId:PROFILES[0].id}),state=rt.dispatch(rt.initialState(),{type:'move',direction:'left'}).state;auto=JSON.stringify(state,null,2);manual=JSON.stringify({$campaignSave:1,state,presentation:{seenIds:['c01'],queue:[],turnIndex:0}},null,1);keys=[repo.key('auto'),repo.key('manual')];storage.setItem(keys[0],auto);storage.setItem(keys[1],manual);}});try{await h.task;assert.equal(h.doc.getElementById('profile-dialog').open,false);assert.equal(h.doc.getElementById('opening-dialog').open,false);assert.equal(h.win.__C3D_QA__.snapshot().state.revision,1);assert.equal(h.storage.getItem(keys[0]),auto);assert.equal(h.storage.getItem(keys[1]),manual);assert.equal(h.data.size,2);}finally{h.cleanup();}});
test('actual selector visit/cancel/repeat, modal movement/save guards and explicit new game retain old progress',async()=>{const p=PROFILES[0],h=await fixture({seed:storage=>{const rt=createProfileRuntime(p.id),repo=createProfileRepository(storage,rt,{profileId:p.id});repo.save('auto',rt.initialState(),{seenIds:['c01','c02'],queue:[],turnIndex:0});repo.save('manual',rt.initialState());}});try{await h.task;drainStory(h);const before=[...h.data],stateBefore=h.win.__C3D_QA__.snapshot().stateHash,url=h.win.location.href;const pending=h.doc.getElementById('new').onclick();await next();const root=h.doc.getElementById('profile-root');assert.equal(h.doc.getElementById('profile-dialog').open,true);h.doc.directions[0].onclick();h.doc.getElementById('save').onclick();await h.doc.getElementById('new').onclick();assert.deepEqual([...h.data],before);assert.equal(h.win.__C3D_QA__.snapshot().stateHash,stateBefore);root.find('返回当前游戏').onclick();await pending;assert.equal(h.win.location.href,url);assert.equal(h.assigned.length,0);const again=h.doc.getElementById('new').onclick();await next();h.setApproval(false);const start=root.find('另开新航次');start.onclick();assert.equal(h.assigned.length,0);assert.equal(h.doc.getElementById('profile-dialog').open,true);h.setApproval(true);start.onclick();start.onclick();await again;assert.equal(h.assigned.length,1);assert.ok(new URL(h.assigned[0]).searchParams.get('run'));assert.deepEqual([...h.data],before);}finally{h.cleanup();}});
test('actual unsupported auto plus valid manual restores read-only and refuses save/load-driven overwrite',async()=>{let keys,raw;const p=PROFILES[1],h=await fixture({url:selectionUrl('https://example.invalid/c/campaigns/',{profileId:p.id,runId:''}),seed:storage=>{const rt=createProfileRuntime(p.id),repo=createProfileRepository(storage,rt,{profileId:p.id});repo.save('manual',rt.initialState(),{seenIds:['c01','c02'],queue:[],turnIndex:0});raw=JSON.stringify({$campaignSave:99,state:rt.initialState()});keys=[repo.key('auto'),repo.key('manual')];storage.setItem(keys[0],raw);}});try{await h.task;const before=[...h.data];assert.equal(h.win.__C3D_QA__.snapshot().saveWritable,false);drainStory(h);h.doc.getElementById('save').onclick();h.doc.getElementById('load-manual').onclick();h.doc.directions[0].onclick();assert.equal(h.storage.getItem(keys[0]),raw);assert.deepEqual([...h.data],before);}finally{h.cleanup();}});
for(const p of PROFILES)test(`actual entry ${p.label}: current-profile certificate completes without autos/manual writes; continue exits replay through reload`,async()=>{const h=await fixture({url:selectionUrl('https://example.invalid/c/campaigns/',{profileId:p.id,runId:''}),seed:storage=>{const rt=createProfileRuntime(p.id),repo=createProfileRepository(storage,rt,{profileId:p.id});repo.save('auto',rt.initialState(),{seenIds:['c01','c02'],queue:[],turnIndex:0});repo.save('manual',rt.initialState());}});try{await h.task;drainStory(h);const before=[...h.data];await h.doc.getElementById('replay-load').onclick();assert.equal(h.win.__C3D_QA__.snapshot().mode,'certificate-replay');for(let n=0;n<170;n++){drainStory(h);h.doc.getElementById('replay-step').onclick();}drainStory(h);const snapshot=h.win.__C3D_QA__.snapshot();assert.equal(snapshot.state.victory,true);assert.equal(snapshot.state.stats.hp,29-p.delta*8);assert.equal(snapshot.state.resources.fuel,1);h.doc.getElementById('save').onclick();assert.deepEqual([...h.data],before);const menu=h.doc.getElementById('new').onclick();await next();h.doc.getElementById('profile-root').find('继续所选航次').onclick();await menu;assert.equal(h.assigned.length,1);assert.equal(h.assigned[0],h.win.location.href);assert.deepEqual([...h.data],before);}finally{h.cleanup();}});
