import test from 'node:test';
import assert from 'node:assert/strict';
import {PROFILES} from '../src/profiles/registry.js';
import {createProfileRuntime} from '../src/profiles/runtime.js';
import {createProfileRepository} from '../src/profiles/persistence.js';
import {prepareProfileSession} from '../src/profiles/boot.js';
import {listContexts,readSelection,resolveBootSelection,selectionUrl,mountProfileSelector,freshContext} from '../src/profiles/selection.js';
import {documentMock} from './helpers/dom-mock.js';
const url='https://example.invalid/c/campaigns/';
const memory=()=>{const data=new Map();return {data,get length(){return data.size;},key:i=>[...data.keys()][i]??null,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};};
function fixture(){const doc=documentMock(),storage=memory(),dialog=doc.getElementById('profile-dialog');dialog.tagName='dialog';dialog.close=()=>{if(!dialog.open)return;dialog.open=false;for(const fn of dialog.events.close??[])fn({type:'close'});};let approvals=0,approved=true;const selector=mountProfileSelector({document:doc,storage,confirm:()=>{approvals++;return approved;}});return {doc,storage,dialog,root:doc.getElementById('profile-root'),selector,approvals:()=>approvals,reject:()=>{approved=false;},accept:()=>{approved=true;}};}
const click=(h,text)=>{const b=h.root.find(text);assert.ok(b,text);assert.equal(b.disabled,false);b.onclick();return b;};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function save(storage,p,runId=''){const runtime=createProfileRuntime(p.id),repo=createProfileRepository(storage,runtime,{profileId:p.id,runId});repo.save('auto',runtime.dispatch(runtime.initialState(),{type:'move',direction:'left'}).state,{seenIds:['c01'],queue:[],turnIndex:0});return repo;}
test('fresh selection constructs no runtime and writes no storage before explicit choice',async()=>{const h=fixture();let constructed=0,selectedUrl;const task=prepareProfileSession({storage:h.storage,url,selector:h.selector,createRuntime:id=>{constructed++;return createProfileRuntime(id);},onSelected:value=>{selectedUrl=value;}});await tick();assert.equal(constructed,0);assert.equal(h.storage.data.size,0);const select=h.root.all().find(n=>n.id==='profile-choice');select.value=PROFILES[2].id;select.onchange();assert.equal(constructed,0);click(h,'开始所选难度');const session=await task;assert.equal(constructed,1);assert.equal(session.profile.label,'EXTREME');assert.equal(session.restored.source,null);assert.equal(h.storage.data.size,0);assert.deepEqual(readSelection(selectedUrl),session.context);});
test('reload uses explicit selected context and does not consult another profile fallback',async()=>{const h=fixture();save(h.storage,PROFILES[0]);const hard=save(h.storage,PROFILES[1],'r-abc-123');const before=[...h.storage.data];const context={profileId:PROFILES[1].id,runId:'r-abc-123'};const session=await prepareProfileSession({storage:h.storage,url:selectionUrl(url,context),selector:h.selector});assert.equal(session.profile.label,'HARD');assert.equal(session.restored.source,'auto');assert.equal(session.runtime.stateHash(session.restored.state),session.runtime.stateHash(hard.load('auto')));assert.deepEqual([...h.storage.data],before);assert.equal(h.dialog.open,false);});
test('one legacy normal context resumes automatically with original bytes and presentation',async()=>{const h=fixture();const repo=save(h.storage,PROFILES[0]);const raw=h.storage.getItem(repo.key('auto'));const session=await prepareProfileSession({storage:h.storage,url,selector:h.selector});assert.equal(session.profile.label,'STANDARD');assert.equal(session.restored.state.revision,1);assert.deepEqual(session.restored.presentation.seenIds,['c01']);assert.equal(h.storage.getItem(repo.key('auto')),raw);assert.equal(h.dialog.open,false);});
test('markerless known hard with no selector preference resolves by state identity',()=>{const h=fixture(),p=PROFILES[1],runtime=createProfileRuntime(p.id),repo=createProfileRepository(h.storage,runtime,{profileId:p.id});h.storage.setItem(repo.key('auto'),JSON.stringify(runtime.initialState()));assert.deepEqual(resolveBootSelection(h.storage,url).context,{profileId:p.id,runId:''});});
for(const query of ['?profile=future','?run=r-abc-123','?profile=voyage-c-hard-r1&run=../../bad','?profile=voyage-c-hard-r1&profile=voyage-c-standard-r1'])test(`unknown/ambiguous URL is refused without writes: ${query}`,()=>{const storage=memory();assert.throws(()=>readSelection(url+query));assert.equal(resolveBootSelection(storage,url+query).context,null);assert.equal(storage.data.size,0);});
test('multiple saved difficulties require choice rather than comparing revisions',()=>{const storage=memory();save(storage,PROFILES[0]);save(storage,PROFILES[2]);assert.equal(resolveBootSelection(storage,url).context,null);});
test('visiting selector, selecting another difficulty and canceling preserves all slots and current context',async()=>{const h=fixture(),current={profileId:PROFILES[0].id,runId:''};save(h.storage,PROFILES[0]);const before=[...h.storage.data];const task=h.selector.open({current});const select=h.root.all().find(n=>n.id==='profile-choice');select.value=PROFILES[1].id;select.onchange();click(h,'返回当前游戏');assert.equal(await task,null);assert.deepEqual([...h.storage.data],before);assert.equal(h.approvals(),0);assert.equal(h.dialog.open,false);});
test('in-progress new game requires confirmation, rejects repeated/stale clicks, and preserves discoverable prior context',async()=>{const h=fixture(),p=PROFILES[0],current={profileId:p.id,runId:''};save(h.storage,p);const before=[...h.storage.data];const task=h.selector.open({current});h.reject();const start=click(h,'另开新航次');await tick();assert.equal(h.dialog.open,true);assert.equal(h.approvals(),1);assert.deepEqual([...h.storage.data],before);h.accept();start.onclick();start.onclick();const result=await task;assert.equal(h.approvals(),2);assert.equal(result.mode,'new');assert.ok(result.runId);assert.deepEqual([...h.storage.data],before);save(h.storage,p,result.runId);assert.deepEqual(listContexts(h.storage,p).map(c=>c.runId).sort(),['',result.runId].sort());const resume=h.selector.open({current:result});const saved=h.root.all().find(n=>n.id==='profile-saved');saved.value='';saved.onchange();click(h,'继续所选航次');assert.deepEqual(await resume,{profileId:p.id,runId:'',mode:'resume'});for(const [key,value] of before)assert.equal(h.storage.getItem(key),value);});
test('forced startup close reopens; optional native Escape closes once and stale close cannot dismiss a newer menu',async()=>{const h=fixture();const pending=h.selector.open({mandatory:true});let done=false;pending.then(()=>{done=true;});for(let i=0;i<3;i++){h.dialog.events.cancel[0]({preventDefault(){}});h.dialog.close();assert.equal(h.dialog.open,true);}await tick();assert.equal(done,false);click(h,'开始所选难度');await pending;const optional=h.selector.open({current:{profileId:PROFILES[0].id,runId:''}});h.dialog.events.cancel[0]({preventDefault(){}});assert.equal(await optional,null);assert.equal(h.dialog.open,false);const next=h.selector.open();h.dialog.events.close[0]({});assert.equal(h.dialog.open,true);click(h,'返回当前游戏');await next;});
test('another active modal and repeated selector activation never replace session or open a second modal',async()=>{const h=fixture();h.doc.getElementById('story').open=true;assert.equal(await h.selector.open(),null);h.doc.getElementById('story').open=false;const task=h.selector.open();assert.equal(await h.selector.open(),null);click(h,'返回当前游戏');assert.equal(await task,null);assert.equal(h.storage.data.size,0);});
test('unsupported-only selected context is refused before session return; explicit new run preserves original',async()=>{const h=fixture(),p=PROFILES[0],rt=createProfileRuntime(p.id),repo=createProfileRepository(h.storage,rt,{profileId:p.id});const raw=JSON.stringify({$campaignSave:2,state:rt.initialState()});h.storage.setItem(repo.key('auto'),raw);const task=prepareProfileSession({storage:h.storage,url:selectionUrl(url,{profileId:p.id,runId:''}),selector:h.selector});for(let n=0;n<400&&!h.dialog.open;n++)await new Promise(resolve=>setTimeout(resolve,5));assert.equal(h.dialog.open,true);assert.ok(h.root.text.includes('没有兼容存档'));click(h,'另开新航次');const session=await task;assert.ok(session.context.runId);assert.equal(session.restored.source,null);assert.equal(h.storage.getItem(repo.key('auto')),raw);assert.equal(h.storage.data.size,1);});
test('new context allocation keeps original empty namespace and avoids existing run collision',()=>{const storage=memory(),p=PROFILES[0];assert.deepEqual(freshContext(storage,p.id),{profileId:p.id,runId:''});save(storage,p);const context=freshContext(storage,p.id,{now:()=>100,random:()=>.1});assert.ok(context.runId);save(storage,p,context.runId);assert.throws(()=>freshContext(storage,p.id,{now:()=>100,random:()=>.1}));});
