import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createVoyageCampaign,VOYAGE_VESSEL_GEOMETRY as G} from '../src/campaigns/c/content.js';
import {replayCampaignCertificate} from '../src/solver/campaign-replay.js';
import {buildViewModel,logicalPoint,metricToCell,rigidYaw} from '../src/rendering/c-three-model.js';
import {makeCamera,projectLogical,pickLogical} from '../src/rendering/c-three-scene.js';
const runtime=createVoyageCampaign(),cert=JSON.parse(await readFile(new URL('../public/campaigns/c-normal.certificate.json',import.meta.url)));
function route(){let state=runtime.initialState();const states=[state];for(const step of cert.steps){const r=runtime.dispatch(state,step.action);assert.equal(r.ok,true);state=r.state;states.push(state);}return states;}
const states=route(),sha=b=>createHash('sha256').update(b).digest('hex');
test('frozen identity and complete 170-atomic-action winning certificate replay unchanged',()=>{assert.equal(runtime.identity.contentHash,'c5a5f809d5548f36');const replay=replayCampaignCertificate(runtime,cert);assert.equal(replay.ok,true);assert.equal(replay.steps,170);assert.equal(replay.state.victory,true);});
test('core, combat, solver, story, planning and content snapshots are byte-identical (explicit geometry-only loader patch excluded)',async()=>{const records=JSON.parse(await readFile(new URL('../reports/source-snapshot.json',import.meta.url)));for(const rec of records.filter(r=>r.file.startsWith('src/')&&r.file!=='src/rendering/continuous-map.js')){const data=await readFile(new URL('../'+rec.file,import.meta.url));assert.equal(sha(data),rec.sha256,rec.file);}});
test('initial board action crosses unique gangway rather than injecting a deck state',()=>{let state=runtime.initialState();assert.equal(state.location.regionId,'C-M01');assert.equal(runtime.inReach(state,'C-M01.boat'),false);let m=runtime.preview(state,{type:'move',direction:'left'});assert.equal(m.legal,true);state=runtime.dispatch(state,{type:'move',direction:'left'}).state;assert.equal(runtime.inReach(state,'C-M01.boat'),true);const boarding=runtime.preview(state,{type:'traverse',edgeId:'C-M01.board'});assert.equal(boarding.legal,true);const r=runtime.dispatch(state,{type:'traverse',edgeId:'C-M01.board'});assert.deepEqual(r.state.location,{regionId:'C-D01',x:7,y:7});assert.equal(r.state.revision,2);});
test('every replay state yields read-only geometry, exact 3 unique weights and shared 2D semantics',()=>{for(const state of states){const before=runtime.serialize(state),a=buildViewModel(runtime,state),b=buildViewModel(runtime,state);assert.deepEqual(a,b);assert.equal(runtime.serialize(state),before);assert.equal(a.geometryId,'C_FERRY_HULL_01');assert.equal(a.weights.length,3);assert.equal(new Set(a.weights.map(w=>w.id)).size,3);assert.equal(a.weights.map(w=>w.mass).sort().join(','),'1,1,2');assert.equal(a.slots.length,6);assert.equal(a.cargo.id,'one-lamp-cargo');if(a.sharedSemantics){assert.deepEqual(a.sharedSemantics.fixtures.weights.map(w=>w.id).sort(),a.weights.map(w=>w.id).sort());assert.equal(a.sharedSemantics.geometryId,a.geometryId);}}});
test('project / plane pick roundtrips all 121 cells on all views at mobile, desktop and DPR-independent scales',()=>{for(const state of states.filter((s,i)=>i===0||s.location.regionId!==states[i-1].location.regionId||s.boat.dock!==states[i-1].boat.dock)){const m=buildViewModel(runtime,state);for(const[w,h]of[[375,375],[700,620],[1024,900],[450,780]]){const camera=makeCamera(m,w,h);for(let y=0;y<11;y++)for(let x=0;x<11;x++){const p=projectLogical(camera,m,x,y,w,h),picked=pickLogical(camera,m,p.x,p.y,w,h);assert.deepEqual(picked,{x,y},`${m.regionId}/${m.dock} ${w} ${x},${y}`);}}}});
test('all legal deck cells fit in fixed portrait and square frusta and physical transform roundtrips',()=>{const m=buildViewModel(runtime,states.find(s=>s.location.regionId==='C-D01'));for(const [w,h]of[[375,375],[700,620],[450,780]]){const camera=makeCamera(m,w,h);for(let y=0;y<11;y++)for(let x=0;x<11;x++){assert.deepEqual(metricToCell(m.regionId,logicalPoint(m.regionId,x,y)),{x,y});if(m.passability[y][x]){const p=projectLogical(camera,m,x,y,w,h);assert.ok(p.x>0&&p.x<w&&p.y>0&&p.y<h,`${x},${y} outside`);}}}});
test('all 120 assignments of three weights remain unique and do not require one balance solution',()=>{const s=structuredClone(states.find(s=>s.location.regionId==='C-D01')),slots=Object.keys(runtime.spec.ballast.slots);let n=0;for(const a of slots)for(const b of slots)for(const c of slots){if(new Set([a,b,c]).size<3)continue;s.boat.positions={w1:a,w2:b,w3:c};runtime.assertValidState(s);const m=buildViewModel(runtime,s);assert.deepEqual(m.weights.map(w=>w.slot),[a,b,c]);n++;}assert.equal(n,120);});
test('hull dimensions and physical fixture support match authoritative v1.2 JSON and immutable OBJ',async()=>{const physical=JSON.parse(await readFile(new URL('../geometry/vessel-physical-geometry-v1.2.json',import.meta.url)));assert.deepEqual(physical.geometry,G);assert.equal(G.hull.length,6);assert.equal(G.hull.beam,3);assert.equal(physical.mesh.allowNonuniformScale,false);assert.equal(sha(await readFile(new URL('../geometry/vessel-hull-v1.2.obj',import.meta.url))),physical.objSha256);assert.equal(G.fixtures.securedSword.visible,false);const foot=G.fixtures.cargoDavit.hullMountXYZ;assert.ok(foot[0]<1.5);assert.equal(foot[1],.8);assert.deepEqual(G.fixtures.cargoDavit.operator,[7,2]);assert.deepEqual(G.fixtures.gateWinch.operator,[4,4]);});
test('M03/M05 equipment and mooring use only true reached states; future devices hidden',()=>{assert.equal(buildViewModel(runtime,states[0]).devices.length,0);const winch=states.find(s=>s.boat.dock==='C-M03'&&s.boat.cargo==='left');assert.ok(winch);assert.equal(buildViewModel(runtime,winch).devices[0].id,'one-gate-winch');const unload=states.find(s=>s.boat.dock==='C-M05'&&s.boat.cargo==='ashore');assert.ok(unload);assert.equal(buildViewModel(runtime,unload).devices[0].id,'one-cargo-davit');assert.equal(buildViewModel(runtime,states.at(-1)).devices[0].stowed,true);for(const s of states){const m=buildViewModel(runtime,s);assert.equal(m.moored,s.boat.moored);assert.equal(m.barrierOpen,Boolean(s.flags['c.barrierOpen']));}});
test('wrong device stand cannot operate; preview leaves input unmodified',()=>{const s=structuredClone(states.find(s=>s.boat.dock==='C-M03'&&s.boat.cargo==='left'));s.location={regionId:'C-D01',x:4,y:3};assert.equal(runtime.inReach(s,'c.openBarrier'),false);const before=runtime.stateHash(s),p=runtime.preview(s,{type:'interact',entityId:'c.openBarrier'});assert.equal(p.legal,false);assert.equal(runtime.stateHash(s),before);});
test('M04 yaw is a rigid positive-determinant rotation, never reflected',()=>{const i=rigidYaw([1,0,0],Math.PI),k=rigidYaw([0,0,1],Math.PI);assert.ok(Math.abs(i[0]+1)<1e-10);assert.ok(Math.abs(k[2]+1)<1e-10);assert.ok(i[0]*k[2]-i[2]*k[0]>0);});
test('Three version is exact MIT pin and UI provides fallback without fixture state injection',async()=>{const pkg=JSON.parse(await readFile(new URL('../package.json',import.meta.url)));assert.equal(pkg.dependencies.three,'0.180.0');const html=await readFile(new URL('../public/campaigns/index.html',import.meta.url),'utf8');assert.ok(html.includes('view-2d'));assert.ok(html.includes('importmap'));const app=await readFile(new URL('../public/campaigns/app.js',import.meta.url),'utf8');assert.ok(app.includes("c3d-prototype:"));assert.ok(app.includes('runtime.preview(state,action)'));assert.ok(!app.includes('fixtureState'));assert.ok(app.includes("state=runtime.initialState()"));});

test('repeated view-model and camera projection never alter authoritative state',()=>{for(const s of states){const hash=runtime.stateHash(s),m=buildViewModel(runtime,s);for(const [w,h]of [[360,360],[900,720]]){const camera=makeCamera(m,w,h);for(const [x,y]of [[3,1],[5,5],[7,9]]){const p=projectLogical(camera,m,x,y,w,h);pickLogical(camera,m,p.x,p.y,w,h);}}assert.equal(runtime.stateHash(s),hash);}});
