import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createVoyageCampaign} from '../src/campaigns/c/content.js';
import {createSaveRepository} from '../src/core/campaign.js';
import {RECOVERY_PRESENTATION} from '../src/rendering/recovery-presentation.js';
import {preloadMapMaterials} from '../src/rendering/continuous-map.js';
const runtime=createVoyageCampaign();
function memory(){const data=new Map();return {data,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
test('every witnessed state roundtrips through save serialization without changing identity or resources',async()=>{const cert=JSON.parse(await readFile(new URL('../public/campaigns/c-normal.certificate.json',import.meta.url)));const storage=memory(),repo=createSaveRepository(storage,runtime);let state=runtime.initialState();for(const step of cert.steps){const before=runtime.serialize(state);const preview=runtime.preview(state,step.action);assert.equal(preview.legal,true);assert.equal(runtime.serialize(state),before);const r=runtime.dispatch(state,step.action);assert.equal(r.ok,true);state=r.state;repo.save('auto',state,{seenIds:[],queue:[],turnIndex:0});const loaded=repo.restore();assert.deepEqual(loaded.state,state);assert.equal(loaded.allowAutoSave,true);}assert.equal(state.victory,true);});
test('foreign identity cannot be restored and corrupt autosave is backed up without overwrite',()=>{const storage=memory(),repo=createSaveRepository(storage,runtime);const state=runtime.initialState();state.identity.contentHash='missing-newer-version';const raw=JSON.stringify(state);storage.setItem(repo.key('auto'),raw);const result=repo.restore();assert.equal(result.state,null);assert.equal(result.allowAutoSave,false);assert.equal(result.issues.length,1);assert.equal(storage.getItem(repo.key('auto')),raw);assert.equal(storage.getItem(result.issues[0].backup),raw);});
test('valid manual fallback is preserved when autosave is corrupt',()=>{const storage=memory(),repo=createSaveRepository(storage,runtime);repo.save('manual',runtime.initialState());storage.setItem(repo.key('auto'),'{broken');const result=repo.restore();assert.equal(result.source,'manual');assert.deepEqual(result.state,runtime.initialState());assert.equal(result.issues.length,1);});
test('illegal remote action changes neither state nor resources',()=>{const state=runtime.initialState(),before=runtime.serialize(state);const result=runtime.dispatch(state,{type:'interact',entityId:'c.unload'});assert.equal(result.ok,false);assert.equal(runtime.serialize(state),before);});
test('geometry-only mode never requests missing material URLs or silently claims art acceptance',()=>{assert.equal(RECOVERY_PRESENTATION.materialsAvailable,false);assert.equal(RECOVERY_PRESENTATION.finalArtAccepted,false);const prior=globalThis.Image;globalThis.Image=class{constructor(){throw new Error('Missing art must not be requested');}};try{preloadMapMaterials();}finally{if(prior===undefined)delete globalThis.Image;else globalThis.Image=prior;}});
