import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {chooseViewportLayout,LAYOUT_LIMITS} from '../src/rendering/c-viewport-layout.js';
// These are modeled DOM measurements, not a browser screenshot result.
const sample={viewportWidth:1180,viewportHeight:757,mainTop:88,mainPaddingY:14,sectionChromeY:26,otherHeight:212,innerWidth:715};
test('1180 x 757 modeled chrome budget reserves new toolbar, notice and direction controls',()=>{const r=chooseViewportLayout(sample);assert.equal(r.mode,'desktop-fit');assert.equal(r.availableHeight,417);assert.equal(r.mapSize,407);assert.ok(sample.mainTop+sample.mainPaddingY+sample.sectionChromeY+sample.otherHeight+r.mapSize<=sample.viewportHeight);assert.ok(r.mapSize/11>=32);});
test('modeled expanded fallback message or diagnostics reduce map budget rather than push controls out',()=>{for(const extra of[0,16,32,48,64]){const r=chooseViewportLayout({...sample,otherHeight:sample.otherHeight+extra});assert.equal(r.mode,'desktop-fit');assert.ok(r.mapSize<=417-extra);assert.equal(r.mapSize%11,0);assert.ok(r.mapSize>=352);}});
test('short desktop uses document scrolling instead of shrinking below 32px per cell',()=>{for(const h of[400,560,620,660]){const r=chooseViewportLayout({...sample,viewportHeight:h});assert.equal(r.mode,'desktop-scroll');assert.equal(r.mapSize,660);assert.ok(r.mapSize/11>=32);}});
test('mobile 320 through 1000 uses one width-limited square with document scrolling',()=>{for(const width of[320,360,390,768,1000]){const r=chooseViewportLayout({...sample,viewportWidth:width,innerWidth:width-50});assert.equal(r.mode,'mobile');assert.ok(r.mapSize<=width-50);assert.equal(r.mapSize%11,0);assert.ok(r.mapSize<=LAYOUT_LIMITS.maxMap);}});
test('resize increases size again and a wider row cannot violate height constraint',()=>{const short=chooseViewportLayout(sample),tall=chooseViewportLayout({...sample,viewportHeight:1000});assert.ok(tall.mapSize>short.mapSize);assert.equal(chooseViewportLayout({...sample,innerWidth:2000}).mapSize,short.mapSize);});
test('measurement observes changing chrome and resize but excludes map itself; no state or GPU mutation',async()=>{const js=await readFile(new URL('../src/rendering/c-viewport-layout.js',import.meta.url),'utf8');assert.ok(js.includes("other=[...section.children].filter(e=>e!==stage)"));assert.ok(js.includes(".filter(e=>e!==stage))observer.observe(el)"));assert.ok(js.includes("win.addEventListener('resize',schedule)"));assert.ok(js.includes("doc.fonts?.ready?.then(schedule)"));assert.ok(!/import\s/.test(js));assert.ok(!/dispatch|localStorage|WebGLRenderer|no-sandbox|SwiftShader/.test(js));assert.ok(js.includes('getBoundingClientRect().height'));assert.ok(js.includes('px(s.marginTop)+px(s.marginBottom)'));});
test('scoped CSS keeps desktop aside independently scrollable and mobile page scrollable',async()=>{const css=await readFile(new URL('../public/campaigns/styles.css',import.meta.url),'utf8');assert.ok(css.includes('body{height:100dvh;display:flex;flex-direction:column;overflow:hidden}'));assert.ok(css.includes('aside{height:100%;overflow-y:auto;overflow-x:hidden;'));assert.ok(css.includes(':root[data-c-layout="desktop-scroll"] body{height:auto;display:block;overflow:auto}'));assert.ok(css.includes('body{height:auto;display:block;overflow:auto}'));assert.ok(css.includes('--measured-map-size'));assert.ok(css.includes('.exploration #view-stats:empty{display:none}'));assert.ok(!css.includes('height:auto!important'));assert.ok(!css.includes('display:block!important'));});
