import { VOYAGE_VESSEL_GEOMETRY as G,voyageVesselToBerth,voyageDeckToBerth } from '../campaigns/c/content.js';
import { MAP_ART_REVISION,cellsWhere,compileBoundaryRuns,rect,line,circle,label,entityCommands } from './continuous-map.js';
export const C_MAP_ART_REVISION=`${MAP_ART_REVISION}-c-dock-support-r2`;
export const VOYAGE_MAP_SIDECAR=Object.freeze({artRevision:C_MAP_ART_REVISION,geometryId:G.geometryId,geometryVersion:G.version,rulesContentHash:'c5a5f809d5548f36',samples:Object.freeze(['C-D01','C-M03','C-M05']),source:'candidate-c-art-plan/current-geometry.json v1.2; runtime VOYAGE_VESSEL_GEOMETRY'});
// The half-cell offset converts logical centres to the shared compositor origin.
export function vesselPoint([X,Y,Z],deck){const sampling=G.deckSampling,p=deck?[(X-sampling.originXYZ[0])/sampling.xStepXYZ[0],(Z-sampling.originXYZ[2])/sampling.yStepXYZ[2]]:voyageVesselToBerth([X,Y,Z]);return p.map(n=>n+.5);}
export function berthPoint(p,deck){const b=G.berthSampling;return deck?vesselPoint([(p[0]-b.hullOriginGrid[0])*b.metresPerCell,G.hull.deckY,(p[1]-b.hullOriginGrid[1])*b.metresPerCell],true):p.map(n=>n+.5);}
export function deckPoint(p,deck){return(deck?p:voyageDeckToBerth(p)).map(n=>n+.5);}
// Quay cells are existing current-dock terrain, not new D01 navigation. The
// quarter-metre inset is a visual contour INSIDE the west-facing authored cell:
// hull edge 6.5m, quay edge 6.75m, existing bank centre 7m remains supported.
export const QUAY_WATER_GAP_METRES=.25;
const inside=(p,poly)=>poly.every((a,i)=>{const b=poly[(i+1)%poly.length];return (b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0])>=-1e-9;});
export function projectDockContext(runtime,dockId,deck){
 const dock=runtime.region(dockId),g=G.berthSampling,gangwayStart=g.gangwayCenterlineGrid[0],key=p=>p.join(','),land=cellsWhere(dock.map,(t,x,y)=>(t==='.'||t==='#')&&!(x===gangwayStart[0]&&y===gangwayStart[1])),landSet=new Set(land.map(key)),polygons=[],edges=new Map();
 for(const[x,y]of land){const westExposed=!landSet.has(`${x-1},${y}`),x0=x-.5+(westExposed?QUAY_WATER_GAP_METRES/g.metresPerCell:0),bounds=[[x0,y-.5],[x+.5,y-.5],[x+.5,y+.5],[x0,y+.5]],polygon=bounds.map(p=>berthPoint(p,deck)),entry={sourceCell:[x,y],sourceToken:dock.map[y][x],berthPolygon:bounds,polygon};polygons.push(entry);
  for(let i=0;i<polygon.length;i++){const a=polygon[i],b=polygon[(i+1)%polygon.length],k=[key(a),key(b)].sort().join('|');if(edges.has(k))edges.delete(k);else edges.set(k,[a,b]);}
 }
 const descriptions=Array.from({length:11},()=>Array(11).fill(null));if(deck)for(let y=0;y<11;y++)for(let x=0;x<11;x++){const p=polygons.find(p=>inside([x+.5,y+.5],p.polygon));if(p)descriptions[y][x]=p.sourceToken==='#'?'当前泊位岸桩基座；岸上请经唯一跳板返回，甲板视图不能直接踏岸':'岸上，请经唯一跳板返回当前泊位；甲板视图不能直接踏岸';}
 return{dockId,sourceMap:dock.map.join('|'),polygons,boundaryRuns:[...edges.values()].map(points=>({kind:'shore',points})),descriptions,waterGapMetres:QUAY_WATER_GAP_METRES};
}
export function projectVoyageScene(runtime,state){const view=runtime.projectView(state),r=view.region,deck=r.id==='C-D01';if(!VOYAGE_MAP_SIDECAR.samples.includes(r.id)||runtime.identity.contentHash!==VOYAGE_MAP_SIDECAR.rulesContentHash)return null;
 const scale=deck?1:G.deckSampling.pitch/G.berthSampling.metresPerCell,pt=p=>deckPoint(p,deck),metric=p=>vesselPoint(p,deck),scene={campaign:'C',regionId:r.id,width:11,height:11,artRevision:C_MAP_ART_REVISION,rulesContentHash:runtime.identity.contentHash,geometryId:G.geometryId,geometryVersion:G.version,ambient:{color:'#102b42',alpha:.28},topologyHash:r.map.join('|'),surfaces:[],boundaryRuns:[],structures:[],objects:[],visibleEntities:view.entities.filter(e=>runtime.meets(state,e.visibleWhen)).map(e=>e.id),passability:r.map.map((row,y)=>[...row].map((_,x)=>runtime.passable(state,x,y))),fixtures:{slots:[],weights:[],cargo:[],devices:[]}};
 const all=cellsWhere(r.map,()=>true),dockId=deck?state.boat.dock:r.id,context=projectDockContext(runtime,dockId,deck),metresToScreen=1/(deck?G.deckSampling.pitch:G.berthSampling.metresPerCell);scene.surfaces.push({id:'water',material:'water',cells:all});scene.dockContext=context;scene.contextCellDescriptions=context.descriptions;
 for(const p of context.polygons)scene.surfaces.push({id:`quay-${dockId}-${p.sourceCell.join('-')}`,material:p.sourceToken==='#'?'dark-rock':'dry-stone',polygon:p.polygon,sourceCell:p.sourceCell,sourceRegion:dockId,uv:{origin:berthPoint([-.5,-.5],deck),period:4*metresToScreen}});scene.boundaryRuns.push(...context.boundaryRuns);
 if(!deck)for(const[x,y]of cellsWhere(r.map,t=>t==='X')){scene.structures.push(rect(x,y,1,1,'#34434a'),line([[x+.12,y+.12],[x+.86,y+.86]],'#ae8570',.08),line([[x+.12,y+.86],[x+.86,y+.12]],'#ae8570',.08));}
 const hull=G.hull.outlineXZ.map(([X,Z])=>metric([X,G.hull.deckY,Z]));scene.hullOutline=hull;scene.surfaces.push({id:'C_FERRY_HULL_01-deck',material:'warm-planks',polygon:hull,uv:{origin:[Math.min(...hull.map(p=>p[0])),Math.min(...hull.map(p=>p[1]))],periodX:4*scale,height:10*scale}});scene.structures.push({type:'path',points:hull,closed:true,stroke:'#2c373b',lineWidth:.14*scale,structureId:G.geometryId},{type:'path',points:hull,closed:true,stroke:'#c3ac7f',lineWidth:.055*scale});
 // Edge rails keep the only gangway clear; the bow/stern remain one hull.
 const rightTop=metric([1.5,.8,-2.4]),rightGapA=metric([1.5,.8,1.5-.24]),rightGapB=metric([1.5,.8,1.5+.24]),rightStern=metric([1.5,.8,3]);
 scene.boundaryRuns.push({kind:'rail',points:[rightTop,rightGapA]},{kind:'rail',points:[rightGapB,rightStern]},{kind:'rail',points:[metric([-1.5,.8,-2.4]),metric([-1.5,.8,3])]});
 const boardPoints=G.berthSampling.gangwayCenterlineGrid.map(p=>berthPoint(p,deck)),gw=G.berthSampling.gangwayWidth/(deck?G.deckSampling.pitch:G.berthSampling.metresPerCell),[ga,gb]=boardPoints;
 scene.structures.push(rect(ga[0],ga[1]-gw/2,gb[0]-ga[0],gw,'#b09567','#514d3e',.035,{structureId:'unique-gangway'}));for(let x=ga[0]+.1;x<gb[0];x+=.18*scale)scene.structures.push(line([[x,ga[1]-gw/2],[x,ga[1]+gw/2]],'#6c5b44',.018));
 scene.fixtures.gangway={id:'unique-gangway',dockId,centerline:boardPoints,width:gw,supports:[{role:'ship',at:ga},{role:'quay',at:gb}]};
 for(const[role,p]of [['ship',ga],['quay',gb]])scene.structures.push(rect(p[0]-.06*metresToScreen,p[1]-gw/2-.035*metresToScreen,.12*metresToScreen,gw+.07*metresToScreen,'#5d6051','#cbc4a1',.025,{structureId:`gangway-${role}-bearing`}));
 if(deck)scene.structures.push(label(9.5,8,'岸上 · 经跳板返回',.16,'#e0dcc8'));
 // Three permanent rack bases stay visible even when the one cargo crate moves.
 for(const[id,p]of Object.entries(G.fixtures.cargoRack.poses)){const[x,y]=pt(p),w=.7*scale,h=.64*scale;scene.structures.push(rect(x-w/2,y-h/2,w,h,'#4e5553','#bdac84',.035*scale,{structureId:`rack-${id}`}));for(const dx of[-.27,.27])scene.structures.push(rect(x+dx*scale-.035*scale,y-.29*scale,.07*scale,.58*scale,'#9e9a82'));}
 const socketLabels=[];for(const[id,p]of Object.entries(runtime.spec.ballast.slotCoordinates)){const[x,y]=pt(p),w=.62*scale,h=.56*scale;scene.fixtures.slots.push({id,at:[x,y]});scene.structures.push(rect(x-w/2,y-h/2,w,h,'#707773','#374447',.035*scale,{structureId:`socket-${id}`,mounting:'flush'}),rect(x-w/2+.07*scale,y-h/2+.06*scale,w-.14*scale,h-.12*scale,'#969b89','#bbc2a8',.017*scale));const weight=Object.entries(state.boat.positions).find(([,slot])=>slot===id);if(weight){const[wid]=weight,mass=runtime.spec.ballast.weights[wid],size=(mass===2?.34:.26)*scale;scene.fixtures.weights.push({id:wid,mass,slot:id});scene.structures.push(rect(x-size/2,y-size/2,size,size,mass===2?'#434c50':'#616c70','#d0c6a4',.035*scale,{weightId:wid}));socketLabels.push(label(x,y+.33*scale,`${id} ${wid.slice(1)}:${mass}`,.145*scale,'#f0e6c4',{weightId:wid,minPixels:deck?7:6}));}else socketLabels.push(label(x,y+.33*scale,id,.145*scale,'#e6ddc3',{minPixels:deck?7:6}));}
 const cargoPose=G.fixtures.cargoRack.poses[state.boat.cargo];if(cargoPose){const[x,y]=pt(cargoPose),w=.64*scale;scene.fixtures.cargo.push({id:'one-lamp-cargo',at:[x,y],state:state.boat.cargo});scene.structures.push(rect(x-w/2,y-w/2,w,w,'#b28b53','#453f35',.045*scale,{cargoId:'one-lamp-cargo'}),line([[x-w/2,y],[x+w/2,y]],'#e0c387',.08*scale),circle(x,y,.13*scale,'#bbbba0','#625d4b',.03*scale));}
 else if(state.boat.cargo==='ashore'){const target=runtime.entity(state.flags['c.cargoAtLamp']?'c.installLamp':'c.rollCargo'),[x,y]=berthPoint([target.x,target.y],deck),q=metresToScreen;scene.fixtures.cargo.push({id:'one-lamp-cargo',at:[x,y],state:'ashore',sourceRegion:target.regionId,sourceCell:[target.x,target.y]});scene.objects.push(rect(x-.23*q,y-.23*q,.46*q,.46*q,'#b28b53','#453f35',.04*q,{cargoId:'one-lamp-cargo'}),circle(x,y,.09*q,'#c5c8a4'));}
 const[helmX,helmY]=pt(G.fixtures.helm);scene.structures.push(line([[helmX,helmY+.4*scale],[helmX,helmY-.18*scale]],'#4a453a',.1*scale),line([[helmX-.24*scale,helmY-.18*scale],[helmX+.24*scale,helmY-.18*scale]],'#d3b985',.085*scale));
 const[sx,sy]=pt(G.fixtures.sternSignal.grid);scene.structures.push(circle(sx,sy,.105*scale,'#d7c18a','#525947',.035*scale));
 const hatch=pt(G.fixtures.smallCargoLocker.grid);scene.structures.push(rect(hatch[0]-.25*scale,hatch[1]-.18*scale,.5*scale,.36*scale,'#8b7453','#4d5148',.025*scale));
 // Both fixed shore bollards exist in every mooring state and both views.
 const mooring=G.fixtures.mooring,fairleads=[mooring.bowFairleadXYZ,mooring.sternFairleadXYZ].map(metric),bollards=mooring.shoreBollardsGrid.map(p=>berthPoint(p,deck));scene.fixtures.mooring={dockId,fairleads,bollards,lines:[]};
 for(const[i,end]of bollards.entries()){scene.structures.push(circle(...end,.14*metresToScreen,'#444f50','#c4c6b3',.025*metresToScreen,{structureId:`shore-bollard-${i}`}),line([[end[0]-.13*metresToScreen,end[1]],[end[0]+.13*metresToScreen,end[1]]],'#d3c5a6',.065*metresToScreen));if(state.boat.moored){const a=fairleads[i];scene.fixtures.mooring.lines.push({id:`main-mooring-${i}`,from:a,to:end});scene.structures.push(line([a,end],'#d4c197',.035*scale,{structureId:`main-mooring-${i}`}),circle(a[0],a[1],.04*scale,'#343c3a'));}}
 const activeDock=deck?state.boat.dock:r.id;
 if(activeDock==='C-M03'){
  if(state.boat.cargo==='left'){const body=pt(G.fixtures.gateWinch.body),handle=pt(G.fixtures.gateWinch.handle);scene.fixtures.devices.push({id:'one-gate-winch',body,handle});scene.structures.push(line([body,handle],'#b7bcaa',.10*scale,{structureId:'winch-connected-shaft'}),circle(...body,.24*scale,'#5f6c6d','#d6caa6',.055*scale),circle(...handle,.13*scale,null,'#c3baa0',.04*scale));const cable=G.fixtures.gateWinch.cablePathXZ.map(([X,Z])=>metric([X,1,Z]));scene.structures.push(line(cable,'#d1c190',.025*scale));}
  // Same floating gate slides into a side pocket, instead of vanishing.
  if(!deck){const open=Boolean(state.flags['c.barrierOpen']);scene.structures.push(rect(open?1.1:1.1,open?1:2,open?.65:5.3,.26,'#877c55','#c0b28b',.04,{structureId:'same-floating-gate',state:open?'in-side-pocket':'closed'}));if(!open)for(let x=1.2;x<6.3;x+=.36)scene.structures.push(line([[x,1.9],[x,2.34]],'#c3b188',.07));}
 }
 if(activeDock==='C-M05'){
  const f=G.fixtures.cargoDavit,foot=metric(f.hullMountXYZ),body=metric(f.outboardHousingXYZ),handle=metric(f.handleXYZ),stowed=Boolean(state.flags['c.craneStowed']);scene.fixtures.devices.push({id:'one-cargo-davit',foot,body,handle,stowed});scene.structures.push(line([foot,body,handle],'#303e45',.18*scale,{structureId:'davit-rigid-bracket'}),line([foot,body,handle],'#a8ada0',.09*scale),circle(...foot,.13*scale,'#9b9e91','#35444a'),circle(...handle,.16*scale,null,'#d0c7a7',.055*scale));const end=stowed?[body[0],body[1]-.3*scale]:[body[0]+.6*scale,body[1]-.6*scale];scene.structures.push(line([body,end],'#999e94',.11*scale),line([end,[end[0],end[1]+.5*scale]],'#d3c6a4',.025*scale));
  for(let y=3.9;y<6.1;y+=.22)scene.structures.push(line([berthPoint([7.6,y-.5],deck),berthPoint([8.4,y-.5],deck)],'#a6a48e',.065*metresToScreen,{structureId:'same-shore-rollway'}));
 }
 if(!deck)for(const e of view.entities.filter(e=>runtime.meets(state,e.visibleWhen)&&!e.completed&&e.kind!=='operation'&&e.kind!=='anchor'))scene.objects.push(...entityCommands(e).map(c=>({...c,entityId:e.id})));
 scene.objects.push(...entityCommands(state.location,{hero:true}),...socketLabels);for(const b of scene.boundaryRuns)if(b.kind==='rail')b.scale=scale;return scene;
}
